// AUTO-ASSEMBLED bonus content — kept SEPARATE from the board question bank so
// bonus rounds never reuse a question players already saw on the board.
//   RAPID_FIRE    : short Q&A for the rapid-fire / wager rounds ({q,a,accept[]}).
//   NAME_SETS     : normalized acceptable-answer lists for typed "Name as Many".
//   NAME_PROMPT_KEY: maps a human prompt to its NAME_SETS key (null => host counts).
const RAPID_FIRE = [
  {"q":"How many sides does a hexagon have?","a":"6","accept":["six","6"]},
  {"q":"What color do you get by mixing blue and yellow?","a":"Green","accept":["green"]},
  {"q":"How many legs does a spider have?","a":"8","accept":["eight","8"]},
  {"q":"What is the largest planet in our solar system?","a":"Jupiter","accept":["jupiter"]},
  {"q":"What gas do plants absorb from the air?","a":"Carbon dioxide","accept":["co2","carbon dioxide"]},
  {"q":"How many continents are there?","a":"7","accept":["seven","7"]},
  {"q":"What is the tallest animal in the world?","a":"Giraffe","accept":["giraffe","the giraffe"]},
  {"q":"What is the chemical symbol for gold?","a":"Au","accept":["au"]},
  {"q":"How many minutes are in an hour?","a":"60","accept":["sixty","60"]},
  {"q":"What is the largest country by area?","a":"Russia","accept":["russia"]},
  {"q":"What is the freezing point of water in Celsius?","a":"0","accept":["0","zero","0 degrees"]},
  {"q":"What is the fastest land animal?","a":"Cheetah","accept":["cheetah","the cheetah"]},
  {"q":"What is the smallest prime number?","a":"2","accept":["two","2"]},
  {"q":"Which planet is known as the Red Planet?","a":"Mars","accept":["mars"]},
  {"q":"What is the currency of Japan?","a":"Yen","accept":["yen","japanese yen"]},
  {"q":"What is the hardest natural substance on Earth?","a":"Diamond","accept":["diamond"]},
  {"q":"How many colors are in a rainbow?","a":"7","accept":["seven","7"]},
  {"q":"What is the largest ocean on Earth?","a":"Pacific Ocean","accept":["pacific","the pacific","pacific ocean"]},
  {"q":"What do bees collect from flowers?","a":"Nectar","accept":["nectar"]},
  {"q":"What is the capital of Japan?","a":"Tokyo","accept":["tokyo"]},
  {"q":"How many days are in a leap year?","a":"366","accept":["366","three hundred sixty six"]},
  {"q":"What is the main language spoken in Brazil?","a":"Portuguese","accept":["portuguese"]},
  {"q":"What is the chemical symbol for water?","a":"H2O","accept":["h2o","h20"]},
  {"q":"Which is the largest mammal?","a":"Blue whale","accept":["blue whale","the blue whale","whale"]},
  {"q":"What planet do we live on?","a":"Earth","accept":["earth","the earth"]},
  {"q":"How many strings does a standard guitar have?","a":"6","accept":["six","6"]},
  {"q":"What is the largest desert in the world?","a":"Antarctic Desert","accept":["antarctic desert","antarctica","antarctic"]},
  {"q":"What is the capital of France?","a":"Paris","accept":["paris"]},
  {"q":"What metal is liquid at room temperature?","a":"Mercury","accept":["mercury"]},
  {"q":"How many players are on a basketball team on the court?","a":"5","accept":["five","5"]},
  {"q":"What is the national animal of China?","a":"Giant panda","accept":["panda","giant panda"]},
  {"q":"What organ pumps blood through the body?","a":"Heart","accept":["heart","the heart"]},
  {"q":"What is the longest river in the world?","a":"Nile","accept":["nile","the nile","nile river"]},
  {"q":"How many sides does a triangle have?","a":"3","accept":["three","3"]},
  {"q":"What is frozen water called?","a":"Ice","accept":["ice"]},
  {"q":"What is the capital of Italy?","a":"Rome","accept":["rome"]},
  {"q":"Which bird is known for its colorful tail feathers and display?","a":"Peacock","accept":["peacock"]},
  {"q":"What is the closest planet to the Sun?","a":"Mercury","accept":["mercury"]},
  {"q":"How many wheels does a tricycle have?","a":"3","accept":["three","3"]},
  {"q":"What is the study of weather called?","a":"Meteorology","accept":["meteorology"]},
  {"q":"Which animal is known as man's best friend?","a":"Dog","accept":["dog","the dog"]},
  {"q":"What is the largest land animal?","a":"African elephant","accept":["elephant","the elephant","african elephant"]},
  {"q":"How many planets are in our solar system?","a":"8","accept":["eight","8"]},
  {"q":"What is the capital of England?","a":"London","accept":["london"]},
  {"q":"What vitamin do we get from sunlight?","a":"Vitamin D","accept":["vitamin d","d"]},
  {"q":"What is the chemical symbol for iron?","a":"Fe","accept":["fe"]},
  {"q":"Which ocean is the smallest?","a":"Arctic Ocean","accept":["arctic","arctic ocean"]},
  {"q":"How many zeros are in one million?","a":"6","accept":["six","6"]},
  {"q":"What is the capital of Spain?","a":"Madrid","accept":["madrid"]},
  {"q":"What do caterpillars turn into?","a":"Butterflies","accept":["butterfly","butterflies","a butterfly"]},
  {"q":"What is the largest organ in the human body?","a":"Skin","accept":["skin","the skin"]},
  {"q":"How many continents start with the letter A?","a":"3","accept":["three","3"]},
  {"q":"What is the national flower of Japan?","a":"Cherry blossom","accept":["cherry blossom","sakura"]},
  {"q":"What is the speed of light measured in?","a":"Meters per second","accept":["meters per second","m/s","metres per second"]},
  {"q":"Which country gave the Statue of Liberty to the USA?","a":"France","accept":["france"]},
  {"q":"What is the capital of Germany?","a":"Berlin","accept":["berlin"]},
  {"q":"How many teeth does an adult human typically have?","a":"32","accept":["32","thirty two"]},
  {"q":"What is the powerhouse of the cell?","a":"Mitochondria","accept":["mitochondria","the mitochondria","mitochondrion"]},
  {"q":"What is the most spoken language in the world by native speakers?","a":"Mandarin Chinese","accept":["mandarin","chinese","mandarin chinese"]},
  {"q":"Which planet is famous for its rings?","a":"Saturn","accept":["saturn"]},
  {"q":"What do you call a baby kangaroo?","a":"Joey","accept":["joey","a joey"]},
  {"q":"What is the capital of Russia?","a":"Moscow","accept":["moscow"]},
  {"q":"How many sides does a pentagon have?","a":"5","accept":["five","5"]},
  {"q":"What is the boiling point of water in Celsius?","a":"100","accept":["100","one hundred","100 degrees"]},
  {"q":"What is the largest country in South America?","a":"Brazil","accept":["brazil"]},
  {"q":"What is the study of living things called?","a":"Biology","accept":["biology"]},
  {"q":"Which planet is closest in size to Earth?","a":"Venus","accept":["venus"]},
  {"q":"What gas do humans need to breathe to live?","a":"Oxygen","accept":["oxygen","o2"]},
  {"q":"What is the capital of Canada?","a":"Ottawa","accept":["ottawa"]},
  {"q":"How many letters are in the English alphabet?","a":"26","accept":["26","twenty six"]},
  {"q":"What is the largest island in the world?","a":"Greenland","accept":["greenland"]},
  {"q":"What is the chemical symbol for sodium?","a":"Na","accept":["na"]},
  {"q":"Which sport uses a shuttlecock?","a":"Badminton","accept":["badminton"]},
  {"q":"What is the capital of Australia?","a":"Canberra","accept":["canberra"]},
  {"q":"What is the tallest mountain in the world?","a":"Mount Everest","accept":["everest","mount everest","mt everest"]},
  {"q":"How many bones are in the adult human body?","a":"206","accept":["206","two hundred six"]},
  {"q":"What color is chlorophyll?","a":"Green","accept":["green"]},
  {"q":"Which country has the Eiffel Tower?","a":"France","accept":["france"]},
  {"q":"What is the capital of China?","a":"Beijing","accept":["beijing","peking"]},
  {"q":"How many strings does a violin have?","a":"4","accept":["four","4"]},
  {"q":"What is the largest big cat in the world?","a":"Tiger","accept":["tiger","the tiger"]},
  {"q":"What is the square root of 64?","a":"8","accept":["eight","8"]},
  {"q":"Which planet spins on its side?","a":"Uranus","accept":["uranus"]},
  {"q":"What is the main ingredient in bread?","a":"Flour","accept":["flour"]},
  {"q":"What is the capital of Egypt?","a":"Cairo","accept":["cairo"]},
  {"q":"How many hearts does an octopus have?","a":"3","accept":["three","3"]},
  {"q":"What is the study of stars and space called?","a":"Astronomy","accept":["astronomy"]},
  {"q":"Which animal lays the largest eggs?","a":"Ostrich","accept":["ostrich","the ostrich"]},
  {"q":"What is the capital of India?","a":"New Delhi","accept":["new delhi","delhi"]},
  {"q":"How many degrees are in a right angle?","a":"90","accept":["90","ninety","90 degrees"]},
  {"q":"What is the chemical symbol for carbon?","a":"C","accept":["c"]},
  {"q":"Which planet is the hottest in the solar system?","a":"Venus","accept":["venus"]},
  {"q":"What is a group of wolves called?","a":"Pack","accept":["pack","a pack"]},
  {"q":"What is the capital of the United States?","a":"Washington, D.C.","accept":["washington","washington dc","washington d.c.","dc"]},
  {"q":"How many sides does an octagon have?","a":"8","accept":["eight","8"]},
  {"q":"What is the smallest planet in the solar system?","a":"Mercury","accept":["mercury"]},
  {"q":"What is the main gas in Earth's atmosphere?","a":"Nitrogen","accept":["nitrogen"]},
  {"q":"Which country is home to the kangaroo?","a":"Australia","accept":["australia"]},
  {"q":"What is the capital of Greece?","a":"Athens","accept":["athens"]},
  {"q":"How many players are on a soccer team on the field?","a":"11","accept":["eleven","11"]},
  {"q":"What is the largest type of penguin?","a":"Emperor penguin","accept":["emperor penguin","emperor","the emperor penguin"]},
  {"q":"What is 12 times 12?","a":"144","accept":["144","one hundred forty four"]},
  {"q":"Which sea creature has eight arms?","a":"Octopus","accept":["octopus","the octopus"]},
  {"q":"What is the capital of Brazil?","a":"Brasilia","accept":["brasilia"]},
  {"q":"What is the chemical symbol for potassium?","a":"K","accept":["k"]},
  {"q":"How many strings does a standard bass guitar have?","a":"4","accept":["four","4"]},
  {"q":"What is the largest reef system in the world?","a":"Great Barrier Reef","accept":["great barrier reef","the great barrier reef"]},
  {"q":"What color are emeralds?","a":"Green","accept":["green"]},
  {"q":"Which planet is named after the Roman god of the sea?","a":"Neptune","accept":["neptune"]},
  {"q":"What is the capital of Mexico?","a":"Mexico City","accept":["mexico city"]},
  {"q":"How many seconds are in a minute?","a":"60","accept":["sixty","60"]},
  {"q":"What is the fastest bird in the world?","a":"Peregrine falcon","accept":["peregrine falcon","peregrine","falcon"]},
  {"q":"What is the chemical symbol for oxygen?","a":"O","accept":["o"]},
  {"q":"Which continent is the Sahara Desert located on?","a":"Africa","accept":["africa"]},
  {"q":"What is the capital of South Korea?","a":"Seoul","accept":["seoul"]},
  {"q":"How many years are in a decade?","a":"10","accept":["ten","10"]},
  {"q":"What is the only mammal capable of true flight?","a":"Bat","accept":["bat","the bat"]},
  {"q":"What is 7 times 8?","a":"56","accept":["56","fifty six"]},
  {"q":"Which planet is known as the Morning Star?","a":"Venus","accept":["venus"]},
  {"q":"What is the capital of Argentina?","a":"Buenos Aires","accept":["buenos aires"]},
  {"q":"What do you call a doctor for teeth?","a":"Dentist","accept":["dentist","a dentist"]},
  {"q":"How many colors are on a traffic light?","a":"3","accept":["three","3"]},
  {"q":"What is the largest country in Africa by area?","a":"Algeria","accept":["algeria"]},
  {"q":"What is the chemical symbol for helium?","a":"He","accept":["he"]},
  {"q":"Which animal is known for changing its color?","a":"Chameleon","accept":["chameleon","the chameleon"]},
  {"q":"What is the capital of Turkey?","a":"Ankara","accept":["ankara"]},
  {"q":"How many wings does a bee have?","a":"4","accept":["four","4"]},
  {"q":"What is the study of rocks called?","a":"Geology","accept":["geology"]},
  {"q":"Which is the longest bone in the human body?","a":"Femur","accept":["femur","the femur","thigh bone"]},
  {"q":"What is the capital of Portugal?","a":"Lisbon","accept":["lisbon"]},
  {"q":"How many continents have penguins in the wild?","a":"5","accept":["five","5"]},
  {"q":"What is the most abundant gas in the universe?","a":"Hydrogen","accept":["hydrogen"]},
  {"q":"Which sport is played at Wimbledon?","a":"Tennis","accept":["tennis"]},
  {"q":"What is the capital of the Netherlands?","a":"Amsterdam","accept":["amsterdam"]},
  {"q":"What is 9 squared?","a":"81","accept":["81","eighty one"]},
  {"q":"Which large flightless bird is native to Africa?","a":"Ostrich","accept":["ostrich","the ostrich"]},
  {"q":"What is the chemical symbol for silver?","a":"Ag","accept":["ag"]},
  {"q":"Which country is shaped like a boot?","a":"Italy","accept":["italy"]},
  {"q":"What is the capital of Sweden?","a":"Stockholm","accept":["stockholm"]},
  {"q":"How many hours are in two days?","a":"48","accept":["48","forty eight"]},
  {"q":"What is the layer of gases surrounding Earth called?","a":"Atmosphere","accept":["atmosphere","the atmosphere"]},
  {"q":"Which animal has black and white stripes?","a":"Zebra","accept":["zebra","the zebra"]},
  {"q":"What is the capital of Norway?","a":"Oslo","accept":["oslo"]},
  {"q":"How many points is a touchdown worth in American football?","a":"6","accept":["six","6"]},
  {"q":"What is the largest internal organ in the human body?","a":"Liver","accept":["liver","the liver"]},
  {"q":"Which planet has the most moons?","a":"Saturn","accept":["saturn"]},
  {"q":"What is the capital of Thailand?","a":"Bangkok","accept":["bangkok"]},
  {"q":"How many strings does a standard ukulele have?","a":"4","accept":["four","4"]},
  {"q":"What is the process by which plants make food?","a":"Photosynthesis","accept":["photosynthesis"]},
  {"q":"Which is the smallest country in the world?","a":"Vatican City","accept":["vatican city","vatican","the vatican"]},
  {"q":"What is the capital of Ireland?","a":"Dublin","accept":["dublin"]},
  {"q":"How many sides does a square have?","a":"4","accept":["four","4"]},
  {"q":"What is the largest type of shark?","a":"Whale shark","accept":["whale shark","the whale shark"]},
  {"q":"Which gas makes soda fizzy?","a":"Carbon dioxide","accept":["carbon dioxide","co2"]},
  {"q":"What is the capital of Switzerland?","a":"Bern","accept":["bern","berne"]},
  {"q":"How many points is a free throw worth in basketball?","a":"1","accept":["one","1"]}
];

const NAME_SETS = {
 "countries_europe": [
  "albania",
  "andorra",
  "austria",
  "belarus",
  "belgium",
  "bosnia",
  "bosnia and herzegovina",
  "britain",
  "bulgaria",
  "croatia",
  "cyprus",
  "czech republic",
  "czechia",
  "denmark",
  "england",
  "estonia",
  "finland",
  "france",
  "germany",
  "great britain",
  "greece",
  "holland",
  "hungary",
  "iceland",
  "ireland",
  "italy",
  "kosovo",
  "latvia",
  "liechtenstein",
  "lithuania",
  "luxembourg",
  "macedonia",
  "malta",
  "moldova",
  "monaco",
  "montenegro",
  "netherlands",
  "north macedonia",
  "norway",
  "poland",
  "portugal",
  "romania",
  "russia",
  "san marino",
  "serbia",
  "slovakia",
  "slovenia",
  "spain",
  "sweden",
  "switzerland",
  "uk",
  "ukraine",
  "united kingdom",
  "vatican",
  "vatican city"
 ],
 "countries_africa": [
  "algeria",
  "angola",
  "benin",
  "botswana",
  "burkina faso",
  "burundi",
  "cabo verde",
  "cameroon",
  "cape verde",
  "central african republic",
  "chad",
  "comoros",
  "congo",
  "cote d ivoire",
  "democratic republic of congo",
  "djibouti",
  "dr congo",
  "drc",
  "egypt",
  "equatorial guinea",
  "eritrea",
  "eswatini",
  "ethiopia",
  "gabon",
  "gambia",
  "ghana",
  "guinea",
  "guinea bissau",
  "ivory coast",
  "kenya",
  "lesotho",
  "liberia",
  "libya",
  "madagascar",
  "malawi",
  "mali",
  "mauritania",
  "mauritius",
  "morocco",
  "mozambique",
  "namibia",
  "niger",
  "nigeria",
  "republic of congo",
  "rwanda",
  "sao tome and principe",
  "senegal",
  "seychelles",
  "sierra leone",
  "somalia",
  "south africa",
  "south sudan",
  "sudan",
  "swaziland",
  "tanzania",
  "togo",
  "tunisia",
  "uganda",
  "zambia",
  "zimbabwe"
 ],
 "countries_asia": [
  "afghanistan",
  "armenia",
  "azerbaijan",
  "bahrain",
  "bangladesh",
  "bhutan",
  "brunei",
  "burma",
  "cambodia",
  "china",
  "cyprus",
  "east timor",
  "georgia",
  "india",
  "indonesia",
  "iran",
  "iraq",
  "israel",
  "japan",
  "jordan",
  "kazakhstan",
  "korea",
  "kuwait",
  "kyrgyzstan",
  "laos",
  "lebanon",
  "malaysia",
  "maldives",
  "mongolia",
  "myanmar",
  "nepal",
  "north korea",
  "oman",
  "pakistan",
  "palestine",
  "philippines",
  "qatar",
  "saudi arabia",
  "singapore",
  "south korea",
  "sri lanka",
  "syria",
  "taiwan",
  "tajikistan",
  "thailand",
  "timor leste",
  "turkey",
  "turkmenistan",
  "uae",
  "united arab emirates",
  "uzbekistan",
  "vietnam",
  "yemen"
 ],
 "countries_north_america": [
  "america",
  "antigua and barbuda",
  "bahamas",
  "barbados",
  "belize",
  "canada",
  "costa rica",
  "cuba",
  "dominica",
  "dominican republic",
  "el salvador",
  "grenada",
  "guatemala",
  "haiti",
  "honduras",
  "jamaica",
  "mexico",
  "nicaragua",
  "panama",
  "saint kitts and nevis",
  "saint lucia",
  "saint vincent and grenadines",
  "trinidad and tobago",
  "united states",
  "united states of america",
  "us",
  "usa"
 ],
 "countries_south_america": [
  "argentina",
  "bolivia",
  "brazil",
  "chile",
  "colombia",
  "ecuador",
  "guyana",
  "paraguay",
  "peru",
  "suriname",
  "uruguay",
  "venezuela"
 ],
 "planets": [
  "earth",
  "jupiter",
  "mars",
  "mercury",
  "neptune",
  "saturn",
  "uranus",
  "venus"
 ],
 "elements_symbols": [
  "actinium",
  "aluminium",
  "aluminum",
  "americium",
  "antimony",
  "argon",
  "arsenic",
  "astatine",
  "barium",
  "berkelium",
  "beryllium",
  "bismuth",
  "bohrium",
  "boron",
  "bromine",
  "cadmium",
  "caesium",
  "calcium",
  "californium",
  "carbon",
  "cerium",
  "cesium",
  "chlorine",
  "chromium",
  "cobalt",
  "copernicium",
  "copper",
  "curium",
  "darmstadtium",
  "dubnium",
  "dysprosium",
  "einsteinium",
  "erbium",
  "europium",
  "fermium",
  "flerovium",
  "fluorine",
  "francium",
  "gadolinium",
  "gallium",
  "germanium",
  "gold",
  "hafnium",
  "hassium",
  "helium",
  "holmium",
  "hydrogen",
  "indium",
  "iodine",
  "iridium",
  "iron",
  "krypton",
  "lanthanum",
  "lawrencium",
  "lead",
  "lithium",
  "livermorium",
  "lutetium",
  "magnesium",
  "manganese",
  "meitnerium",
  "mendelevium",
  "mercury",
  "molybdenum",
  "moscovium",
  "neodymium",
  "neon",
  "neptunium",
  "nickel",
  "nihonium",
  "niobium",
  "nitrogen",
  "nobelium",
  "oganesson",
  "osmium",
  "oxygen",
  "palladium",
  "phosphorus",
  "platinum",
  "plutonium",
  "polonium",
  "potassium",
  "praseodymium",
  "promethium",
  "protactinium",
  "radium",
  "radon",
  "rhenium",
  "rhodium",
  "roentgenium",
  "rubidium",
  "ruthenium",
  "rutherfordium",
  "samarium",
  "scandium",
  "seaborgium",
  "selenium",
  "silicon",
  "silver",
  "sodium",
  "strontium",
  "sulfur",
  "sulphur",
  "tantalum",
  "technetium",
  "tellurium",
  "tennessine",
  "terbium",
  "thallium",
  "thorium",
  "thulium",
  "tin",
  "titanium",
  "tungsten",
  "uranium",
  "vanadium",
  "xenon",
  "ytterbium",
  "yttrium",
  "zinc",
  "zirconium"
 ],
 "nba_teams": [
  "76ers",
  "atlanta hawks",
  "blazers",
  "boston celtics",
  "brooklyn nets",
  "bucks",
  "bulls",
  "cavaliers",
  "cavs",
  "celtics",
  "charlotte hornets",
  "chicago bulls",
  "cleveland cavaliers",
  "clippers",
  "dallas mavericks",
  "denver nuggets",
  "detroit pistons",
  "golden state warriors",
  "grizzlies",
  "hawks",
  "heat",
  "hornets",
  "houston rockets",
  "indiana pacers",
  "jazz",
  "kings",
  "knicks",
  "la clippers",
  "la lakers",
  "lakers",
  "los angeles clippers",
  "los angeles lakers",
  "magic",
  "mavericks",
  "mavs",
  "memphis grizzlies",
  "miami heat",
  "milwaukee bucks",
  "minnesota timberwolves",
  "nets",
  "new orleans pelicans",
  "new york knicks",
  "nuggets",
  "okc thunder",
  "oklahoma city thunder",
  "orlando magic",
  "pacers",
  "pelicans",
  "philadelphia 76ers",
  "phoenix suns",
  "pistons",
  "portland trail blazers",
  "raptors",
  "rockets",
  "sacramento kings",
  "san antonio spurs",
  "sixers",
  "spurs",
  "suns",
  "thunder",
  "timberwolves",
  "toronto raptors",
  "trail blazers",
  "utah jazz",
  "warriors",
  "washington wizards",
  "wizards",
  "wolves"
 ],
 "us_states": [
  "alabama",
  "alaska",
  "arizona",
  "arkansas",
  "california",
  "colorado",
  "connecticut",
  "delaware",
  "florida",
  "georgia",
  "hawaii",
  "idaho",
  "illinois",
  "indiana",
  "iowa",
  "kansas",
  "kentucky",
  "louisiana",
  "maine",
  "maryland",
  "massachusetts",
  "michigan",
  "minnesota",
  "mississippi",
  "missouri",
  "montana",
  "nebraska",
  "nevada",
  "new hampshire",
  "new jersey",
  "new mexico",
  "new york",
  "north carolina",
  "north dakota",
  "ohio",
  "oklahoma",
  "oregon",
  "pennsylvania",
  "rhode island",
  "south carolina",
  "south dakota",
  "tennessee",
  "texas",
  "utah",
  "vermont",
  "virginia",
  "washington",
  "west virginia",
  "wisconsin",
  "wyoming"
 ],
 "world_capitals": [
  "abu dhabi",
  "abuja",
  "accra",
  "algiers",
  "amman",
  "amsterdam",
  "ankara",
  "athens",
  "baghdad",
  "baku",
  "bangkok",
  "beijing",
  "beirut",
  "belgrade",
  "berlin",
  "bern",
  "bogota",
  "brasilia",
  "bratislava",
  "brussels",
  "bucharest",
  "budapest",
  "buenos aires",
  "cairo",
  "canberra",
  "cape town",
  "caracas",
  "copenhagen",
  "damascus",
  "delhi",
  "dhaka",
  "doha",
  "dublin",
  "hanoi",
  "havana",
  "helsinki",
  "islamabad",
  "jakarta",
  "jerusalem",
  "kabul",
  "kiev",
  "kuala lumpur",
  "kuwait city",
  "kyiv",
  "lima",
  "lisbon",
  "london",
  "madrid",
  "manila",
  "mexico city",
  "minsk",
  "moscow",
  "nairobi",
  "new delhi",
  "oslo",
  "ottawa",
  "paris",
  "prague",
  "pretoria",
  "rabat",
  "reykjavik",
  "riyadh",
  "rome",
  "santiago",
  "seoul",
  "singapore",
  "sofia",
  "stockholm",
  "tehran",
  "tirana",
  "tokyo",
  "vienna",
  "warsaw",
  "washington",
  "washington dc",
  "wellington",
  "yerevan"
 ]
};

const NAME_PROMPT_KEY = {
 "Countries in Europe": "countries_europe",
 "Countries in Africa": "countries_africa",
 "Countries in Asia": "countries_asia",
 "Countries in North America": "countries_north_america",
 "Countries in South America": "countries_south_america",
 "World capital cities": "world_capitals",
 "U.S. states": "us_states",
 "Planets in the Solar System": "planets",
 "Elements on the periodic table": "elements_symbols",
 "NBA teams": "nba_teams"
};
