// Extra content: more questions for existing categories (merged & de-duped to
// reduce repetition), 3 new categories, Family Feud data, and name-game prompts.

// Additional questions appended to existing categories + brand-new categories.
const EXTRA_QUESTIONS = {
  "General Knowledge": [
    { q: "What is the study of fungi called?", a: "Mycology", points: 600, type: "text" },
    { q: "Which vitamin does the human body produce when exposed to sunlight?", a: "Vitamin D", points: 600, type: "text" },
    { q: "What is the name for a word that reads the same forwards and backwards?", a: "A palindrome", points: 600, type: "text" },
    { q: "How many strings does a standard violin have?", a: "Four", points: 400, type: "text" },
    { q: "What is the chemical symbol for sodium?", a: "Na", points: 200, type: "text" },
    { q: "How many sides does a hexagon have?", a: "Six", points: 200, type: "text" },
    { q: "Which philosopher wrote Critique of Pure Reason?", a: "Immanuel Kant", points: 800, type: "text" },
    { q: "What is the smallest bone in the human body?", a: "The stapes", points: 800, type: "text" },
    { q: "Which scientist formulated the uncertainty principle?", a: "Werner Heisenberg", points: 800, type: "text" },
    { q: "Which element has the highest melting point of all elements?", a: "Tungsten", points: 1000, type: "text" },
    { q: "What protein gives skin and hair its structure and strength?", a: "Keratin", points: 1000, type: "text" },
    { q: "In economics, what term describes a sustained fall in general prices?", a: "Deflation", points: 1000, type: "text" }
  ],
  "Sports": [
    { q: "Which boxer was known as The Greatest and lit the 1996 Olympic torch?", a: "Muhammad Ali", points: 600, type: "text" },
    { q: "In cricket, what is a bowler taking three wickets with consecutive balls called?", a: "A hat-trick", points: 600, type: "text" },
    { q: "Which Formula 1 team is the most successful by constructors' championships?", a: "Ferrari", points: 600, type: "text" },
    { q: "In what sport is the Ryder Cup contested?", a: "Golf", points: 400, type: "text" },
    { q: "How many players are on the ice per team in hockey, including the goalie?", a: "Six", points: 400, type: "text" },
    { q: "In rugby union, how many points is a try worth?", a: "Five", points: 800, type: "text" },
    { q: "In baseball, what is hitting a single, double, triple, and home run in one game called?", a: "Hitting for the cycle", points: 800, type: "text" },
    { q: "In fencing, what are the three weapons used?", a: "Foil, epee, and sabre", points: 1000, type: "text" }
  ],
  "History": [
    { q: "Which Roman emperor was the first to convert to Christianity?", a: "Constantine the Great", points: 800, type: "text" },
    { q: "What trade network connected Asia and Europe across Central Asia?", a: "The Silk Road", points: 800, type: "text" },
    { q: "Which Byzantine emperor codified Roman law into the Corpus Juris Civilis?", a: "Justinian I", points: 1000, type: "text" },
    { q: "In what year did the Ottoman Empire capture Constantinople?", a: "1453", points: 1000, type: "text" },
    { q: "Which empire was ruled by Genghis Khan?", a: "The Mongol Empire", points: 400, type: "text" },
    { q: "Who led the nonviolent independence movement in India?", a: "Mahatma Gandhi", points: 600, type: "text" }
  ],
  "Geography": [
    { q: "Which African country was never formally colonized by a European power?", a: "Ethiopia", points: 600, type: "text" },
    { q: "Which mountain range separates Europe from Asia?", a: "The Ural Mountains", points: 600, type: "text" },
    { q: "Through how many countries does the equator pass?", a: "Thirteen", points: 800, type: "text" },
    { q: "Which sea is the saltiest outlet-free body of water bordering Jordan and Israel?", a: "The Dead Sea", points: 800, type: "text" },
    { q: "Which is the only country to border both the Caspian Sea and the Persian Gulf?", a: "Iran", points: 1000, type: "text" },
    { q: "Which Pacific island republic comprising over 300 islands sits near the date line?", a: "Fiji", points: 1000, type: "text" }
  ],
  "Movies & TV": [
    { q: "Which TV series is set in the fictional town of Hawkins, Indiana?", a: "Stranger Things", points: 400, type: "text" },
    { q: "Which actor voiced Woody in the Toy Story films?", a: "Tom Hanks", points: 600, type: "text" },
    { q: "In The Godfather, what is the Corleone family business front?", a: "Olive oil importing", points: 800, type: "text" },
    { q: "Which actress won the Best Actress Oscar for La La Land?", a: "Emma Stone", points: 800, type: "text" },
    { q: "What was the first non-English-language film to win Best Picture?", a: "Parasite", points: 1000, type: "text" },
    { q: "Who was the first African American to win the Best Actor Academy Award?", a: "Sidney Poitier", points: 1000, type: "text" }
  ],
  "Music & Songs": [
    { q: "Which 1980s song by Toto references blessing the rains in Africa?", a: "Africa", points: 200, type: "text" },
    { q: "Which streaming service was founded in Sweden in 2006?", a: "Spotify", points: 200, type: "text" },
    { q: "Which genre of music originated in the Bronx, New York, in the 1970s?", a: "Hip hop", points: 600, type: "text" },
    { q: "Which Brazilian genre blends samba and jazz, popularized by The Girl from Ipanema?", a: "Bossa nova", points: 600, type: "text" },
    { q: "Which Nigerian musician pioneered the Afrobeat genre?", a: "Fela Kuti", points: 800, type: "text" },
    { q: "What scale of five notes per octave is common in folk and blues?", a: "Pentatonic scale", points: 1000, type: "text" },
    { q: "Which German term means a recurring musical theme tied to a character, used by Wagner?", a: "Leitmotif", points: 1000, type: "text" }
  ],
  "Science": [
    { q: "What part of the human body produces insulin?", a: "The pancreas", points: 400, type: "text" },
    { q: "What type of bond involves the sharing of electron pairs between atoms?", a: "Covalent bond", points: 600, type: "text" },
    { q: "What is the name for the change of a solid directly into a gas?", a: "Sublimation", points: 800, type: "text" },
    { q: "What is the SI unit of force?", a: "The newton", points: 800, type: "text" },
    { q: "What is the term for a substance that speeds up a reaction without being consumed?", a: "A catalyst", points: 1000, type: "text" },
    { q: "Who arranged the periodic table by atomic weight?", a: "Dmitri Mendeleev", points: 1000, type: "text" }
  ],
  "Animals & Nature": [
    { q: "Which bird is known for mimicking human speech?", a: "The parrot", points: 200, type: "text" },
    { q: "What is a young kangaroo called?", a: "A joey", points: 200, type: "text" },
    { q: "Which animal has the longest migration of any mammal?", a: "The gray whale", points: 600, type: "text" },
    { q: "What is the term for a plant or animal living on another organism?", a: "A parasite", points: 800, type: "text" },
    { q: "What is the only continent with no native reptiles?", a: "Antarctica", points: 800, type: "text" },
    { q: "Which living creature has the most powerful bite force?", a: "The saltwater crocodile", points: 1000, type: "text" }
  ],
  "Food & Drink": [
    { q: "Which nut is used to make marzipan?", a: "Almond", points: 400, type: "text" },
    { q: "What type of pastry is used to make profiteroles?", a: "Choux pastry", points: 400, type: "text" },
    { q: "Which fermented Korean dish is made from salted vegetables, usually cabbage?", a: "Kimchi", points: 600, type: "text" },
    { q: "Which Italian city gives traditional balsamic vinegar its origin name?", a: "Modena", points: 600, type: "text" },
    { q: "What chemical compound makes chili peppers taste hot?", a: "Capsaicin", points: 1000, type: "text" },
    { q: "What enzyme in pineapple breaks down protein and stops gelatin setting?", a: "Bromelain", points: 1000, type: "text" },
    { q: "What is the Spanish chilled tomato-based soup called?", a: "Gazpacho", points: 800, type: "text" }
  ],
  "Famous People": [
    { q: "Which explorer led the first expedition to circumnavigate the globe?", a: "Ferdinand Magellan", points: 600, type: "text" },
    { q: "Which mathematician is called the father of the computer for his Analytical Engine?", a: "Charles Babbage", points: 800, type: "text" },
    { q: "Which philosopher wrote The Republic?", a: "Plato", points: 800, type: "text" },
    { q: "Which Persian scholar wrote The Canon of Medicine?", a: "Avicenna (Ibn Sina)", points: 1000, type: "text" },
    { q: "Which Dutch microscopist is known as the father of microbiology?", a: "Antonie van Leeuwenhoek", points: 1000, type: "text" }
  ],
  "Technology & Inventions": [
    { q: "What handheld Sony device from 1979 popularized portable cassette music?", a: "The Walkman", points: 200, type: "text" },
    { q: "Which Hungarian inventor created the rotating cube puzzle in 1974?", a: "Erno Rubik", points: 400, type: "text" },
    { q: "Which French inventor created a system of raised dots for the blind to read by touch?", a: "Louis Braille", points: 600, type: "text" },
    { q: "What audio format did Philips and Sony introduce in 1982 on a 12-cm disc?", a: "The compact disc", points: 600, type: "text" },
    { q: "Which Italian physicist built the first electric battery around 1800?", a: "Alessandro Volta", points: 800, type: "text" },
    { q: "Which naval officer and computer scientist developed the first compiler?", a: "Grace Hopper", points: 1000, type: "text" },
    { q: "Which German engineer patented the first practical four-stroke engine in 1876?", a: "Nikolaus Otto", points: 1000, type: "text" }
  ],
  "Space & Astronomy": [
    { q: "What is the second-largest planet in our Solar System?", a: "Saturn", points: 400, type: "text" },
    { q: "What is the largest volcano in the Solar System, found on Mars?", a: "Olympus Mons", points: 600, type: "text" },
    { q: "What is the region of icy bodies beyond Neptune where many comets originate?", a: "The Kuiper Belt", points: 600, type: "text" },
    { q: "What is the supermassive black hole at the center of the Milky Way called?", a: "Sagittarius A*", points: 1000, type: "text" },
    { q: "What unit of cosmic distance equals about 3.26 light-years?", a: "A parsec", points: 1000, type: "text" },
    { q: "What hypothetical cloud of icy objects surrounds the Solar System?", a: "The Oort Cloud", points: 800, type: "text" }
  ],
  "Art & Literature": [
    { q: "What art movement is named after Monet's painting Impression, Sunrise?", a: "Impressionism", points: 200, type: "text" },
    { q: "Which Dutch master painted The Night Watch?", a: "Rembrandt", points: 600, type: "text" },
    { q: "Which American author wrote The Great Gatsby?", a: "F. Scott Fitzgerald", points: 400, type: "text" },
    { q: "Which American poet wrote The Raven?", a: "Edgar Allan Poe", points: 800, type: "text" },
    { q: "Which Japanese author wrote The Tale of Genji, often called the first novel?", a: "Murasaki Shikibu", points: 1000, type: "text" },
    { q: "Which Argentine writer wrote the story collections Ficciones and Labyrinths?", a: "Jorge Luis Borges", points: 1000, type: "text" }
  ],
  "Pop Culture": [
    { q: "Which social media app known for short videos is owned by ByteDance?", a: "TikTok", points: 200, type: "text" },
    { q: "Which boy band did Harry Styles rise to fame with?", a: "One Direction", points: 200, type: "text" },
    { q: "Which Colombian singer is known for Hips Don't Lie?", a: "Shakira", points: 400, type: "text" },
    { q: "Which South Korean group had the hit Dynamite?", a: "BTS", points: 400, type: "text" },
    { q: "Which 2003 fantasy film won eleven Academy Awards?", a: "The Lord of the Rings: The Return of the King", points: 600, type: "text" },
    { q: "Which South Korean survival drama became Netflix's most-watched series in 2021?", a: "Squid Game", points: 1000, type: "text" },
    { q: "Which musician, born Stefani Germanotta, took a stage name from a Queen song?", a: "Lady Gaga", points: 1000, type: "text" }
  ],
  "Famous Landmarks": [
    { q: "Which red sandstone rock-cut city in Jordan is a famous landmark?", a: "Petra", points: 400, type: "text" },
    { q: "Which domed cathedral designed partly by Michelangelo is the largest church in Vatican City?", a: "St. Peter's Basilica", points: 600, type: "text" },
    { q: "Which 5th-century rock fortress in Sri Lanka was built by King Kashyapa?", a: "Sigiriya", points: 600, type: "text" },
    { q: "Which giant statue of Christ overlooks Rio de Janeiro?", a: "Christ the Redeemer", points: 800, type: "text" },
    { q: "Which red sandstone Mughal fort in Delhi was the emperors' main residence?", a: "The Red Fort", points: 1000, type: "text" },
    { q: "Which desert city in Syria was ruled by Queen Zenobia?", a: "Palmyra", points: 1000, type: "text" }
  ],

  "Logos & Brands": [
    { q: "Which technology company's logo is an apple with a bite taken out of it?", a: "Apple", points: 200, type: "text" },
    { q: "Which fast-food chain is known for its golden arches logo?", a: "McDonald's", points: 200, type: "text" },
    { q: "Which sportswear brand uses a curved checkmark called the swoosh?", a: "Nike", points: 200, type: "text" },
    { q: "Which coffeehouse chain has a green logo featuring a twin-tailed mermaid?", a: "Starbucks", points: 200, type: "text" },
    { q: "Which search engine uses a multicolored logo in blue, red, yellow, and green?", a: "Google", points: 200, type: "text" },
    { q: "Which social media platform uses a white lowercase f on a blue background?", a: "Facebook", points: 200, type: "text" },
    { q: "Which car company uses a three-pointed star inside a circle?", a: "Mercedes-Benz", points: 200, type: "text" },
    { q: "Which soft drink uses white flowing cursive script on a red background?", a: "Coca-Cola", points: 200, type: "text" },
    { q: "Which luxury car brand uses four interlocking rings?", a: "Audi", points: 400, type: "text" },
    { q: "Which online retailer's logo has an arrow from the letter A to the letter Z?", a: "Amazon", points: 400, type: "text" },
    { q: "Which car company uses a prancing horse as its emblem?", a: "Ferrari", points: 400, type: "text" },
    { q: "Which fast-food chain uses a smiling girl with red braided pigtails?", a: "Wendy's", points: 400, type: "text" },
    { q: "Which sportswear brand uses three parallel stripes?", a: "Adidas", points: 400, type: "text" },
    { q: "Which streaming service uses a single red capital letter N?", a: "Netflix", points: 400, type: "text" },
    { q: "Which credit card company uses two overlapping red and yellow circles?", a: "Mastercard", points: 400, type: "text" },
    { q: "Which car company uses a blue and white roundel resembling a spinning propeller?", a: "BMW", points: 400, type: "text" },
    { q: "Which luxury fashion brand uses interlocking double C letters?", a: "Chanel", points: 600, type: "text" },
    { q: "Which delivery company used the slogan 'What can Brown do for you?'", a: "UPS", points: 600, type: "text" },
    { q: "Which automaker uses a logo of a lion standing on its hind legs?", a: "Peugeot", points: 600, type: "text" },
    { q: "Which clothing brand uses a small polo player on horseback?", a: "Ralph Lauren", points: 600, type: "text" },
    { q: "Which fried chicken chain features its founder Colonel Sanders?", a: "KFC", points: 600, type: "text" },
    { q: "Which automobile company uses a blue oval with cursive white script?", a: "Ford", points: 600, type: "text" },
    { q: "Which jeweler is known for its robin's-egg blue boxes?", a: "Tiffany & Co.", points: 600, type: "text" },
    { q: "Which camera and film company had a red and yellow 'K' logo?", a: "Kodak", points: 600, type: "text" },
    { q: "Which luxury car brand uses a black bull on a gold shield?", a: "Lamborghini", points: 800, type: "text" },
    { q: "Which Italian sports car maker uses a trident as its emblem?", a: "Maserati", points: 800, type: "text" },
    { q: "Which fashion brand uses a crocodile as its logo?", a: "Lacoste", points: 800, type: "text" },
    { q: "Which beverage company uses a red, white, and blue circular logo?", a: "Pepsi", points: 800, type: "text" },
    { q: "Which luxury goods company uses interlocking L and V initials?", a: "Louis Vuitton", points: 800, type: "text" },
    { q: "Which oil company uses a green and yellow sunburst logo called the Helios?", a: "BP", points: 800, type: "text" },
    { q: "Which car maker uses three diamonds arranged in a triangle?", a: "Mitsubishi", points: 800, type: "text" },
    { q: "Which shipping company hides an arrow between two letters of its purple-and-orange logo?", a: "FedEx", points: 800, type: "text" },
    { q: "Which luxury watch brand uses a five-pointed crown as its logo?", a: "Rolex", points: 1000, type: "text" },
    { q: "Which Spanish fashion retailer in the Inditex group uses tightly overlapping serif letters?", a: "Zara", points: 1000, type: "text" },
    { q: "The Alfa Romeo logo features a serpent and the red cross of which Italian city?", a: "Milan", points: 1000, type: "text" },
    { q: "Which French tire company uses a mascot made of stacked white tires, called Bibendum?", a: "Michelin", points: 1000, type: "text" },
    { q: "Which carmaker's emblem shows a sailing ship, reflecting its Gothenburg origins?", a: "Volvo", points: 1000, type: "text" },
    { q: "Which audio brand uses a stylized lowercase 'b' inside a circle?", a: "Beats", points: 1000, type: "text" },
    { q: "Which tech company's mascot is a green robot?", a: "Android", points: 1000, type: "text" },
    { q: "Which sportswear brand uses a puma (big cat) leaping in its logo?", a: "Puma", points: 1000, type: "text" }
  ],
  "Cartoons & Animation": [
    { q: "Which Disney mouse is known for his red shorts and white gloves?", a: "Mickey Mouse", points: 200, type: "text" },
    { q: "In The Simpsons, what is the first name of the bald father?", a: "Homer", points: 200, type: "text" },
    { q: "Which yellow sea sponge lives in a pineapple under the sea?", a: "SpongeBob SquarePants", points: 200, type: "text" },
    { q: "Which Looney Tunes rabbit asks 'What's up, Doc?'", a: "Bugs Bunny", points: 200, type: "text" },
    { q: "In Finding Nemo, what type of fish is Nemo?", a: "A clownfish", points: 200, type: "text" },
    { q: "Which Disney movie features a young lion named Simba?", a: "The Lion King", points: 200, type: "text" },
    { q: "In Tom and Jerry, what kind of animal is Jerry?", a: "A mouse", points: 200, type: "text" },
    { q: "Which Great Dane solves mysteries with teens in the Mystery Machine?", a: "Scooby-Doo", points: 200, type: "text" },
    { q: "Which Japanese franchise features an electric mouse named Pikachu?", a: "Pokemon", points: 400, type: "text" },
    { q: "In Rick and Morty, what is the relationship between the two title characters?", a: "Grandfather and grandson", points: 400, type: "text" },
    { q: "Which Pixar film features a robot cleaning up an abandoned Earth?", a: "WALL-E", points: 400, type: "text" },
    { q: "Which animated sitcom centers on Peter Griffin in the town of Quahog?", a: "Family Guy", points: 400, type: "text" },
    { q: "In Toy Story, what is the name of the cowboy doll voiced by Tom Hanks?", a: "Woody", points: 400, type: "text" },
    { q: "Which Cartoon Network show follows Finn and a dog named Jake in the Land of Ooo?", a: "Adventure Time", points: 400, type: "text" },
    { q: "Which film features a girl named Coraline who finds a parallel world?", a: "Coraline", points: 400, type: "text" },
    { q: "In Avatar: The Last Airbender, what element does Aang master last?", a: "Fire", points: 400, type: "text" },
    { q: "Which Studio Ghibli film features Chihiro working in a bathhouse for spirits?", a: "Spirited Away", points: 600, type: "text" },
    { q: "In South Park, which parka-wearing character repeatedly dies in early episodes?", a: "Kenny", points: 600, type: "text" },
    { q: "Which 1988 anime film by Katsuhiro Otomo is set in Neo-Tokyo?", a: "Akira", points: 600, type: "text" },
    { q: "In Aladdin, what is the name of Jafar's parrot?", a: "Iago", points: 600, type: "text" },
    { q: "Which series follows the Pines twins spending summer in a mysterious Oregon town?", a: "Gravity Falls", points: 600, type: "text" },
    { q: "Which Pixar film personifies the emotions inside a girl named Riley?", a: "Inside Out", points: 600, type: "text" },
    { q: "In Futurama, what is the name of the alcohol-powered robot?", a: "Bender", points: 600, type: "text" },
    { q: "Which 1940 Disney film pairs classical music with animation?", a: "Fantasia", points: 600, type: "text" },
    { q: "Which 1937 Disney film was the first feature-length cel-animated movie?", a: "Snow White and the Seven Dwarfs", points: 800, type: "text" },
    { q: "In Cowboy Bebop, what is the name of the corgi crew member?", a: "Ein", points: 800, type: "text" },
    { q: "Which Studio Ghibli film features a castle powered by a fire demon named Calcifer?", a: "Howl's Moving Castle", points: 800, type: "text" },
    { q: "Which Genndy Tartakovsky series follows a samurai displaced in time?", a: "Samurai Jack", points: 800, type: "text" },
    { q: "In The Simpsons, who runs the Kwik-E-Mart?", a: "Apu", points: 800, type: "text" },
    { q: "Which Don Bluth film follows a mouse named Fievel emigrating to America?", a: "An American Tail", points: 800, type: "text" },
    { q: "In BoJack Horseman, what type of animal is the title character?", a: "A horse", points: 800, type: "text" },
    { q: "Which 1968 Beatles animated film features the song Yellow Submarine?", a: "Yellow Submarine", points: 800, type: "text" },
    { q: "Which 1995 anime by Mamoru Oshii follows the cyborg Major Motoko Kusanagi?", a: "Ghost in the Shell", points: 1000, type: "text" },
    { q: "Which animator created the stop-motion duo Wallace and Gromit?", a: "Nick Park", points: 1000, type: "text" },
    { q: "In the 1960s series The Flintstones, what is the Flintstones' pet dinosaur called?", a: "Dino", points: 1000, type: "text" },
    { q: "Which Studio Ghibli film by Isao Takahata follows two siblings in wartime Japan?", a: "Grave of the Fireflies", points: 1000, type: "text" },
    { q: "In Neon Genesis Evangelion, what are the giant biomechanical units called?", a: "Evangelions (Evas)", points: 1000, type: "text" },
    { q: "Which 1981 animated anthology film featured a glowing green orb called the Loc-Nar?", a: "Heavy Metal", points: 1000, type: "text" },
    { q: "Which French animated film from 1973 is known in English as Fantastic Planet?", a: "Fantastic Planet", points: 1000, type: "text" },
    { q: "Which Hayao Miyazaki film features a forest spirit and a girl named San?", a: "Princess Mononoke", points: 1000, type: "text" }
  ],
  "TV Shows": [
    { q: "Which sitcom follows six friends in New York and a coffee shop called Central Perk?", a: "Friends", points: 200, type: "text" },
    { q: "Which HBO fantasy series features the Iron Throne?", a: "Game of Thrones", points: 200, type: "text" },
    { q: "Which sitcom is set in a Boston bar where everybody knows your name?", a: "Cheers", points: 200, type: "text" },
    { q: "Which series follows chemistry teacher Walter White making methamphetamine?", a: "Breaking Bad", points: 200, type: "text" },
    { q: "Which mockumentary sitcom is set at Dunder Mifflin in Scranton?", a: "The Office", points: 200, type: "text" },
    { q: "Which medical drama centers on Meredith Grey at a Seattle hospital?", a: "Grey's Anatomy", points: 200, type: "text" },
    { q: "Which 1980s-set sci-fi series features a girl named Eleven and the Upside Down?", a: "Stranger Things", points: 200, type: "text" },
    { q: "Which sitcom centers on physicist Sheldon Cooper and his friends?", a: "The Big Bang Theory", points: 200, type: "text" },
    { q: "Which prequel to Breaking Bad follows lawyer Jimmy McGill?", a: "Better Call Saul", points: 400, type: "text" },
    { q: "Which mockumentary sitcom follows the Pritchett-Dunphy-Tucker clan?", a: "Modern Family", points: 400, type: "text" },
    { q: "Which HBO drama follows New Jersey mob boss Tony Soprano?", a: "The Sopranos", points: 400, type: "text" },
    { q: "Which British sci-fi series follows a time-traveling alien who pilots the TARDIS?", a: "Doctor Who", points: 400, type: "text" },
    { q: "Which workplace sitcom is set in the parks department of Pawnee, Indiana?", a: "Parks and Recreation", points: 400, type: "text" },
    { q: "Which period drama follows the Crawley family and their servants at an English estate?", a: "Downton Abbey", points: 400, type: "text" },
    { q: "Which Baltimore crime drama by David Simon explored the city's drug trade?", a: "The Wire", points: 400, type: "text" },
    { q: "Which Netflix drama follows Queen Elizabeth II and the royal family?", a: "The Crown", points: 400, type: "text" },
    { q: "Which series followed plane crash survivors on a mysterious island?", a: "Lost", points: 600, type: "text" },
    { q: "Which AMC series follows Rick Grimes surviving a zombie apocalypse?", a: "The Walking Dead", points: 600, type: "text" },
    { q: "Which BBC crime drama follows the Shelby family in 1920s Birmingham?", a: "Peaky Blinders", points: 600, type: "text" },
    { q: "Which AMC 1960s-set drama follows ad executive Don Draper?", a: "Mad Men", points: 600, type: "text" },
    { q: "Which sitcom stars Larry David as a fictionalized version of himself?", a: "Curb Your Enthusiasm", points: 600, type: "text" },
    { q: "Which anthology series created by Rod Serling began in 1959?", a: "The Twilight Zone", points: 600, type: "text" },
    { q: "Which drama by Aaron Sorkin depicted a fictional U.S. presidential staff?", a: "The West Wing", points: 600, type: "text" },
    { q: "Which British anthology series explores the dark side of technology?", a: "Black Mirror", points: 600, type: "text" },
    { q: "Which German Netflix time-travel series is set in the town of Winden?", a: "Dark", points: 800, type: "text" },
    { q: "Which British sitcom set in a Torquay hotel starred John Cleese?", a: "Fawlty Towers", points: 800, type: "text" },
    { q: "Which 1980s detective series starred Tom Selleck in Hawaii?", a: "Magnum, P.I.", points: 800, type: "text" },
    { q: "Which Danish drama follows Birgitte Nyborg becoming prime minister?", a: "Borgen", points: 800, type: "text" },
    { q: "Which legal drama starred Julianna Margulies as Alicia Florrick?", a: "The Good Wife", points: 800, type: "text" },
    { q: "Which 1970s sitcom spun off from All in the Family had the theme 'Movin' On Up'?", a: "The Jeffersons", points: 800, type: "text" },
    { q: "Which series began with the investigation into the death of Laura Palmer?", a: "Twin Peaks", points: 800, type: "text" },
    { q: "Which 1960s anthology hosted by Alfred Hitchcock featured suspense tales?", a: "Alfred Hitchcock Presents", points: 800, type: "text" },
    { q: "Which 1967 series featured a former agent held in a place called the Village?", a: "The Prisoner", points: 1000, type: "text" },
    { q: "Which 1981 serial adaptation of an Evelyn Waugh novel starred Jeremy Irons?", a: "Brideshead Revisited", points: 1000, type: "text" },
    { q: "Which Israeli thriller inspired the American series Homeland?", a: "Prisoners of War", points: 1000, type: "text" },
    { q: "Which French drama about a talent agency is known in English as Call My Agent?", a: "Dix pour cent", points: 1000, type: "text" },
    { q: "Which 1986 Dennis Potter series starred Michael Gambon as a hospitalized writer?", a: "The Singing Detective", points: 1000, type: "text" },
    { q: "Which 1990 David Lynch series was set in a Pacific Northwest logging town?", a: "Twin Peaks", points: 1000, type: "text" },
    { q: "Which long-running British soap is set in Albert Square in London's East End?", a: "EastEnders", points: 1000, type: "text" },
    { q: "Which sci-fi series created by Gene Roddenberry premiered in 1966?", a: "Star Trek", points: 1000, type: "text" }
  ]
};

// 'Family Feud' style survey prompts: most popular answer listed first.
const FAMILY_FEUD = [
  { prompt: "We asked 100 people: name something you do first thing in the morning.", answers: ["Brush teeth", "Check phone", "Drink coffee", "Shower", "Eat breakfast", "Hit snooze"] },
  { prompt: "We asked 100 people: name a food that is messy to eat.", answers: ["Spaghetti", "Ribs", "Tacos", "Burgers", "Ice cream cone", "Wings", "Watermelon"] },
  { prompt: "We asked 100 people: name something you find in a kitchen.", answers: ["Refrigerator", "Stove", "Sink", "Microwave", "Toaster", "Dishes", "Knives"] },
  { prompt: "We asked 100 people: name a popular pizza topping.", answers: ["Pepperoni", "Cheese", "Mushrooms", "Sausage", "Onions", "Peppers", "Pineapple"] },
  { prompt: "We asked 100 people: name something people take to the beach.", answers: ["Towel", "Sunscreen", "Umbrella", "Cooler", "Sunglasses", "Beach ball", "Snacks"] },
  { prompt: "We asked 100 people: name an animal you might see at the zoo.", answers: ["Lion", "Elephant", "Monkey", "Giraffe", "Tiger", "Zebra", "Penguin", "Bear"] },
  { prompt: "We asked 100 people: name something you do to relax after work.", answers: ["Watch TV", "Take a nap", "Read a book", "Take a bath", "Go for a walk", "Listen to music", "Have a snack"] },
  { prompt: "We asked 100 people: name a reason you might be late for work.", answers: ["Traffic", "Overslept", "Bad weather", "Lost keys", "Car trouble", "Kids", "Long coffee line"] },
  { prompt: "We asked 100 people: name something in a child's backpack.", answers: ["Books", "Pencils", "Lunch", "Notebook", "Snacks", "Water bottle", "Crayons"] },
  { prompt: "We asked 100 people: name a chore nobody likes to do.", answers: ["Dishes", "Laundry", "Cleaning the bathroom", "Taking out trash", "Vacuuming", "Mowing the lawn", "Ironing"] },
  { prompt: "We asked 100 people: name something you might lose around the house.", answers: ["Keys", "Phone", "Remote", "Glasses", "Socks", "Wallet", "Charger"] },
  { prompt: "We asked 100 people: name a topping you put on ice cream.", answers: ["Sprinkles", "Chocolate syrup", "Whipped cream", "Cherry", "Nuts", "Caramel", "Hot fudge"] },
  { prompt: "We asked 100 people: name something people drink with breakfast.", answers: ["Coffee", "Tea", "Orange juice", "Water", "Milk", "Smoothie", "Hot chocolate"] },
  { prompt: "We asked 100 people: name something you find at a wedding.", answers: ["Bride", "Groom", "Cake", "Flowers", "Music", "Dancing", "Rings"] },
  { prompt: "We asked 100 people: name something people do during Ramadan.", answers: ["Fast", "Pray", "Read Quran", "Break fast", "Give charity", "Visit family", "Prepare food"] },
  { prompt: "We asked 100 people: name something served with rice.", answers: ["Chicken", "Meat", "Fish", "Curry", "Vegetables", "Yogurt", "Beans"] },
  { prompt: "We asked 100 people: name a place people go on vacation.", answers: ["Beach", "Dubai", "Paris", "London", "Mountains", "Resort", "Theme park"] },
  { prompt: "We asked 100 people: name something found in a mall.", answers: ["Shops", "Food court", "Cinema", "Clothes", "Perfume", "Parking", "Escalator"] },
  { prompt: "We asked 100 people: name something people buy before Eid.", answers: ["Clothes", "Sweets", "Gifts", "Perfume", "Chocolate", "Decorations", "Shoes"] },
  { prompt: "We asked 100 people: name a common phone app.", answers: ["WhatsApp", "Instagram", "TikTok", "YouTube", "Snapchat", "Google Maps", "Email"] },
  { prompt: "We asked 100 people: name something you see at an airport.", answers: ["Planes", "Luggage", "Passport", "Security", "Duty free", "Boarding gate", "Trolleys"] },
  { prompt: "We asked 100 people: name a popular dessert.", answers: ["Cake", "Ice cream", "Kunafa", "Chocolate", "Baklava", "Cookies", "Cheesecake"] },
  { prompt: "We asked 100 people: name something you find in a majlis.", answers: ["Sofa", "Coffee", "Tea", "Dates", "Carpet", "Incense", "Tissues"] },
  { prompt: "We asked 100 people: name something people do before guests arrive.", answers: ["Clean", "Cook", "Make coffee", "Prepare sweets", "Set the table", "Light incense", "Tidy up"] },
  { prompt: "We asked 100 people: name a common Eid gift.", answers: ["Money", "Clothes", "Perfume", "Chocolate", "Toys", "Jewelry", "Sweets"] },
  { prompt: "We asked 100 people: name something in a car.", answers: ["Steering wheel", "Seats", "Radio", "Air conditioning", "Seat belt", "Phone charger", "Water bottle"] },
  { prompt: "We asked 100 people: name something people forget at home.", answers: ["Phone", "Keys", "Wallet", "Charger", "Glasses", "ID", "Lunch"] },
  { prompt: "We asked 100 people: name a common school subject.", answers: ["Math", "Science", "English", "Arabic", "History", "Islamic studies", "Art"] },
  { prompt: "We asked 100 people: name something you order at a cafe.", answers: ["Coffee", "Tea", "Cake", "Sandwich", "Juice", "Croissant", "Water"] },
  { prompt: "We asked 100 people: name something people do at a football match.", answers: ["Cheer", "Chant", "Eat snacks", "Wave flags", "Take photos", "Shout", "Celebrate"] },
  { prompt: "We asked 100 people: name something you pack for travel.", answers: ["Passport", "Clothes", "Charger", "Toothbrush", "Money", "Shoes", "Medicine"] },
  { prompt: "We asked 100 people: name a popular social media platform.", answers: ["Instagram", "TikTok", "Snapchat", "YouTube", "X", "Facebook", "WhatsApp"] }
];

// Extra topics for the 'name as many' bonus game.
const NAME_PROMPTS_EXTRA = [
  "Countries in South America", "Pixar movies", "Breakfast cereals", "Disney princesses",
  "Things in a typical fridge", "Famous superheroes", "Breeds of dog", "Ice cream flavors",
  "Board games", "Fruits that are red", "Items of clothing", "Things that have wheels",
  "Musical instruments", "Yellow things", "Card games", "Things you bring camping",
  "Vegetables", "Olympic sports", "Things in a classroom", "Cartoon characters",
  "Things found in space", "Fast food chains", "Things at a birthday party", "Pizza chains",
  "James Bond actors", "Arab countries", "GCC countries", "Middle Eastern capitals",
  "Qatar landmarks", "Things in a majlis", "Ramadan foods", "Eid gifts",
  "Arabic names", "Football World Cup winners", "Premier League clubs",
  "Champions League winners", "Countries with Arabic as an official language",
  "Cities in the Gulf", "Things at a wedding", "Desserts", "Phone apps",
  "Things in an airport", "School subjects", "Board games"
];
