// Curated, direct question-and-answer trivia, calibrated for adults (mid-20s):
// specific and interesting, not childish, not vague. 15 themes, ~30 Qs each.
const REAL_CATEGORIES = {
  "General Knowledge": [
    { q: "What is the chemical symbol for the element gold?", a: "Au", points: 200, type: "text" },
    { q: "Which planet in our solar system is the largest by diameter?", a: "Jupiter", points: 200, type: "text" },
    { q: "What is the capital city of Australia?", a: "Canberra", points: 200, type: "text" },
    { q: "Who painted the ceiling of the Sistine Chapel?", a: "Michelangelo", points: 200, type: "text" },
    { q: "What is the largest ocean on Earth?", a: "The Pacific Ocean", points: 200, type: "text" },
    { q: "How many bones are in the adult human body?", a: "206", points: 200, type: "text" },
    { q: "What is the hardest naturally occurring substance on Earth?", a: "Diamond", points: 400, type: "text" },
    { q: "Which gas makes up roughly 78 percent of Earth's atmosphere?", a: "Nitrogen", points: 400, type: "text" },
    { q: "What is the longest river in the world?", a: "The Nile", points: 400, type: "text" },
    { q: "Who wrote the play Romeo and Juliet?", a: "William Shakespeare", points: 400, type: "text" },
    { q: "What is the currency used in Japan?", a: "The yen", points: 400, type: "text" },
    { q: "Which scientist developed the theory of general relativity?", a: "Albert Einstein", points: 400, type: "text" },
    { q: "What is the smallest country in the world by area?", a: "Vatican City", points: 600, type: "text" },
    { q: "In which organ of the human body is insulin produced?", a: "The pancreas", points: 600, type: "text" },
    { q: "What is the most abundant element in the universe?", a: "Hydrogen", points: 600, type: "text" },
    { q: "Which artist is famous for the painting The Persistence of Memory?", a: "Salvador Dali", points: 600, type: "text" },
    { q: "Approximately how fast does light travel in a vacuum, in kilometers per second?", a: "300,000", points: 600, type: "text" },
    { q: "Which country is home to the ancient city of Petra?", a: "Jordan", points: 600, type: "text" },
    { q: "What is the only metal that is liquid at room temperature?", a: "Mercury", points: 800, type: "text" },
    { q: "Which novel by George Orwell introduced the concept of Big Brother?", a: "1984", points: 800, type: "text" },
    { q: "What is the name of the galaxy that contains our solar system?", a: "The Milky Way", points: 800, type: "text" },
    { q: "Who composed the Ninth Symphony, which includes Ode to Joy?", a: "Ludwig van Beethoven", points: 800, type: "text" },
    { q: "Which organelle is known as the powerhouse of the cell?", a: "The mitochondria", points: 800, type: "text" },
    { q: "Which mountain is the tallest in Africa?", a: "Mount Kilimanjaro", points: 800, type: "text" },
    { q: "What is the atomic number of the element carbon?", a: "6", points: 1000, type: "text" },
    { q: "Which Italian explorer gives his name to the American continents?", a: "Amerigo Vespucci", points: 1000, type: "text" },
    { q: "What is the SI unit of electrical resistance?", a: "The ohm", points: 1000, type: "text" },
    { q: "Which philosopher wrote The Republic, featuring the Allegory of the Cave?", a: "Plato", points: 1000, type: "text" },
    { q: "What is the term for an angle that measures exactly 90 degrees?", a: "A right angle", points: 1000, type: "text" },
    { q: "Which salty, outlet-free body of water borders Jordan and Israel?", a: "The Dead Sea", points: 1000, type: "text" }
  ],
  "Sports": [
    { q: "How many players are on the field for one team in a standard game of basketball?", a: "5", points: 200, type: "text" },
    { q: "In which sport would you perform a slam dunk?", a: "Basketball", points: 200, type: "text" },
    { q: "How often are the Summer Olympic Games held?", a: "Every four years", points: 200, type: "text" },
    { q: "In tennis, what term describes a score of zero?", a: "Love", points: 200, type: "text" },
    { q: "Which sport is associated with Wimbledon?", a: "Tennis", points: 200, type: "text" },
    { q: "In soccer, what color card signals a player's ejection from the match?", a: "Red", points: 200, type: "text" },
    { q: "Which country hosted the first FIFA World Cup, in 1930?", a: "Uruguay", points: 400, type: "text" },
    { q: "In what year did the first WrestleMania take place?", a: "1985", points: 400, type: "text" },
    { q: "How many points is a touchdown worth in American football, before the extra point?", a: "6", points: 400, type: "text" },
    { q: "Which boxer was known as The Greatest and said he could float like a butterfly?", a: "Muhammad Ali", points: 400, type: "text" },
    { q: "In golf, what is the term for one stroke under par on a hole?", a: "A birdie", points: 400, type: "text" },
    { q: "Which country has won the most FIFA World Cup titles?", a: "Brazil", points: 400, type: "text" },
    { q: "How many Grand Slam tournaments make up tennis's annual calendar?", a: "4", points: 600, type: "text" },
    { q: "In what city were the first modern Olympic Games held in 1896?", a: "Athens", points: 600, type: "text" },
    { q: "Which Formula 1 driver shares the record of seven World Championships with Lewis Hamilton?", a: "Michael Schumacher", points: 600, type: "text" },
    { q: "What is the maximum break possible in a single frame of snooker?", a: "147", points: 600, type: "text" },
    { q: "In baseball, how many strikes result in a batter being struck out?", a: "3", points: 600, type: "text" },
    { q: "Which sprinter set the men's 100 meter world record of 9.58 seconds in 2009?", a: "Usain Bolt", points: 600, type: "text" },
    { q: "Which country invented the sport of judo?", a: "Japan", points: 800, type: "text" },
    { q: "In cycling, what color jersey is worn by the overall leader of the Tour de France?", a: "Yellow", points: 800, type: "text" },
    { q: "Which NBA player scored 100 points in a single game in 1962?", a: "Wilt Chamberlain", points: 800, type: "text" },
    { q: "What is the length of a marathon, in miles, to the nearest tenth?", a: "26.2", points: 800, type: "text" },
    { q: "Which country won the very first Rugby World Cup, in 1987?", a: "New Zealand", points: 800, type: "text" },
    { q: "In chess, which piece can move only diagonally?", a: "The bishop", points: 800, type: "text" },
    { q: "Which famous horse race is run each year at Aintree racecourse near Liverpool?", a: "The Grand National", points: 1000, type: "text" },
    { q: "Who is the all-time leading goal scorer in the history of the NHL?", a: "Wayne Gretzky", points: 1000, type: "text" },
    { q: "Which gymnast scored the first perfect 10 in Olympic history, in 1976?", a: "Nadia Comaneci", points: 1000, type: "text" },
    { q: "In what year did Roger Bannister become the first person to run a sub-four-minute mile?", a: "1954", points: 1000, type: "text" },
    { q: "Which American swimmer won eight gold medals at the 2008 Beijing Olympics?", a: "Michael Phelps", points: 1000, type: "text" },
    { q: "Which country originated the martial art and Olympic sport of taekwondo?", a: "South Korea", points: 1000, type: "text" }
  ],
  "History": [
    { q: "In which year did World War II end?", a: "1945", points: 200, type: "text" },
    { q: "Who was the first President of the United States?", a: "George Washington", points: 200, type: "text" },
    { q: "Which ancient civilization built the pyramids at Giza?", a: "The Egyptians", points: 200, type: "text" },
    { q: "Which wall divided a German city until it fell in 1989?", a: "The Berlin Wall", points: 200, type: "text" },
    { q: "Who was the British Prime Minister for most of World War II?", a: "Winston Churchill", points: 200, type: "text" },
    { q: "On which continent was the ancient Roman Empire originally centered?", a: "Europe", points: 200, type: "text" },
    { q: "Which treaty ended World War I in 1919?", a: "The Treaty of Versailles", points: 400, type: "text" },
    { q: "Which explorer is credited with reaching the Americas in 1492?", a: "Christopher Columbus", points: 400, type: "text" },
    { q: "In which year did the Titanic sink on its maiden voyage?", a: "1912", points: 400, type: "text" },
    { q: "Who led the Soviet Union during most of World War II?", a: "Joseph Stalin", points: 400, type: "text" },
    { q: "Which document, signed in 1776, declared American independence?", a: "The Declaration of Independence", points: 400, type: "text" },
    { q: "Which queen ruled England during the Spanish Armada's defeat in 1588?", a: "Elizabeth I", points: 400, type: "text" },
    { q: "Which French military leader was exiled to the island of Elba in 1814?", a: "Napoleon Bonaparte", points: 600, type: "text" },
    { q: "In which year did the French Revolution begin?", a: "1789", points: 600, type: "text" },
    { q: "Which empire was ruled by Genghis Khan in the 13th century?", a: "The Mongol Empire", points: 600, type: "text" },
    { q: "Who was assassinated in Sarajevo in 1914, helping trigger World War I?", a: "Archduke Franz Ferdinand", points: 600, type: "text" },
    { q: "Which ancient wonder stood in the harbor of Alexandria as a lighthouse?", a: "The Lighthouse of Alexandria", points: 600, type: "text" },
    { q: "Which U.S. president issued the Emancipation Proclamation?", a: "Abraham Lincoln", points: 600, type: "text" },
    { q: "Which civilization developed the first known writing system, called cuneiform?", a: "The Sumerians", points: 800, type: "text" },
    { q: "In which year did the Soviet Union officially dissolve?", a: "1991", points: 800, type: "text" },
    { q: "Which English king had six wives during the 16th century?", a: "Henry VIII", points: 800, type: "text" },
    { q: "Which battle in 1815 marked Napoleon's final defeat?", a: "The Battle of Waterloo", points: 800, type: "text" },
    { q: "Which plague killed roughly a third of Europe's population in the 14th century?", a: "The Black Death", points: 800, type: "text" },
    { q: "Who was the first emperor of a unified China?", a: "Qin Shi Huang", points: 800, type: "text" },
    { q: "Which treaty in 1648 ended the Thirty Years' War?", a: "The Peace of Westphalia", points: 1000, type: "text" },
    { q: "Which Macedonian king created one of history's largest empires by 323 BC?", a: "Alexander the Great", points: 1000, type: "text" },
    { q: "Which French fortress-prison was stormed in 1789, an event marked by a national holiday?", a: "The Bastille", points: 1000, type: "text" },
    { q: "Which queen of Egypt was the last active ruler of the Ptolemaic Kingdom?", a: "Cleopatra", points: 1000, type: "text" },
    { q: "Which 1215 English charter limited the power of the monarchy?", a: "The Magna Carta", points: 1000, type: "text" },
    { q: "Which Roman general crossed the Rubicon in 49 BC, sparking civil war?", a: "Julius Caesar", points: 1000, type: "text" }
  ],
  "Geography": [
    { q: "Which African country has three capital cities?", a: "South Africa", points: 200, type: "text" },
    { q: "The Strait of Gibraltar separates Spain from which continent?", a: "Africa", points: 200, type: "text" },
    { q: "Which country is home to the fjords and the city of Bergen?", a: "Norway", points: 200, type: "text" },
    { q: "Mount Kilimanjaro, Africa's highest peak, is located in which country?", a: "Tanzania", points: 200, type: "text" },
    { q: "The Danube River flows into which sea?", a: "The Black Sea", points: 200, type: "text" },
    { q: "Which country's flag is this?", a: "Italy", points: 200, type: "image", emoji: "🇮🇹" },
    { q: "Which is the only country located in all four hemispheres?", a: "Kiribati", points: 400, type: "text" },
    { q: "Which European city sits on both banks of the Bosphorus Strait?", a: "Istanbul", points: 400, type: "text" },
    { q: "The Atacama Desert, the driest non-polar desert, is mostly in which country?", a: "Chile", points: 400, type: "text" },
    { q: "Which country has the longest coastline in the world?", a: "Canada", points: 400, type: "text" },
    { q: "Lake Titicaca lies on the border of Peru and which other country?", a: "Bolivia", points: 400, type: "text" },
    { q: "Which country's flag is this?", a: "Brazil", points: 400, type: "image", emoji: "🇧🇷" },
    { q: "The city of Timbuktu is located in which present-day country?", a: "Mali", points: 600, type: "text" },
    { q: "Which two countries are connected by the Khyber Pass?", a: "Afghanistan and Pakistan", points: 600, type: "text" },
    { q: "What is the smallest country in mainland Africa by area?", a: "The Gambia", points: 600, type: "text" },
    { q: "The Kamchatka Peninsula belongs to which country?", a: "Russia", points: 600, type: "text" },
    { q: "Which African country was formerly known as Abyssinia?", a: "Ethiopia", points: 600, type: "text" },
    { q: "Which country's flag is this?", a: "Sweden", points: 600, type: "image", emoji: "🇸🇪" },
    { q: "Which landlocked country is completely surrounded by South Africa?", a: "Lesotho", points: 800, type: "text" },
    { q: "The Darien Gap, a break in the Pan-American Highway, lies between Panama and which country?", a: "Colombia", points: 800, type: "text" },
    { q: "What is the capital of the Australian state of Tasmania?", a: "Hobart", points: 800, type: "text" },
    { q: "The ancient city of Petra is located in which modern country?", a: "Jordan", points: 800, type: "text" },
    { q: "Which is the only country whose national flag is not rectangular or square?", a: "Nepal", points: 800, type: "text" },
    { q: "Which country's flag is this?", a: "South Korea", points: 800, type: "image", emoji: "🇰🇷" },
    { q: "What is the name of the deepest point in the oceans, in the Mariana Trench?", a: "Challenger Deep", points: 1000, type: "text" },
    { q: "What is the capital city of the West African nation of Burkina Faso?", a: "Ouagadougou", points: 1000, type: "text" },
    { q: "Which Russian exclave borders Poland and Lithuania on the Baltic Sea?", a: "Kaliningrad", points: 1000, type: "text" },
    { q: "What is the highest mountain entirely within Europe, in Russia's Caucasus range?", a: "Mount Elbrus", points: 1000, type: "text" },
    { q: "Which Central Asian country is the world's largest landlocked country?", a: "Kazakhstan", points: 1000, type: "text" },
    { q: "Which country's flag is this?", a: "Turkey", points: 1000, type: "image", emoji: "🇹🇷" }
  ],
  "Movies & TV": [
    { q: "Which 1994 film features the line about life being like a box of chocolates?", a: "Forrest Gump", points: 200, type: "text" },
    { q: "Which animated studio created Toy Story, the first feature-length computer-animated film?", a: "Pixar", points: 200, type: "text" },
    { q: "In the TV series Friends, what is the profession of the character Ross Geller?", a: "Paleontologist", points: 200, type: "text" },
    { q: "Which actor played Jack Dawson in the 1997 film Titanic?", a: "Leonardo DiCaprio", points: 200, type: "text" },
    { q: "What fictional African nation is the setting of the Marvel film Black Panther?", a: "Wakanda", points: 200, type: "text" },
    { q: "Which sitcom is set at the fictional Dunder Mifflin paper company?", a: "The Office", points: 200, type: "text" },
    { q: "Who directed the 1993 film Jurassic Park?", a: "Steven Spielberg", points: 400, type: "text" },
    { q: "In Breaking Bad, what is chemistry teacher Walter White's street alias?", a: "Heisenberg", points: 400, type: "text" },
    { q: "Which 1999 film features a boy who says he sees dead people?", a: "The Sixth Sense", points: 400, type: "text" },
    { q: "What is the name of the kingdom ruled by Elsa in Disney's Frozen?", a: "Arendelle", points: 400, type: "text" },
    { q: "Which actress won an Oscar for playing a boxer in Million Dollar Baby?", a: "Hilary Swank", points: 400, type: "text" },
    { q: "In Game of Thrones, what is the name of the Stark family's ancestral home?", a: "Winterfell", points: 400, type: "text" },
    { q: "Which 1976 boxing film won the Academy Award for Best Picture?", a: "Rocky", points: 600, type: "text" },
    { q: "Who directed the films Pulp Fiction and Kill Bill?", a: "Quentin Tarantino", points: 600, type: "text" },
    { q: "In The Matrix, what color pill does Neo choose to learn the truth?", a: "Red", points: 600, type: "text" },
    { q: "Which actor played the Joker in the 2008 film The Dark Knight?", a: "Heath Ledger", points: 600, type: "text" },
    { q: "What is the name of the spaceship in the 1979 horror film Alien?", a: "The Nostromo", points: 600, type: "text" },
    { q: "Which Japanese director made the 1954 film Seven Samurai?", a: "Akira Kurosawa", points: 600, type: "text" },
    { q: "Which 1941 film directed by Orson Welles is often called the greatest film ever made?", a: "Citizen Kane", points: 800, type: "text" },
    { q: "What is the first name of Sherlock Holmes's brother in the BBC series Sherlock?", a: "Mycroft", points: 800, type: "text" },
    { q: "Which actress played Clarice Starling in The Silence of the Lambs?", a: "Jodie Foster", points: 800, type: "text" },
    { q: "What was the first feature-length film with synchronized dialogue, released in 1927?", a: "The Jazz Singer", points: 800, type: "text" },
    { q: "In Blade Runner, what term is used for the bioengineered humanoids?", a: "Replicants", points: 800, type: "text" },
    { q: "Which 1975 Spielberg film about a great white shark created the summer blockbuster?", a: "Jaws", points: 800, type: "text" },
    { q: "Which 1972 film directed by Francis Ford Coppola follows the Corleone crime family?", a: "The Godfather", points: 1000, type: "text" },
    { q: "Who was the first African American to win the Academy Award for Best Actor?", a: "Sidney Poitier", points: 1000, type: "text" },
    { q: "Which silent film actor was known as The Tramp?", a: "Charlie Chaplin", points: 1000, type: "text" },
    { q: "In which fictional Pennsylvania town is the US version of The Office set?", a: "Scranton", points: 1000, type: "text" },
    { q: "Which 1968 Stanley Kubrick film features a sentient computer named HAL 9000?", a: "2001: A Space Odyssey", points: 1000, type: "text" },
    { q: "Which actress holds the record for the most Academy Award acting nominations?", a: "Meryl Streep", points: 1000, type: "text" }
  ],
  "Music & Songs": [
    { q: "Which Beatles album, recorded in 1969, was the last they made together?", a: "Abbey Road", points: 200, type: "text" },
    { q: "Which artist is known as the King of Pop?", a: "Michael Jackson", points: 200, type: "text" },
    { q: "Which British band released the album A Night at the Opera, featuring Bohemian Rhapsody?", a: "Queen", points: 200, type: "text" },
    { q: "Which American artist titled an album 1989 and later re-recorded her early albums?", a: "Taylor Swift", points: 200, type: "text" },
    { q: "What instrument did jazz legend Louis Armstrong famously play?", a: "The trumpet", points: 200, type: "text" },
    { q: "Which Swedish pop group recorded the hit song Dancing Queen?", a: "ABBA", points: 200, type: "text" },
    { q: "Which composer wrote the Ninth Symphony, which includes the Ode to Joy?", a: "Ludwig van Beethoven", points: 400, type: "text" },
    { q: "Which rapper released the 2000 album The Marshall Mathers LP?", a: "Eminem", points: 400, type: "text" },
    { q: "Which guitarist performed a famous rendition of the Star-Spangled Banner at Woodstock in 1969?", a: "Jimi Hendrix", points: 400, type: "text" },
    { q: "What is the term for the speed or pace of a piece of music?", a: "Tempo", points: 400, type: "text" },
    { q: "Which band's 1973 album The Dark Side of the Moon spent years on the charts?", a: "Pink Floyd", points: 400, type: "text" },
    { q: "Which American singer is known as the Queen of Soul?", a: "Aretha Franklin", points: 400, type: "text" },
    { q: "Which Bob Dylan song from 1965 asks how it feels to be on your own?", a: "Like a Rolling Stone", points: 600, type: "text" },
    { q: "Which Austrian composer wrote the opera The Magic Flute?", a: "Wolfgang Amadeus Mozart", points: 600, type: "text" },
    { q: "Which musical genre originated in Jamaica in the late 1960s and is linked to Bob Marley?", a: "Reggae", points: 600, type: "text" },
    { q: "Which 1971 John Lennon song asks listeners to imagine a world with no countries?", a: "Imagine", points: 600, type: "text" },
    { q: "How many strings does a standard classical guitar have?", a: "Six", points: 600, type: "text" },
    { q: "Which American composer wrote the 1924 orchestral work Rhapsody in Blue?", a: "George Gershwin", points: 600, type: "text" },
    { q: "Which Italian word for loud is used as a dynamic marking in music?", a: "Forte", points: 800, type: "text" },
    { q: "Which Detroit record label was home to The Supremes and Marvin Gaye?", a: "Motown", points: 800, type: "text" },
    { q: "Which English composer wrote The Planets orchestral suite?", a: "Gustav Holst", points: 800, type: "text" },
    { q: "Which jazz trumpeter released the influential 1959 album Kind of Blue?", a: "Miles Davis", points: 800, type: "text" },
    { q: "What is the name for a group of four musicians performing together?", a: "A quartet", points: 800, type: "text" },
    { q: "Which Russian composer wrote The Rite of Spring, which caused a riot at its 1913 premiere?", a: "Igor Stravinsky", points: 800, type: "text" },
    { q: "Which German composer wrote the four-opera cycle The Ring of the Nibelung?", a: "Richard Wagner", points: 1000, type: "text" },
    { q: "What is the highest female singing voice type in classical music?", a: "Soprano", points: 1000, type: "text" },
    { q: "Which jazz saxophonist released the 1965 spiritual album A Love Supreme?", a: "John Coltrane", points: 1000, type: "text" },
    { q: "Which Finnish composer wrote the symphonic poem Finlandia?", a: "Jean Sibelius", points: 1000, type: "text" },
    { q: "Which American singer was known as Lady Day and was a famous jazz vocalist?", a: "Billie Holiday", points: 1000, type: "text" },
    { q: "Which Baroque composer wrote the set of violin concertos known as The Four Seasons?", a: "Antonio Vivaldi", points: 1000, type: "text" }
  ],
  "Science": [
    { q: "What is the most abundant element in the universe by mass?", a: "Hydrogen", points: 200, type: "text" },
    { q: "What force keeps the planets in orbit around the Sun?", a: "Gravity", points: 200, type: "text" },
    { q: "What gas do plants absorb from the air for photosynthesis?", a: "Carbon dioxide", points: 200, type: "text" },
    { q: "What is the chemical symbol for gold?", a: "Au", points: 200, type: "text" },
    { q: "Which organelle is the powerhouse of the cell?", a: "The mitochondria", points: 200, type: "text" },
    { q: "Which planet in our solar system is the largest?", a: "Jupiter", points: 200, type: "text" },
    { q: "Which scientist proposed the three laws of motion?", a: "Isaac Newton", points: 400, type: "text" },
    { q: "What is the pH value of a perfectly neutral solution at 25 degrees Celsius?", a: "7", points: 400, type: "text" },
    { q: "Which subatomic particle carries a negative electric charge?", a: "The electron", points: 400, type: "text" },
    { q: "What is the hardest known naturally occurring material?", a: "Diamond", points: 400, type: "text" },
    { q: "What type of energy is stored in an object due to its position or height?", a: "Potential energy", points: 400, type: "text" },
    { q: "What is the most abundant gas in Earth's atmosphere?", a: "Nitrogen", points: 400, type: "text" },
    { q: "Which scientist developed the theory of general relativity?", a: "Albert Einstein", points: 600, type: "text" },
    { q: "What is the process by which a liquid turns into a gas at its surface, below boiling point?", a: "Evaporation", points: 600, type: "text" },
    { q: "How many chromosomes are in a typical human body cell?", a: "46", points: 600, type: "text" },
    { q: "What element has the atomic number 1?", a: "Hydrogen", points: 600, type: "text" },
    { q: "What is the SI unit of electrical resistance?", a: "The ohm", points: 600, type: "text" },
    { q: "What is the name of the closest galaxy to the Milky Way?", a: "Andromeda", points: 600, type: "text" },
    { q: "What particle was discovered at CERN in 2012, confirming part of the Standard Model?", a: "The Higgs boson", points: 800, type: "text" },
    { q: "What is the term for the temperature at which all molecular motion theoretically stops?", a: "Absolute zero", points: 800, type: "text" },
    { q: "What is the name of the boundary around a black hole beyond which nothing can escape?", a: "The event horizon", points: 800, type: "text" },
    { q: "What metal is liquid at room temperature?", a: "Mercury", points: 800, type: "text" },
    { q: "What is the heaviest naturally occurring element on the periodic table?", a: "Uranium", points: 800, type: "text" },
    { q: "Which gas, with the symbol O, is essential for human respiration?", a: "Oxygen", points: 800, type: "text" },
    { q: "What principle states you cannot simultaneously know a particle's exact position and momentum?", a: "The Heisenberg uncertainty principle", points: 1000, type: "text" },
    { q: "Which German chemist developed the process to synthesize ammonia from nitrogen and hydrogen?", a: "Fritz Haber", points: 1000, type: "text" },
    { q: "What is the term for a collapsed star composed almost entirely of neutrons?", a: "A neutron star", points: 1000, type: "text" },
    { q: "What is the approximate half-life of carbon-14, used in radiocarbon dating?", a: "About 5,730 years", points: 1000, type: "text" },
    { q: "Which organelle in plant cells contains chlorophyll and conducts photosynthesis?", a: "The chloroplast", points: 1000, type: "text" },
    { q: "What is the name of the model describing the universe's origin from a hot, dense state?", a: "The Big Bang theory", points: 1000, type: "text" }
  ],
  "Animals & Nature": [
    { q: "What is the largest land animal on Earth?", a: "The African elephant", points: 200, type: "text" },
    { q: "What is the fastest land animal?", a: "The cheetah", points: 200, type: "text" },
    { q: "What is the only mammal capable of true sustained flight?", a: "The bat", points: 200, type: "text" },
    { q: "What is the largest animal ever known to have lived?", a: "The blue whale", points: 200, type: "text" },
    { q: "What do you call an animal that eats only plants?", a: "A herbivore", points: 200, type: "text" },
    { q: "What is the tallest living animal species?", a: "The giraffe", points: 200, type: "text" },
    { q: "What is the only venomous snake native to Britain?", a: "The adder", points: 400, type: "text" },
    { q: "What is a group of lions called?", a: "A pride", points: 400, type: "text" },
    { q: "What is the largest species of big cat in the world?", a: "The tiger", points: 400, type: "text" },
    { q: "What is the process by which caterpillars transform into butterflies called?", a: "Metamorphosis", points: 400, type: "text" },
    { q: "What bird cannot fly and lays the largest eggs of any living bird?", a: "The ostrich", points: 400, type: "text" },
    { q: "On which single continent do lions and giraffes live in the wild?", a: "Africa", points: 400, type: "text" },
    { q: "What is the largest living species of lizard?", a: "The Komodo dragon", points: 600, type: "text" },
    { q: "What is the only marsupial native to North America?", a: "The opossum", points: 600, type: "text" },
    { q: "What is the scientific term for animals that are active primarily at night?", a: "Nocturnal", points: 600, type: "text" },
    { q: "What is the largest type of penguin?", a: "The emperor penguin", points: 600, type: "text" },
    { q: "What is the only bear species that primarily eats bamboo?", a: "The giant panda", points: 600, type: "text" },
    { q: "What is the largest species of shark, which is a filter feeder?", a: "The whale shark", points: 600, type: "text" },
    { q: "What is the only egg-laying mammal besides the echidna?", a: "The platypus", points: 800, type: "text" },
    { q: "What is the term for the seasonal mass movement of animals from one region to another?", a: "Migration", points: 800, type: "text" },
    { q: "What is the hardest substance produced by the human body?", a: "Tooth enamel", points: 800, type: "text" },
    { q: "Which animal has the longest gestation period of any mammal, nearly two years?", a: "The elephant", points: 800, type: "text" },
    { q: "What is the largest living structure on Earth, off the coast of Australia?", a: "The Great Barrier Reef", points: 800, type: "text" },
    { q: "What is a group of crows commonly called?", a: "A murder", points: 800, type: "text" },
    { q: "What is the world's largest species of rodent, native to South America?", a: "The capybara", points: 1000, type: "text" },
    { q: "What is the scientific term for a relationship in which two species both benefit?", a: "Mutualism", points: 1000, type: "text" },
    { q: "Which amphibian, native to Mexico, is famous for regenerating lost body parts?", a: "The axolotl", points: 1000, type: "text" },
    { q: "What is the only big cat that purrs but cannot roar?", a: "The cheetah", points: 1000, type: "text" },
    { q: "What is the term for animals with a backbone or spinal column?", a: "Vertebrates", points: 1000, type: "text" },
    { q: "What is the largest species of eagle by weight, native to the Philippines?", a: "The Philippine eagle", points: 1000, type: "text" }
  ],
  "Food & Drink": [
    { q: "What fruit is traditionally used to make wine?", a: "Grapes", points: 200, type: "text" },
    { q: "What spice is derived from the dried stigmas of a crocus flower?", a: "Saffron", points: 200, type: "text" },
    { q: "What is the main ingredient in traditional guacamole?", a: "Avocado", points: 200, type: "text" },
    { q: "What type of pastry is used to make profiteroles and eclairs?", a: "Choux pastry", points: 200, type: "text" },
    { q: "What is the primary grain used to make traditional sushi?", a: "Rice", points: 200, type: "text" },
    { q: "What dairy product is churned to make butter?", a: "Cream", points: 200, type: "text" },
    { q: "Which Italian region is the origin of Bolognese sauce?", a: "Emilia-Romagna (Bologna)", points: 400, type: "text" },
    { q: "What is the Japanese term for the savory fifth taste?", a: "Umami", points: 400, type: "text" },
    { q: "What country is the origin of the dish paella?", a: "Spain", points: 400, type: "text" },
    { q: "What bean is the primary ingredient in traditional hummus?", a: "The chickpea", points: 400, type: "text" },
    { q: "What is the French term for cooking food slowly in its own fat?", a: "Confit", points: 400, type: "text" },
    { q: "What alcoholic spirit is the base of a traditional mojito?", a: "Rum", points: 400, type: "text" },
    { q: "What grape variety is one of the most widely planted red wine grapes in the world?", a: "Cabernet Sauvignon", points: 600, type: "text" },
    { q: "Along with gin and Campari, what is the third ingredient in a classic Negroni?", a: "Sweet vermouth", points: 600, type: "text" },
    { q: "What process occurs when yeast converts sugars into alcohol and carbon dioxide?", a: "Fermentation", points: 600, type: "text" },
    { q: "What cheese is traditionally used in an authentic Greek salad?", a: "Feta", points: 600, type: "text" },
    { q: "What is the primary ingredient in the Japanese paste miso?", a: "Soybeans", points: 600, type: "text" },
    { q: "Which French region gives its name to a famous sparkling wine?", a: "Champagne", points: 600, type: "text" },
    { q: "What is the protein in wheat that gives bread its elasticity?", a: "Gluten", points: 800, type: "text" },
    { q: "Which Mexican state is widely considered the birthplace of mole sauce?", a: "Oaxaca", points: 800, type: "text" },
    { q: "What rice variety is essential for making a creamy risotto?", a: "Arborio", points: 800, type: "text" },
    { q: "What spice gives curry powder its characteristic yellow color?", a: "Turmeric", points: 800, type: "text" },
    { q: "What is the Indian term for clarified butter used in cooking?", a: "Ghee", points: 800, type: "text" },
    { q: "What leafy herb is the main flavor in traditional pesto?", a: "Basil", points: 800, type: "text" },
    { q: "What Italian cornmeal dish can be served creamy or set and grilled?", a: "Polenta", points: 1000, type: "text" },
    { q: "What spirit, distilled from the blue agave plant, is the base of a margarita?", a: "Tequila", points: 1000, type: "text" },
    { q: "What Hungarian spice made from dried ground peppers is essential to goulash?", a: "Paprika", points: 1000, type: "text" },
    { q: "What is the Japanese rice wine traditionally served warm or chilled?", a: "Sake", points: 1000, type: "text" },
    { q: "What is the name of the process of aging beef in a cold, controlled environment to deepen flavor?", a: "Dry aging", points: 1000, type: "text" },
    { q: "What Italian dessert's name translates to 'pick me up'?", a: "Tiramisu", points: 1000, type: "text" }
  ],
  "Famous People": [
    { q: "Which physicist developed the theory of general relativity?", a: "Albert Einstein", points: 200, type: "text" },
    { q: "Who was the first President of the United States?", a: "George Washington", points: 200, type: "text" },
    { q: "Which artist painted the ceiling of the Sistine Chapel?", a: "Michelangelo", points: 200, type: "text" },
    { q: "Who wrote the plays Romeo and Juliet and Hamlet?", a: "William Shakespeare", points: 200, type: "text" },
    { q: "Which scientist proposed the theory of evolution by natural selection?", a: "Charles Darwin", points: 200, type: "text" },
    { q: "Who was the British Prime Minister during most of World War II?", a: "Winston Churchill", points: 200, type: "text" },
    { q: "Which Polish-born scientist won Nobel Prizes in both Physics and Chemistry?", a: "Marie Curie", points: 400, type: "text" },
    { q: "Who was the first woman to fly solo across the Atlantic Ocean?", a: "Amelia Earhart", points: 400, type: "text" },
    { q: "Which explorer reached the Americas in 1492 under the Spanish crown?", a: "Christopher Columbus", points: 400, type: "text" },
    { q: "Who composed the Ninth Symphony while almost completely deaf?", a: "Ludwig van Beethoven", points: 400, type: "text" },
    { q: "Which civil rights leader delivered the I Have a Dream speech in 1963?", a: "Martin Luther King Jr.", points: 400, type: "text" },
    { q: "Who was the Egyptian queen who allied with both Julius Caesar and Mark Antony?", a: "Cleopatra", points: 400, type: "text" },
    { q: "Which mathematician helped found computer science and broke the Enigma code?", a: "Alan Turing", points: 600, type: "text" },
    { q: "Which Austrian neurologist founded psychoanalysis?", a: "Sigmund Freud", points: 600, type: "text" },
    { q: "Which medieval Venetian traveler wrote of his journeys to the court of Kublai Khan?", a: "Marco Polo", points: 600, type: "text" },
    { q: "Who led India to independence through nonviolent civil disobedience?", a: "Mahatma Gandhi", points: 600, type: "text" },
    { q: "Which artist painted both the Mona Lisa and The Last Supper?", a: "Leonardo da Vinci", points: 600, type: "text" },
    { q: "Who wrote the novel One Hundred Years of Solitude?", a: "Gabriel Garcia Marquez", points: 600, type: "text" },
    { q: "Which Danish physicist developed a model of the atom with electrons in fixed orbits?", a: "Niels Bohr", points: 800, type: "text" },
    { q: "Which Roman emperor legalized Christianity with the Edict of Milan?", a: "Constantine the Great", points: 800, type: "text" },
    { q: "Who was the first female Prime Minister of the United Kingdom?", a: "Margaret Thatcher", points: 800, type: "text" },
    { q: "Which astronomer was tried by the Inquisition for supporting heliocentrism?", a: "Galileo Galilei", points: 800, type: "text" },
    { q: "Which Serbian-American inventor pioneered alternating current electrical systems?", a: "Nikola Tesla", points: 800, type: "text" },
    { q: "Which nurse, known as the Lady with the Lamp, founded modern nursing?", a: "Florence Nightingale", points: 800, type: "text" },
    { q: "Which Macedonian king, tutored by Aristotle, conquered the Persian Empire?", a: "Alexander the Great", points: 1000, type: "text" },
    { q: "Which scientist discovered penicillin in 1928?", a: "Alexander Fleming", points: 1000, type: "text" },
    { q: "Who was the first Holy Roman Emperor, crowned in the year 800?", a: "Charlemagne", points: 1000, type: "text" },
    { q: "Which economist wrote The Wealth of Nations in 1776?", a: "Adam Smith", points: 1000, type: "text" },
    { q: "Who formulated the laws of planetary motion in the early 17th century?", a: "Johannes Kepler", points: 1000, type: "text" },
    { q: "Which English mathematician and physicist wrote the Principia Mathematica?", a: "Isaac Newton", points: 1000, type: "text" }
  ],
  "Technology & Inventions": [
    { q: "In which year was the first iPhone released?", a: "2007", points: 200, type: "text" },
    { q: "Who is widely credited with inventing the telephone?", a: "Alexander Graham Bell", points: 200, type: "text" },
    { q: "What does the abbreviation WWW stand for?", a: "World Wide Web", points: 200, type: "text" },
    { q: "Which company developed the Windows operating system?", a: "Microsoft", points: 200, type: "text" },
    { q: "What invention by Gutenberg revolutionized the spread of books?", a: "The printing press", points: 200, type: "text" },
    { q: "What does the acronym USB stand for?", a: "Universal Serial Bus", points: 200, type: "text" },
    { q: "Who is credited with inventing the practical incandescent light bulb?", a: "Thomas Edison", points: 400, type: "text" },
    { q: "Which programming language was created by Guido van Rossum?", a: "Python", points: 400, type: "text" },
    { q: "What does the acronym GPS stand for?", a: "Global Positioning System", points: 400, type: "text" },
    { q: "Which company manufactured the first mass-produced automobile, the Model T?", a: "Ford", points: 400, type: "text" },
    { q: "What does the acronym HTML stand for?", a: "HyperText Markup Language", points: 400, type: "text" },
    { q: "Who is credited with inventing the World Wide Web in 1989?", a: "Tim Berners-Lee", points: 400, type: "text" },
    { q: "Which two brothers achieved the first powered airplane flight in 1903?", a: "The Wright Brothers", points: 600, type: "text" },
    { q: "What was the name of the first general-purpose electronic computer, completed in 1945?", a: "ENIAC", points: 600, type: "text" },
    { q: "Which Swedish chemist invented dynamite?", a: "Alfred Nobel", points: 600, type: "text" },
    { q: "What does the acronym CPU stand for?", a: "Central Processing Unit", points: 600, type: "text" },
    { q: "Which company released the first popular graphical web browser, Navigator?", a: "Netscape", points: 600, type: "text" },
    { q: "What does the acronym HTTP stand for?", a: "HyperText Transfer Protocol", points: 600, type: "text" },
    { q: "Who patented the first practical telegraph and developed a famous code?", a: "Samuel Morse", points: 800, type: "text" },
    { q: "Which two Steves co-founded Apple along with Ronald Wayne?", a: "Steve Jobs and Steve Wozniak", points: 800, type: "text" },
    { q: "What was the name of the first artificial Earth satellite, launched in 1957?", a: "Sputnik 1", points: 800, type: "text" },
    { q: "Which Scottish engineer's steam-engine improvements helped drive the Industrial Revolution?", a: "James Watt", points: 800, type: "text" },
    { q: "What was the name of the network that was the precursor to the modern internet?", a: "ARPANET", points: 800, type: "text" },
    { q: "Which inventor created the first practical photographic process, the daguerreotype?", a: "Louis Daguerre", points: 800, type: "text" },
    { q: "Which Hungarian-American mathematician is linked to the basic architecture of modern computers?", a: "John von Neumann", points: 1000, type: "text" },
    { q: "What was the name of IBM's chess computer that beat Garry Kasparov in 1997?", a: "Deep Blue", points: 1000, type: "text" },
    { q: "Which English mathematician designed the Analytical Engine in the 19th century?", a: "Charles Babbage", points: 1000, type: "text" },
    { q: "Who is regarded as the first computer programmer for her work on the Analytical Engine?", a: "Ada Lovelace", points: 1000, type: "text" },
    { q: "In what year was the first message sent over ARPANET?", a: "1969", points: 1000, type: "text" },
    { q: "Which company's engineers invented the transistor at Bell Labs in 1947?", a: "Bell Labs (AT&T)", points: 1000, type: "text" }
  ],
  "Space & Astronomy": [
    { q: "Which planet is closest to the Sun?", a: "Mercury", points: 200, type: "text" },
    { q: "What is the name of Earth's only natural satellite?", a: "The Moon", points: 200, type: "text" },
    { q: "Which planet is known as the Red Planet?", a: "Mars", points: 200, type: "text" },
    { q: "What star is at the center of our solar system?", a: "The Sun", points: 200, type: "text" },
    { q: "Which is the largest planet in our solar system?", a: "Jupiter", points: 200, type: "text" },
    { q: "What galaxy contains our solar system?", a: "The Milky Way", points: 200, type: "text" },
    { q: "Who was the first human to walk on the Moon?", a: "Neil Armstrong", points: 400, type: "text" },
    { q: "Which planet is famous for its prominent ring system?", a: "Saturn", points: 400, type: "text" },
    { q: "What was the name of NASA's program that landed humans on the Moon?", a: "Apollo", points: 400, type: "text" },
    { q: "Which was the first space probe to leave the solar system?", a: "Voyager 1", points: 400, type: "text" },
    { q: "Who was the first human to travel into space?", a: "Yuri Gagarin", points: 400, type: "text" },
    { q: "Which planet is the hottest in our solar system?", a: "Venus", points: 400, type: "text" },
    { q: "What is the name of the boundary around a black hole beyond which nothing can escape?", a: "The event horizon", points: 600, type: "text" },
    { q: "Which space telescope, launched in 1990, has produced famous deep-field images?", a: "The Hubble Space Telescope", points: 600, type: "text" },
    { q: "What term describes a star that suddenly brightens dramatically then fades?", a: "A supernova", points: 600, type: "text" },
    { q: "Which planet has the largest volcano in the solar system, Olympus Mons?", a: "Mars", points: 600, type: "text" },
    { q: "What is the closest star system to our Sun?", a: "Alpha Centauri", points: 600, type: "text" },
    { q: "Who was the first woman in space?", a: "Valentina Tereshkova", points: 600, type: "text" },
    { q: "What is the name of the largest moon of Jupiter?", a: "Ganymede", points: 800, type: "text" },
    { q: "Which astronomer discovered that the universe is expanding?", a: "Edwin Hubble", points: 800, type: "text" },
    { q: "What is the term for the leftover radiation from the Big Bang?", a: "The cosmic microwave background", points: 800, type: "text" },
    { q: "Which dwarf planet was reclassified from full planet status in 2006?", a: "Pluto", points: 800, type: "text" },
    { q: "Which moon of Saturn is the only one known to have a thick atmosphere?", a: "Titan", points: 800, type: "text" },
    { q: "What is the approximate age of the universe in billions of years?", a: "13.8 billion years", points: 800, type: "text" },
    { q: "What is the term for the point in an orbit where a body is closest to the Sun?", a: "Perihelion", points: 1000, type: "text" },
    { q: "Which spacecraft carried Armstrong and Aldrin to the first Moon landing in 1969?", a: "Apollo 11", points: 1000, type: "text" },
    { q: "What is the name of the boundary marking the limit of the Sun's solar wind?", a: "The heliopause", points: 1000, type: "text" },
    { q: "What type of star is the Sun classified as on the main sequence?", a: "A yellow dwarf", points: 1000, type: "text" },
    { q: "What is the name of the large cloud of icy bodies theorized to surround the solar system?", a: "The Oort Cloud", points: 1000, type: "text" },
    { q: "Which planet has the fastest winds in the solar system and a deep blue color?", a: "Neptune", points: 1000, type: "text" }
  ],
  "Art & Literature": [
    { q: "Which Russian author wrote the novel War and Peace?", a: "Leo Tolstoy", points: 200, type: "text" },
    { q: "Who painted the ceiling of the Sistine Chapel?", a: "Michelangelo", points: 200, type: "text" },
    { q: "Which English playwright wrote the tragedy Hamlet?", a: "William Shakespeare", points: 200, type: "text" },
    { q: "Who wrote the epic poem about Odysseus's journey home, the Odyssey?", a: "Homer", points: 200, type: "text" },
    { q: "Which artist painted the Mona Lisa?", a: "Leonardo da Vinci", points: 200, type: "text" },
    { q: "Who wrote the dystopian novel Nineteen Eighty-Four?", a: "George Orwell", points: 200, type: "text" },
    { q: "Which Spanish painter co-founded the Cubist movement?", a: "Pablo Picasso", points: 400, type: "text" },
    { q: "Who wrote the novel Pride and Prejudice?", a: "Jane Austen", points: 400, type: "text" },
    { q: "Which Dutch painter created The Starry Night?", a: "Vincent van Gogh", points: 400, type: "text" },
    { q: "Who wrote the play A Doll's House?", a: "Henrik Ibsen", points: 400, type: "text" },
    { q: "Which American author wrote The Great Gatsby?", a: "F. Scott Fitzgerald", points: 400, type: "text" },
    { q: "Who created the detective character Sherlock Holmes?", a: "Arthur Conan Doyle", points: 400, type: "text" },
    { q: "Which Russian author wrote Crime and Punishment?", a: "Fyodor Dostoevsky", points: 600, type: "text" },
    { q: "Which Norwegian painter created The Scream?", a: "Edvard Munch", points: 600, type: "text" },
    { q: "Who wrote the novel Things Fall Apart?", a: "Chinua Achebe", points: 600, type: "text" },
    { q: "Which Italian poet wrote The Divine Comedy?", a: "Dante Alighieri", points: 600, type: "text" },
    { q: "Which English author wrote the novel Jane Eyre?", a: "Charlotte Bronte", points: 600, type: "text" },
    { q: "Who wrote the play Waiting for Godot?", a: "Samuel Beckett", points: 600, type: "text" },
    { q: "Which French author wrote the novel In Search of Lost Time?", a: "Marcel Proust", points: 800, type: "text" },
    { q: "Which French Impressionist painted the Water Lilies series?", a: "Claude Monet", points: 800, type: "text" },
    { q: "Which Irish author wrote the modernist novel Ulysses?", a: "James Joyce", points: 800, type: "text" },
    { q: "Which Mexican artist is known for self-portraits like The Two Fridas?", a: "Frida Kahlo", points: 800, type: "text" },
    { q: "Who wrote the novel Beloved, set after the American Civil War?", a: "Toni Morrison", points: 800, type: "text" },
    { q: "Which German author wrote the play Faust?", a: "Johann Wolfgang von Goethe", points: 800, type: "text" },
    { q: "Which Austrian painter created the gold-leaf work The Kiss?", a: "Gustav Klimt", points: 1000, type: "text" },
    { q: "Which Dutch painter created Girl with a Pearl Earring?", a: "Johannes Vermeer", points: 1000, type: "text" },
    { q: "Which Portuguese author wrote the novel Blindness?", a: "Jose Saramago", points: 1000, type: "text" },
    { q: "Which Spanish painter created the anti-war mural Guernica?", a: "Pablo Picasso", points: 1000, type: "text" },
    { q: "Who wrote the novel Invisible Man, published in 1952?", a: "Ralph Ellison", points: 1000, type: "text" },
    { q: "Which Colombian author won the 1982 Nobel Prize in Literature?", a: "Gabriel Garcia Marquez", points: 1000, type: "text" }
  ],
  "Pop Culture": [
    { q: "Which video game franchise features a plumber named Mario?", a: "Super Mario", points: 200, type: "text" },
    { q: "Which pop singer released the album Thriller in 1982?", a: "Michael Jackson", points: 200, type: "text" },
    { q: "Which film series features a wizard boy named Harry Potter?", a: "Harry Potter", points: 200, type: "text" },
    { q: "Which British band recorded the album Abbey Road?", a: "The Beatles", points: 200, type: "text" },
    { q: "Which animated studio created the films Toy Story and Finding Nemo?", a: "Pixar", points: 200, type: "text" },
    { q: "Which superhero is known by the alter ego Bruce Wayne?", a: "Batman", points: 200, type: "text" },
    { q: "Which director made the films Jaws and Jurassic Park?", a: "Steven Spielberg", points: 400, type: "text" },
    { q: "Which sitcom features characters named Ross, Rachel, and Monica?", a: "Friends", points: 400, type: "text" },
    { q: "Which video game franchise features creatures called Pikachu and Charizard?", a: "Pokemon", points: 400, type: "text" },
    { q: "Which singer is known as the Queen of Pop and released the song Like a Prayer?", a: "Madonna", points: 400, type: "text" },
    { q: "Which 1997 film won Best Picture and depicts the sinking of a famous ship?", a: "Titanic", points: 400, type: "text" },
    { q: "Which Swedish pop group recorded the song Dancing Queen?", a: "ABBA", points: 400, type: "text" },
    { q: "Which director made the films Pulp Fiction and Kill Bill?", a: "Quentin Tarantino", points: 600, type: "text" },
    { q: "Which reggae musician released the album Exodus?", a: "Bob Marley", points: 600, type: "text" },
    { q: "Which fantasy TV series is based on novels by George R. R. Martin?", a: "Game of Thrones", points: 600, type: "text" },
    { q: "Which actor played the boxer Rocky Balboa?", a: "Sylvester Stallone", points: 600, type: "text" },
    { q: "Which Japanese company created the video game franchise The Legend of Zelda?", a: "Nintendo", points: 600, type: "text" },
    { q: "Which band recorded the song Bohemian Rhapsody?", a: "Queen", points: 600, type: "text" },
    { q: "Which director made the films Vertigo and Psycho?", a: "Alfred Hitchcock", points: 800, type: "text" },
    { q: "Which animated TV family lives in the town of Springfield?", a: "The Simpsons", points: 800, type: "text" },
    { q: "Which English singer released the album 21, featuring Rolling in the Deep?", a: "Adele", points: 800, type: "text" },
    { q: "Which actor played the lead role in the 1994 film Forrest Gump?", a: "Tom Hanks", points: 800, type: "text" },
    { q: "Which studio created the open-world video game series Grand Theft Auto?", a: "Rockstar Games", points: 800, type: "text" },
    { q: "Which director made the films Goodfellas and Taxi Driver?", a: "Martin Scorsese", points: 800, type: "text" },
    { q: "Which Italian composer wrote the score for The Good, the Bad and the Ugly?", a: "Ennio Morricone", points: 1000, type: "text" },
    { q: "Which director made the films Seven Samurai and Rashomon?", a: "Akira Kurosawa", points: 1000, type: "text" },
    { q: "Which British rock band released the concept album The Dark Side of the Moon?", a: "Pink Floyd", points: 1000, type: "text" },
    { q: "Which 2009 sandbox video game by Mojang popularized the survival genre?", a: "Minecraft", points: 1000, type: "text" },
    { q: "Which soul singer was known as the Queen of Soul and recorded Respect?", a: "Aretha Franklin", points: 1000, type: "text" },
    { q: "Which film franchise features a spy with the code number 007?", a: "James Bond", points: 1000, type: "text" }
  ],
  "Famous Landmarks": [
    { q: "In which city is the Eiffel Tower located?", a: "Paris", points: 200, type: "text" },
    { q: "The Great Pyramid of Giza is located in which country?", a: "Egypt", points: 200, type: "text" },
    { q: "In which country is the Colosseum located?", a: "Italy", points: 200, type: "text" },
    { q: "The Statue of Liberty stands in the harbor of which US city?", a: "New York City", points: 200, type: "text" },
    { q: "The Great Wall is a famous landmark in which country?", a: "China", points: 200, type: "text" },
    { q: "In which country is the Taj Mahal located?", a: "India", points: 200, type: "text" },
    { q: "The ancient citadel of the Acropolis overlooks which European capital?", a: "Athens", points: 400, type: "text" },
    { q: "Machu Picchu, the ancient Incan site, is located in which country?", a: "Peru", points: 400, type: "text" },
    { q: "The Sydney Opera House is located in which country?", a: "Australia", points: 400, type: "text" },
    { q: "Christ the Redeemer overlooks which Brazilian city?", a: "Rio de Janeiro", points: 400, type: "text" },
    { q: "The Brandenburg Gate is a famous landmark in which city?", a: "Berlin", points: 400, type: "text" },
    { q: "The leaning bell tower famous for tilting is in which Italian city?", a: "Pisa", points: 400, type: "text" },
    { q: "The ancient city of Petra is located in which modern country?", a: "Jordan", points: 600, type: "text" },
    { q: "The temple complex of Angkor Wat is located in which country?", a: "Cambodia", points: 600, type: "text" },
    { q: "The Alhambra palace and fortress is located in which Spanish city?", a: "Granada", points: 600, type: "text" },
    { q: "The Hagia Sophia is a famous landmark in which city?", a: "Istanbul", points: 600, type: "text" },
    { q: "Mount Rushmore, with its carved presidential faces, is in which US state?", a: "South Dakota", points: 600, type: "text" },
    { q: "The prehistoric monument Stonehenge is located in which country?", a: "England", points: 600, type: "text" },
    { q: "The Chichen Itza pyramid, known as El Castillo, is located in which country?", a: "Mexico", points: 800, type: "text" },
    { q: "The Burj Khalifa, the world's tallest building, is located in which city?", a: "Dubai", points: 800, type: "text" },
    { q: "The Sagrada Familia basilica, designed by Antoni Gaudi, is in which city?", a: "Barcelona", points: 800, type: "text" },
    { q: "The ancient temple of Borobudur is located on which Indonesian island?", a: "Java", points: 800, type: "text" },
    { q: "The Golden Gate Bridge spans the entrance to the bay of which US city?", a: "San Francisco", points: 800, type: "text" },
    { q: "The rock-hewn churches of Lalibela are located in which African country?", a: "Ethiopia", points: 800, type: "text" },
    { q: "The Potala Palace, former residence of the Dalai Lama, is located in which city?", a: "Lhasa", points: 1000, type: "text" },
    { q: "The Meteora monasteries are perched on rock pillars in which country?", a: "Greece", points: 1000, type: "text" },
    { q: "The ancient city of Timbuktu, a center of learning, is located in which country?", a: "Mali", points: 1000, type: "text" },
    { q: "The Terracotta Army was discovered near which Chinese city?", a: "Xi'an", points: 1000, type: "text" },
    { q: "The temple of Abu Simbel, relocated to escape flooding, is located in which country?", a: "Egypt", points: 1000, type: "text" },
    { q: "The medieval Christian monastery of Mont-Saint-Michel sits on a tidal island in which country?", a: "France", points: 1000, type: "text" }
  ]
};
