// Curated, direct Q&A trivia for adults (mid-20s), with a strict difficulty
// ladder per category: $200 = easy, scaling to $1000 = expert (like the flags).
// 8 questions per point tier for variety, so boards rarely repeat between games.
const REAL_CATEGORIES = {
  "General Knowledge": [
    { q: "What is the closest planet to the Sun?", a: "Mercury", points: 200, type: "text" },
    { q: "How many continents are there on Earth?", a: "Seven", points: 200, type: "text" },
    { q: "What is the largest mammal in the world?", a: "Blue whale", points: 200, type: "text" },
    { q: "What gas do humans need to breathe to survive?", a: "Oxygen", points: 200, type: "text" },
    { q: "What is the capital of France?", a: "Paris", points: 200, type: "text" },
    { q: "What is the capital of Italy?", a: "Rome", points: 200, type: "text" },
    { q: "What is the freezing point of water in degrees Celsius?", a: "0", points: 200, type: "text" },
    { q: "Which fairy tale character left behind a glass slipper?", a: "Cinderella", points: 200, type: "text" },
    { q: "What is the chemical symbol for gold?", a: "Au", points: 400, type: "text" },
    { q: "What is the tallest mountain above sea level on Earth?", a: "Mount Everest", points: 400, type: "text" },
    { q: "Who painted the Mona Lisa?", a: "Leonardo da Vinci", points: 400, type: "text" },
    { q: "What is the largest ocean on Earth?", a: "Pacific Ocean", points: 400, type: "text" },
    { q: "How many bones does an adult human body have?", a: "206", points: 400, type: "text" },
    { q: "What is the currency used in Japan?", a: "Yen", points: 400, type: "text" },
    { q: "Which planet is known as the Red Planet?", a: "Mars", points: 400, type: "text" },
    { q: "What is the hardest known natural material?", a: "Diamond", points: 400, type: "text" },
    { q: "What is the chemical formula for table salt?", a: "NaCl", points: 600, type: "text" },
    { q: "Who developed the theory of general relativity?", a: "Albert Einstein", points: 600, type: "text" },
    { q: "What is the smallest country in the world by area?", a: "Vatican City", points: 600, type: "text" },
    { q: "What is the powerhouse of the cell?", a: "Mitochondria", points: 600, type: "text" },
    { q: "Which language has the most native speakers in the world?", a: "Mandarin Chinese", points: 600, type: "text" },
    { q: "Who wrote the play Romeo and Juliet?", a: "William Shakespeare", points: 600, type: "text" },
    { q: "What is the longest river in the world?", a: "Nile", points: 600, type: "text" },
    { q: "What is the largest internal organ in the human body?", a: "Liver", points: 600, type: "text" },
    { q: "What is the most abundant gas in Earth's atmosphere?", a: "Nitrogen", points: 800, type: "text" },
    { q: "Who is credited with discovering penicillin?", a: "Alexander Fleming", points: 800, type: "text" },
    { q: "What is the atomic number of carbon?", a: "6", points: 800, type: "text" },
    { q: "What is the capital of Australia?", a: "Canberra", points: 800, type: "text" },
    { q: "Which Italian astronomer improved the telescope and supported heliocentrism?", a: "Galileo Galilei", points: 800, type: "text" },
    { q: "What is the largest moon of Saturn?", a: "Titan", points: 800, type: "text" },
    { q: "Who composed the Ninth Symphony, also known as the Choral Symphony?", a: "Ludwig van Beethoven", points: 800, type: "text" },
    { q: "What is the SI unit of electrical resistance?", a: "Ohm", points: 800, type: "text" },
    { q: "What is the only metal that is liquid at room temperature?", a: "Mercury", points: 1000, type: "text" },
    { q: "Who proposed the three laws of planetary motion?", a: "Johannes Kepler", points: 1000, type: "text" },
    { q: "What is the rarest naturally occurring element in Earth's crust?", a: "Astatine", points: 1000, type: "text" },
    { q: "What protein carries oxygen in red blood cells?", a: "Hemoglobin", points: 1000, type: "text" },
    { q: "Which Swiss mathematician is the constant e, roughly 2.718, named after?", a: "Leonhard Euler", points: 1000, type: "text" },
    { q: "What is the deepest point in the world's oceans called?", a: "Challenger Deep", points: 1000, type: "text" },
    { q: "What is the largest hot desert in the world?", a: "The Sahara", points: 1000, type: "text" },
    { q: "Which scientist formulated the three laws of motion?", a: "Isaac Newton", points: 1000, type: "text" }
  ],
  "Sports": [
    { q: "How many players from one team are on a soccer field at one time?", a: "Eleven", points: 200, type: "text" },
    { q: "Which Portuguese superstar has starred for Real Madrid and Manchester United?", a: "Cristiano Ronaldo", points: 200, type: "text" },
    { q: "In which sport would you perform a slam dunk?", a: "Basketball", points: 200, type: "text" },
    { q: "How many points is a touchdown worth in American football?", a: "Six", points: 200, type: "text" },
    { q: "What sport is played at Wimbledon?", a: "Tennis", points: 200, type: "text" },
    { q: "How often are the Summer Olympic Games held?", a: "Every four years", points: 200, type: "text" },
    { q: "In which sport is the term 'home run' used?", a: "Baseball", points: 200, type: "text" },
    { q: "What color jersey is worn by the overall leader of the Tour de France?", a: "Yellow", points: 200, type: "text" },
    { q: "Which Argentine player captained his nation to the 2022 FIFA World Cup title?", a: "Lionel Messi", points: 400, type: "text" },
    { q: "How many rings are on the Olympic flag?", a: "Five", points: 400, type: "text" },
    { q: "In golf, what is the term for one stroke under par on a hole?", a: "Birdie", points: 400, type: "text" },
    { q: "Which country has won the most FIFA World Cup titles?", a: "Brazil", points: 400, type: "text" },
    { q: "How long is a marathon, in kilometers, rounded to the nearest whole number?", a: "42", points: 400, type: "text" },
    { q: "In which sport is the Stanley Cup awarded?", a: "Ice hockey", points: 400, type: "text" },
    { q: "Which tennis Grand Slam is played on clay courts?", a: "French Open", points: 400, type: "text" },
    { q: "Which NBA player is nicknamed 'The Black Mamba'?", a: "Kobe Bryant", points: 400, type: "text" },
    { q: "Which swimmer holds the record for the most Olympic gold medals?", a: "Michael Phelps", points: 600, type: "text" },
    { q: "In Formula 1, what flag is waved to signal the end of a race?", a: "Checkered flag", points: 600, type: "text" },
    { q: "How many points is the bullseye worth in a standard game of darts?", a: "50", points: 600, type: "text" },
    { q: "Which country hosted the 2016 Summer Olympics?", a: "Brazil", points: 600, type: "text" },
    { q: "In boxing, how many rounds are in a standard professional championship fight?", a: "Twelve", points: 600, type: "text" },
    { q: "Which German driver won seven Formula 1 World Championships before Lewis Hamilton matched it?", a: "Michael Schumacher", points: 600, type: "text" },
    { q: "In which year did the first WrestleMania take place?", a: "1985", points: 600, type: "text" },
    { q: "Which country hosted the first FIFA World Cup, in 1930?", a: "Uruguay", points: 600, type: "text" },
    { q: "Who held the men's 100 meters world record set in 2009 at 9.58 seconds?", a: "Usain Bolt", points: 800, type: "text" },
    { q: "In rugby union, how many points is a try worth?", a: "Five", points: 800, type: "text" },
    { q: "Who became the NBA's all-time leading regular-season scorer, surpassing Kareem Abdul-Jabbar?", a: "LeBron James", points: 800, type: "text" },
    { q: "In which year were the first modern Olympic Games held in Athens?", a: "1896", points: 800, type: "text" },
    { q: "What is the maximum break in a single frame of snooker?", a: "147", points: 800, type: "text" },
    { q: "Which country won the first ever Rugby World Cup in 1987?", a: "New Zealand", points: 800, type: "text" },
    { q: "In baseball, what term describes a pitcher retiring all 27 batters faced?", a: "Perfect game", points: 800, type: "text" },
    { q: "Which famous horse race is run each year at Aintree near Liverpool?", a: "The Grand National", points: 800, type: "text" },
    { q: "Who scored the 'Hand of God' goal at the 1986 FIFA World Cup?", a: "Diego Maradona", points: 1000, type: "text" },
    { q: "In tennis, who completed the calendar-year Grand Slam in men's singles in 1969?", a: "Rod Laver", points: 1000, type: "text" },
    { q: "Which country won the inaugural Cricket World Cup in 1975?", a: "West Indies", points: 1000, type: "text" },
    { q: "What is the length of an Olympic swimming pool, in meters?", a: "50", points: 1000, type: "text" },
    { q: "Who was the first gymnast to score a perfect 10 at the Olympic Games?", a: "Nadia Comaneci", points: 1000, type: "text" },
    { q: "Which driver won the very first Formula 1 World Championship in 1950?", a: "Giuseppe Farina", points: 1000, type: "text" },
    { q: "In what year did Roger Bannister run the first sub-four-minute mile?", a: "1954", points: 1000, type: "text" },
    { q: "Which country has won the most Olympic gold medals in history?", a: "The United States", points: 1000, type: "text" }
  ],
  "History": [
    { q: "Who was the first President of the United States?", a: "George Washington", points: 200, type: "text" },
    { q: "On which continent were the ancient pyramids of Giza built?", a: "Africa", points: 200, type: "text" },
    { q: "In which country did the ancient Olympic Games originate?", a: "Greece", points: 200, type: "text" },
    { q: "What ship sank in 1912 after hitting an iceberg?", a: "Titanic", points: 200, type: "text" },
    { q: "Who was the leader of Nazi Germany during World War II?", a: "Adolf Hitler", points: 200, type: "text" },
    { q: "What wall divided a German city until 1989?", a: "Berlin Wall", points: 200, type: "text" },
    { q: "Which ancient civilization built the Colosseum?", a: "Roman", points: 200, type: "text" },
    { q: "Who is credited with sailing to the Americas in 1492?", a: "Christopher Columbus", points: 200, type: "text" },
    { q: "In which year did World War II end?", a: "1945", points: 400, type: "text" },
    { q: "Which Egyptian queen was known for her relationships with Julius Caesar and Mark Antony?", a: "Cleopatra", points: 400, type: "text" },
    { q: "What document begins with the words 'We the People'?", a: "The U.S. Constitution", points: 400, type: "text" },
    { q: "Who delivered the 'I Have a Dream' speech in 1963?", a: "Martin Luther King Jr.", points: 400, type: "text" },
    { q: "Which empire was ruled by Genghis Khan?", a: "Mongol Empire", points: 400, type: "text" },
    { q: "In which city was President John F. Kennedy assassinated?", a: "Dallas", points: 400, type: "text" },
    { q: "What was the name of the first artificial satellite, launched in 1957?", a: "Sputnik", points: 400, type: "text" },
    { q: "Which French military leader was exiled to the island of Elba?", a: "Napoleon Bonaparte", points: 400, type: "text" },
    { q: "Who was the British Prime Minister for most of World War II?", a: "Winston Churchill", points: 600, type: "text" },
    { q: "In which year did the French Revolution begin?", a: "1789", points: 600, type: "text" },
    { q: "Which ancient wonder was located in the harbor of Alexandria?", a: "Lighthouse of Alexandria", points: 600, type: "text" },
    { q: "Which treaty ended World War I in 1919?", a: "Treaty of Versailles", points: 600, type: "text" },
    { q: "Who was the first woman to win a Nobel Prize?", a: "Marie Curie", points: 600, type: "text" },
    { q: "Which civilization developed the cuneiform writing system?", a: "Sumerians", points: 600, type: "text" },
    { q: "In what year did the United States declare its independence?", a: "1776", points: 600, type: "text" },
    { q: "Which Russian royal family was executed in 1918?", a: "The Romanovs", points: 600, type: "text" },
    { q: "Which Macedonian king built one of the ancient world's largest empires by his early thirties?", a: "Alexander the Great", points: 800, type: "text" },
    { q: "What was the European period of artistic rebirth beginning in the 14th century called?", a: "The Renaissance", points: 800, type: "text" },
    { q: "Which 1066 battle led to the Norman conquest of England?", a: "Battle of Hastings", points: 800, type: "text" },
    { q: "Who was the first Emperor of a unified China?", a: "Qin Shi Huang", points: 800, type: "text" },
    { q: "What plague killed roughly a third of Europe's population in the 14th century?", a: "The Black Death", points: 800, type: "text" },
    { q: "Which American general accepted the Confederate surrender at Appomattox in 1865?", a: "Ulysses S. Grant", points: 800, type: "text" },
    { q: "Which Byzantine emperor codified Roman law in the 6th century?", a: "Justinian I", points: 800, type: "text" },
    { q: "Which English king had six wives and broke with the Roman Catholic Church?", a: "Henry VIII", points: 800, type: "text" },
    { q: "In which year did the Magna Carta receive its royal seal?", a: "1215", points: 1000, type: "text" },
    { q: "Which 1648 treaty ended the Thirty Years' War?", a: "Peace of Westphalia", points: 1000, type: "text" },
    { q: "Which Mongol ruler founded the Yuan dynasty in China?", a: "Kublai Khan", points: 1000, type: "text" },
    { q: "What 1494 treaty divided the New World between Spain and Portugal?", a: "Treaty of Tordesillas", points: 1000, type: "text" },
    { q: "Which Carthaginian general crossed the Alps with elephants to attack Rome?", a: "Hannibal", points: 1000, type: "text" },
    { q: "Which Roman general crossed the Rubicon in 49 BC, sparking civil war?", a: "Julius Caesar", points: 1000, type: "text" },
    { q: "Which queen ruled England during the defeat of the Spanish Armada in 1588?", a: "Elizabeth I", points: 1000, type: "text" },
    { q: "In which year did the Soviet Union officially dissolve?", a: "1991", points: 1000, type: "text" }
  ],
  "Geography": [
    { q: "Which country is shaped like a boot?", a: "Italy", points: 200, type: "text" },
    { q: "What is the largest ocean on Earth?", a: "Pacific Ocean", points: 200, type: "text" },
    { q: "On which continent is the Sahara Desert located?", a: "Africa", points: 200, type: "text" },
    { q: "Which river flows through Egypt and is the longest in Africa?", a: "Nile", points: 200, type: "text" },
    { q: "What is the largest country in the world by land area?", a: "Russia", points: 200, type: "text" },
    { q: "Which mountain is the tallest in the world above sea level?", a: "Mount Everest", points: 200, type: "text" },
    { q: "In which country is the Eiffel Tower located?", a: "France", points: 200, type: "text" },
    { q: "Which country is famous as the home of the kangaroo?", a: "Australia", points: 200, type: "text" },
    { q: "Which U.S. state is the largest by land area?", a: "Alaska", points: 400, type: "text" },
    { q: "What is the capital of Australia?", a: "Canberra", points: 400, type: "text" },
    { q: "Which country has the most natural lakes in the world?", a: "Canada", points: 400, type: "text" },
    { q: "The Andes mountain range runs along the western edge of which continent?", a: "South America", points: 400, type: "text" },
    { q: "What is the capital city of Canada?", a: "Ottawa", points: 400, type: "text" },
    { q: "Which African country was never colonized by a European power?", a: "Ethiopia", points: 400, type: "text" },
    { q: "What is the smallest country in the world by area?", a: "Vatican City", points: 400, type: "text" },
    { q: "Which sea separates Europe from Africa near Gibraltar?", a: "Mediterranean Sea", points: 400, type: "text" },
    { q: "Which strait connects the Mediterranean Sea to the Atlantic Ocean?", a: "Strait of Gibraltar", points: 600, type: "text" },
    { q: "What is the capital of New Zealand?", a: "Wellington", points: 600, type: "text" },
    { q: "The Atacama Desert, one of the driest places on Earth, is in which country?", a: "Chile", points: 600, type: "text" },
    { q: "Which European capital is divided by the Danube into Buda and Pest?", a: "Budapest", points: 600, type: "text" },
    { q: "What is the largest lake in the world by surface area?", a: "Caspian Sea", points: 600, type: "text" },
    { q: "Which country has the longest coastline in the world?", a: "Canada", points: 600, type: "text" },
    { q: "Mount Kilimanjaro, Africa's highest peak, is located in which country?", a: "Tanzania", points: 600, type: "text" },
    { q: "The Atacama aside, which country is both the largest island and a continent?", a: "Australia", points: 600, type: "text" },
    { q: "What is the capital of Kazakhstan?", a: "Astana", points: 800, type: "text" },
    { q: "Which two countries share the longest international border?", a: "United States and Canada", points: 800, type: "text" },
    { q: "Lake Titicaca, the highest navigable lake, lies between Peru and which country?", a: "Bolivia", points: 800, type: "text" },
    { q: "Which country has the most time zones, including its overseas territories?", a: "France", points: 800, type: "text" },
    { q: "The Strait of Malacca lies between the Malay Peninsula and which Indonesian island?", a: "Sumatra", points: 800, type: "text" },
    { q: "Which mountain range forms a natural border between France and Spain?", a: "Pyrenees", points: 800, type: "text" },
    { q: "What is the capital of Bhutan?", a: "Thimphu", points: 800, type: "text" },
    { q: "Which African country is completely surrounded by South Africa?", a: "Lesotho", points: 800, type: "text" },
    { q: "What is the southernmost capital city of any independent country?", a: "Wellington", points: 1000, type: "text" },
    { q: "Which country is the only one to lie in all four hemispheres?", a: "Kiribati", points: 1000, type: "text" },
    { q: "The Wallace Line divides Asian and Australian wildlife near which two islands?", a: "Bali and Lombok", points: 1000, type: "text" },
    { q: "Which landlocked country is surrounded by only Russia and China?", a: "Mongolia", points: 1000, type: "text" },
    { q: "What is the capital of Eritrea?", a: "Asmara", points: 1000, type: "text" },
    { q: "Which Central Asian country is the world's largest landlocked country?", a: "Kazakhstan", points: 1000, type: "text" },
    { q: "What is the capital of Mongolia?", a: "Ulaanbaatar", points: 1000, type: "text" },
    { q: "Which country's flag is this?", a: "Italy", points: 200, type: "image", emoji: "🇮🇹" },
    { q: "Which country's flag is this?", a: "Brazil", points: 400, type: "image", emoji: "🇧🇷" },
    { q: "Which country's flag is this?", a: "Sweden", points: 600, type: "image", emoji: "🇸🇪" },
    { q: "Which country's flag is this?", a: "South Korea", points: 800, type: "image", emoji: "🇰🇷" },
    { q: "Which country's flag is this?", a: "Turkey", points: 1000, type: "image", emoji: "🇹🇷" }
  ],
  "Movies & TV": [
    { q: "Which animated film features a clownfish father named Marlin searching for his son?", a: "Finding Nemo", points: 200, type: "text" },
    { q: "In which film series does Harry Potter attend Hogwarts?", a: "Harry Potter", points: 200, type: "text" },
    { q: "What is the name of the lion who becomes king in Disney's The Lion King?", a: "Simba", points: 200, type: "text" },
    { q: "Which superhero is known as the Caped Crusader and protects Gotham City?", a: "Batman", points: 200, type: "text" },
    { q: "In the sitcom Friends, what is the name of the coffee shop the characters frequent?", a: "Central Perk", points: 200, type: "text" },
    { q: "Which film features a great white shark terrorizing a beach town called Amity?", a: "Jaws", points: 200, type: "text" },
    { q: "What is the name of the toy cowboy in the Toy Story films?", a: "Woody", points: 200, type: "text" },
    { q: "Which movie features a sinking ocean liner and characters named Jack and Rose?", a: "Titanic", points: 200, type: "text" },
    { q: "Which actor played Jack Sparrow in the Pirates of the Caribbean films?", a: "Johnny Depp", points: 400, type: "text" },
    { q: "In Breaking Bad, what is chemistry teacher Walter White's street alias?", a: "Heisenberg", points: 400, type: "text" },
    { q: "Which 1994 film features the line about life being like a box of chocolates?", a: "Forrest Gump", points: 400, type: "text" },
    { q: "What is the name of the fictional African nation in the film Black Panther?", a: "Wakanda", points: 400, type: "text" },
    { q: "Which director made Jurassic Park and Schindler's List?", a: "Steven Spielberg", points: 400, type: "text" },
    { q: "In Game of Thrones, which noble house has the words 'Winter Is Coming'?", a: "House Stark", points: 400, type: "text" },
    { q: "Which Pixar film takes place largely inside the mind of a girl named Riley?", a: "Inside Out", points: 400, type: "text" },
    { q: "Which captain commands the starship Enterprise in Star Trek: The Next Generation?", a: "Jean-Luc Picard", points: 400, type: "text" },
    { q: "Which 1972 film won Best Picture and follows the Corleone family?", a: "The Godfather", points: 600, type: "text" },
    { q: "Who directed the 2010 film Inception?", a: "Christopher Nolan", points: 600, type: "text" },
    { q: "In the US version of The Office, what paper company branch does the show follow?", a: "Dunder Mifflin Scranton", points: 600, type: "text" },
    { q: "Which actress won an Oscar for playing the boxer in Million Dollar Baby?", a: "Hilary Swank", points: 600, type: "text" },
    { q: "What is the name of the kingdom ruled by Elsa in Disney's Frozen?", a: "Arendelle", points: 600, type: "text" },
    { q: "Which 1999 film features a character named Neo who learns reality is a simulation?", a: "The Matrix", points: 600, type: "text" },
    { q: "Who composed the iconic musical score for the original Star Wars films?", a: "John Williams", points: 600, type: "text" },
    { q: "In The Sopranos, what is the first name of mob boss Tony Soprano's wife?", a: "Carmela", points: 600, type: "text" },
    { q: "Which film won the first Academy Award for Best Animated Feature in 2002?", a: "Shrek", points: 800, type: "text" },
    { q: "Who directed the 1960 thriller Psycho?", a: "Alfred Hitchcock", points: 800, type: "text" },
    { q: "Which actor played the Joker in the 2008 film The Dark Knight?", a: "Heath Ledger", points: 800, type: "text" },
    { q: "What is the name of the hotel in Stanley Kubrick's film The Shining?", a: "Overlook Hotel", points: 800, type: "text" },
    { q: "Which Italian film won the 1999 Best Foreign Language Oscar and starred Roberto Benigni?", a: "Life Is Beautiful", points: 800, type: "text" },
    { q: "In Mad Men, what advertising agency does Don Draper work at when the show begins?", a: "Sterling Cooper", points: 800, type: "text" },
    { q: "Who directed the 2019 film Parasite, the first non-English Best Picture winner?", a: "Bong Joon-ho", points: 800, type: "text" },
    { q: "In which animated franchise would you find characters named Shrek and Donkey?", a: "Shrek", points: 800, type: "text" },
    { q: "Which 1941 film by Orson Welles is frequently called the greatest film ever made?", a: "Citizen Kane", points: 1000, type: "text" },
    { q: "In Blade Runner, what term is used for the artificial humans hunted by Deckard?", a: "Replicants", points: 1000, type: "text" },
    { q: "Which director won the Best Director Oscar for Saving Private Ryan?", a: "Steven Spielberg", points: 1000, type: "text" },
    { q: "Which Japanese director made the 1954 film Seven Samurai?", a: "Akira Kurosawa", points: 1000, type: "text" },
    { q: "In Twin Peaks, whose murder opens the series?", a: "Laura Palmer", points: 1000, type: "text" },
    { q: "Which actress has won the most competitive acting Academy Awards, with four wins?", a: "Katharine Hepburn", points: 1000, type: "text" },
    { q: "Which 1957 courtroom drama features a jury deliberating in a single room, with Henry Fonda as Juror 8?", a: "12 Angry Men", points: 1000, type: "text" },
    { q: "Who directed the 1975 film One Flew Over the Cuckoo's Nest?", a: "Milos Forman", points: 1000, type: "text" }
  ],
  "Music & Songs": [
    { q: "Which British band recorded Abbey Road and included John, Paul, George, and Ringo?", a: "The Beatles", points: 200, type: "text" },
    { q: "What instrument did Jimi Hendrix famously play?", a: "Guitar", points: 200, type: "text" },
    { q: "Which artist is known as the King of Pop?", a: "Michael Jackson", points: 200, type: "text" },
    { q: "What is the name of the band fronted by Freddie Mercury?", a: "Queen", points: 200, type: "text" },
    { q: "Which pop star released the album 1989 and the song Shake It Off?", a: "Taylor Swift", points: 200, type: "text" },
    { q: "How many strings does a standard guitar have?", a: "Six", points: 200, type: "text" },
    { q: "Which artist is known as the Queen of Pop and released Like a Prayer?", a: "Madonna", points: 200, type: "text" },
    { q: "What genre of music from Jamaica is associated with Bob Marley?", a: "Reggae", points: 200, type: "text" },
    { q: "Which band released the rock anthem Bohemian Rhapsody in 1975?", a: "Queen", points: 400, type: "text" },
    { q: "Who is the lead singer of the band U2?", a: "Bono", points: 400, type: "text" },
    { q: "Which composer wrote the Ninth Symphony, which includes Ode to Joy?", a: "Ludwig van Beethoven", points: 400, type: "text" },
    { q: "Which American singer was known as the Queen of Soul?", a: "Aretha Franklin", points: 400, type: "text" },
    { q: "What is the name of Beyonce's former girl group?", a: "Destiny's Child", points: 400, type: "text" },
    { q: "Which 1982 Michael Jackson album is the best-selling album of all time?", a: "Thriller", points: 400, type: "text" },
    { q: "Which rapper released the album The Marshall Mathers LP?", a: "Eminem", points: 400, type: "text" },
    { q: "Which band recorded the album The Dark Side of the Moon?", a: "Pink Floyd", points: 400, type: "text" },
    { q: "Who composed the four concertos known as The Four Seasons?", a: "Antonio Vivaldi", points: 600, type: "text" },
    { q: "Which Swedish pop group won Eurovision in 1974 with the song Waterloo?", a: "ABBA", points: 600, type: "text" },
    { q: "What term describes the speed or pace of a piece of music?", a: "Tempo", points: 600, type: "text" },
    { q: "Which guitarist was a founding member of Led Zeppelin?", a: "Jimmy Page", points: 600, type: "text" },
    { q: "Who recorded the influential 1959 jazz album Kind of Blue?", a: "Miles Davis", points: 600, type: "text" },
    { q: "Which singer-songwriter released the 1971 album Blue and wrote Big Yellow Taxi?", a: "Joni Mitchell", points: 600, type: "text" },
    { q: "What Italian term on sheet music means to play very loud?", a: "Fortissimo", points: 600, type: "text" },
    { q: "Which English rock band released the 1997 album OK Computer?", a: "Radiohead", points: 600, type: "text" },
    { q: "Which composer wrote the opera The Magic Flute?", a: "Wolfgang Amadeus Mozart", points: 800, type: "text" },
    { q: "How many keys are on a standard full-size piano?", a: "88", points: 800, type: "text" },
    { q: "Which jazz singer was nicknamed the First Lady of Song?", a: "Ella Fitzgerald", points: 800, type: "text" },
    { q: "Which 1966 Beach Boys album is considered a landmark of pop music?", a: "Pet Sounds", points: 800, type: "text" },
    { q: "What is the highest female singing voice type in classical music?", a: "Soprano", points: 800, type: "text" },
    { q: "Which Russian composer wrote the ballet Swan Lake?", a: "Pyotr Ilyich Tchaikovsky", points: 800, type: "text" },
    { q: "Which band released the 1991 album Nevermind, featuring Smells Like Teen Spirit?", a: "Nirvana", points: 800, type: "text" },
    { q: "What name is given to a musical composition written for the dead or a funeral?", a: "Requiem", points: 800, type: "text" },
    { q: "What is the term for a group of five musicians performing together?", a: "Quintet", points: 1000, type: "text" },
    { q: "Which German composer wrote the four-opera cycle The Ring of the Nibelung?", a: "Richard Wagner", points: 1000, type: "text" },
    { q: "What is the lowest male singing voice type in classical music?", a: "Bass", points: 1000, type: "text" },
    { q: "Which jazz pianist and composer wrote the standard Round Midnight?", a: "Thelonious Monk", points: 1000, type: "text" },
    { q: "What Italian musical term indicates a gradual decrease in volume?", a: "Diminuendo", points: 1000, type: "text" },
    { q: "Which composer wrote The Rite of Spring, which caused a riot at its 1913 premiere?", a: "Igor Stravinsky", points: 1000, type: "text" },
    { q: "What scale consists of all twelve pitches, used in serial composition?", a: "Chromatic scale", points: 1000, type: "text" },
    { q: "Which Austrian composer's unfinished Requiem was completed by his student Sussmayr?", a: "Wolfgang Amadeus Mozart", points: 1000, type: "text" }
  ],
  "Science": [
    { q: "What is the closest planet to the Sun?", a: "Mercury", points: 200, type: "text" },
    { q: "What gas do humans breathe in to survive?", a: "Oxygen", points: 200, type: "text" },
    { q: "What is the chemical symbol for water?", a: "H2O", points: 200, type: "text" },
    { q: "What force pulls objects toward the Earth?", a: "Gravity", points: 200, type: "text" },
    { q: "What is the largest planet in our solar system?", a: "Jupiter", points: 200, type: "text" },
    { q: "What organ pumps blood through the human body?", a: "The heart", points: 200, type: "text" },
    { q: "What is the center of an atom called?", a: "The nucleus", points: 200, type: "text" },
    { q: "At what temperature in Celsius does water freeze?", a: "0 degrees", points: 200, type: "text" },
    { q: "What is the hardest known natural material on Earth?", a: "Diamond", points: 400, type: "text" },
    { q: "What part of the cell contains DNA?", a: "The nucleus", points: 400, type: "text" },
    { q: "What planet is known as the Red Planet?", a: "Mars", points: 400, type: "text" },
    { q: "What is the chemical symbol for gold?", a: "Au", points: 400, type: "text" },
    { q: "Which scientist developed the theory of general relativity?", a: "Albert Einstein", points: 400, type: "text" },
    { q: "What is the powerhouse of the cell?", a: "The mitochondria", points: 400, type: "text" },
    { q: "What is the most abundant gas in Earth's atmosphere?", a: "Nitrogen", points: 400, type: "text" },
    { q: "What process do plants use to convert light into chemical energy?", a: "Photosynthesis", points: 400, type: "text" },
    { q: "What is the SI unit of electrical resistance?", a: "The ohm", points: 600, type: "text" },
    { q: "What subatomic particle has a negative charge?", a: "The electron", points: 600, type: "text" },
    { q: "What is the most common element in the universe by mass?", a: "Hydrogen", points: 600, type: "text" },
    { q: "Which scientist proposed the laws of planetary motion?", a: "Johannes Kepler", points: 600, type: "text" },
    { q: "What is the pH value of a neutral solution at room temperature?", a: "7", points: 600, type: "text" },
    { q: "What type of radiation has the longest wavelength on the electromagnetic spectrum?", a: "Radio waves", points: 600, type: "text" },
    { q: "What galaxy contains our solar system?", a: "The Milky Way", points: 600, type: "text" },
    { q: "How many chromosomes are in a typical human body cell?", a: "46", points: 600, type: "text" },
    { q: "What is the SI unit of magnetic flux density?", a: "The tesla", points: 800, type: "text" },
    { q: "What enzyme unwinds the DNA double helix during replication?", a: "Helicase", points: 800, type: "text" },
    { q: "What is the name of the boundary around a black hole beyond which nothing can escape?", a: "The event horizon", points: 800, type: "text" },
    { q: "Which scientist first measured the charge of an electron with the oil-drop experiment?", a: "Robert Millikan", points: 800, type: "text" },
    { q: "What is the heaviest naturally occurring element on the periodic table?", a: "Uranium", points: 800, type: "text" },
    { q: "What principle states you cannot simultaneously know a particle's exact position and momentum?", a: "The Heisenberg uncertainty principle", points: 800, type: "text" },
    { q: "What organelle in plant cells is responsible for photosynthesis?", a: "The chloroplast", points: 800, type: "text" },
    { q: "What is the term for the temperature at which all molecular motion theoretically stops?", a: "Absolute zero", points: 800, type: "text" },
    { q: "What fundamental particle is thought to give other particles mass?", a: "The Higgs boson", points: 1000, type: "text" },
    { q: "Which physicist formulated the equation describing quantum wavefunctions?", a: "Erwin Schrodinger", points: 1000, type: "text" },
    { q: "What is the process by which heavy elements form in the cores of massive stars?", a: "Stellar nucleosynthesis", points: 1000, type: "text" },
    { q: "What is the chemical symbol for the element antimony?", a: "Sb", points: 1000, type: "text" },
    { q: "What cellular structure synthesizes proteins by translating messenger RNA?", a: "The ribosome", points: 1000, type: "text" },
    { q: "What law states that the entropy of an isolated system never decreases?", a: "The second law of thermodynamics", points: 1000, type: "text" },
    { q: "What is the approximate half-life of carbon-14, used in radiocarbon dating?", a: "About 5,730 years", points: 1000, type: "text" },
    { q: "What is the term for a star that has collapsed into an extremely dense ball of neutrons?", a: "A neutron star", points: 1000, type: "text" }
  ],
  "Animals & Nature": [
    { q: "What is the largest land animal on Earth?", a: "The elephant", points: 200, type: "text" },
    { q: "What is the tallest animal in the world?", a: "The giraffe", points: 200, type: "text" },
    { q: "What is the largest big cat in the world?", a: "The tiger", points: 200, type: "text" },
    { q: "What do bees produce that humans eat?", a: "Honey", points: 200, type: "text" },
    { q: "What is the fastest land animal?", a: "The cheetah", points: 200, type: "text" },
    { q: "What do we call an animal that hunts other animals for food?", a: "A predator", points: 200, type: "text" },
    { q: "What ocean animal is known for having eight arms?", a: "The octopus", points: 200, type: "text" },
    { q: "What do we call animals that eat only plants?", a: "Herbivores", points: 200, type: "text" },
    { q: "What is the largest animal ever known to have lived?", a: "The blue whale", points: 400, type: "text" },
    { q: "What is the only mammal capable of true flight?", a: "The bat", points: 400, type: "text" },
    { q: "What is a group of lions called?", a: "A pride", points: 400, type: "text" },
    { q: "What is the largest species of bear?", a: "The polar bear", points: 400, type: "text" },
    { q: "What gas do plants absorb from the air during photosynthesis?", a: "Carbon dioxide", points: 400, type: "text" },
    { q: "What is the hardest substance in the human body?", a: "Tooth enamel", points: 400, type: "text" },
    { q: "Which flightless bird lives in Antarctica and swims to catch fish?", a: "The penguin", points: 400, type: "text" },
    { q: "What is the process by which a caterpillar becomes a butterfly?", a: "Metamorphosis", points: 400, type: "text" },
    { q: "What is the largest living species of reptile?", a: "The saltwater crocodile", points: 600, type: "text" },
    { q: "What is a group of crows called?", a: "A murder", points: 600, type: "text" },
    { q: "What is the term for animals that are active at night?", a: "Nocturnal", points: 600, type: "text" },
    { q: "What is the largest type of penguin?", a: "The emperor penguin", points: 600, type: "text" },
    { q: "What is the longest venomous snake in the world?", a: "The king cobra", points: 600, type: "text" },
    { q: "What is the study of birds called?", a: "Ornithology", points: 600, type: "text" },
    { q: "What tree species is the tallest in the world?", a: "The coast redwood", points: 600, type: "text" },
    { q: "What is the term for an animal that eats both plants and meat?", a: "An omnivore", points: 600, type: "text" },
    { q: "What is the only bird known to fly backwards?", a: "The hummingbird", points: 800, type: "text" },
    { q: "What is the largest species of shark?", a: "The whale shark", points: 800, type: "text" },
    { q: "What is the world's largest species of rodent?", a: "The capybara", points: 800, type: "text" },
    { q: "What egg-laying mammal is native to Australia and has a duck-like bill?", a: "The platypus", points: 800, type: "text" },
    { q: "What is the scientific name for the gray wolf?", a: "Canis lupus", points: 800, type: "text" },
    { q: "What is the deepest part of the world's oceans called?", a: "The Mariana Trench", points: 800, type: "text" },
    { q: "What is the term for a plant that lives for only one growing season?", a: "An annual", points: 800, type: "text" },
    { q: "What layer of the rainforest, formed by treetops, holds most of its animal life?", a: "The canopy", points: 800, type: "text" },
    { q: "What is the only venomous primate in the world?", a: "The slow loris", points: 1000, type: "text" },
    { q: "What is the scientific name for the species of modern humans?", a: "Homo sapiens", points: 1000, type: "text" },
    { q: "What is the largest amphibian in the world?", a: "The Chinese giant salamander", points: 1000, type: "text" },
    { q: "What is the term for a symbiotic relationship in which both species benefit?", a: "Mutualism", points: 1000, type: "text" },
    { q: "What flightless bird native to New Zealand shares its name with a fruit?", a: "The kiwi", points: 1000, type: "text" },
    { q: "What spiny egg-laying mammal of Australia and New Guinea is also called a spiny anteater?", a: "The echidna", points: 1000, type: "text" },
    { q: "What is the largest invertebrate in the world?", a: "The colossal squid", points: 1000, type: "text" },
    { q: "What is the term for an animal active mainly at dawn and dusk?", a: "Crepuscular", points: 1000, type: "text" }
  ],
  "Food & Drink": [
    { q: "What fruit is traditionally used to make wine?", a: "Grapes", points: 200, type: "text" },
    { q: "What is the main ingredient in guacamole?", a: "Avocado", points: 200, type: "text" },
    { q: "What hot drink is made from roasted beans?", a: "Coffee", points: 200, type: "text" },
    { q: "What dairy product is churned to make butter?", a: "Cream", points: 200, type: "text" },
    { q: "What Italian dish is a flat bread topped with cheese and sauce?", a: "Pizza", points: 200, type: "text" },
    { q: "What vegetable is famous for making people cry when cut?", a: "The onion", points: 200, type: "text" },
    { q: "What is the main ingredient in bread?", a: "Flour", points: 200, type: "text" },
    { q: "What yellow fruit do monkeys famously love to eat?", a: "The banana", points: 200, type: "text" },
    { q: "What spice is the most expensive in the world by weight?", a: "Saffron", points: 400, type: "text" },
    { q: "What country is the origin of sushi?", a: "Japan", points: 400, type: "text" },
    { q: "What type of dough is used to make a croissant?", a: "Laminated (puff) pastry", points: 400, type: "text" },
    { q: "What grain is used to make traditional Japanese sake?", a: "Rice", points: 400, type: "text" },
    { q: "What bean is chocolate made from?", a: "The cacao bean", points: 400, type: "text" },
    { q: "What is the national dish of Spain made with rice and saffron?", a: "Paella", points: 400, type: "text" },
    { q: "What fermented soybean paste is a staple in Japanese soup?", a: "Miso", points: 400, type: "text" },
    { q: "What spirit is made by distilling fermented agave?", a: "Tequila", points: 400, type: "text" },
    { q: "What is the French term for a kitchen's setup of prepared ingredients?", a: "Mise en place", points: 600, type: "text" },
    { q: "What country produces the most coffee in the world?", a: "Brazil", points: 600, type: "text" },
    { q: "What cut of meat is used for a traditional Italian osso buco?", a: "Veal shank", points: 600, type: "text" },
    { q: "What is the main alcoholic ingredient in a mojito?", a: "Rum", points: 600, type: "text" },
    { q: "What type of cheese is traditionally used in an authentic Greek salad?", a: "Feta", points: 600, type: "text" },
    { q: "What gas, produced by yeast, makes bread rise?", a: "Carbon dioxide", points: 600, type: "text" },
    { q: "What is the Japanese term for the savory fifth taste?", a: "Umami", points: 600, type: "text" },
    { q: "Which region of France is most famous for its sparkling wine?", a: "Champagne", points: 600, type: "text" },
    { q: "What Mexican sauce is made with chocolate and chili peppers?", a: "Mole", points: 800, type: "text" },
    { q: "Besides chickpeas, what paste is a key ingredient in hummus?", a: "Tahini", points: 800, type: "text" },
    { q: "What grape variety is used to make traditional red Burgundy wine?", a: "Pinot Noir", points: 800, type: "text" },
    { q: "What cooking technique seals food in a bag and cooks it in a temperature-controlled water bath?", a: "Sous vide", points: 800, type: "text" },
    { q: "What spice gives curry its characteristic yellow color?", a: "Turmeric", points: 800, type: "text" },
    { q: "What Italian rice variety is most commonly used to make risotto?", a: "Arborio", points: 800, type: "text" },
    { q: "What is the name of the fermented Korean cabbage dish?", a: "Kimchi", points: 800, type: "text" },
    { q: "What Italian dessert's name translates to 'pick me up'?", a: "Tiramisu", points: 800, type: "text" },
    { q: "What chemical reaction between amino acids and sugars browns and flavors cooked food?", a: "The Maillard reaction", points: 1000, type: "text" },
    { q: "What noble rot fungus is used to make sweet dessert wines like Sauternes?", a: "Botrytis cinerea", points: 1000, type: "text" },
    { q: "What Spanish cured ham is made from acorn-fed black Iberian pigs?", a: "Jamon iberico de bellota", points: 1000, type: "text" },
    { q: "What aged Italian cheese must come from specific provinces and age at least 12 months?", a: "Parmigiano-Reggiano", points: 1000, type: "text" },
    { q: "What expensive coffee is made from beans digested and excreted by a civet?", a: "Kopi luwak", points: 1000, type: "text" },
    { q: "What grape variety is the main component of most Italian Chianti wines?", a: "Sangiovese", points: 1000, type: "text" },
    { q: "What French sauce, one of the five mother sauces, is made from milk thickened with a white roux?", a: "Bechamel", points: 1000, type: "text" },
    { q: "What is the Japanese rice wine traditionally served warm or chilled?", a: "Sake", points: 1000, type: "text" }
  ],
  "Famous People": [
    { q: "Who was the first President of the United States?", a: "George Washington", points: 200, type: "text" },
    { q: "Which English playwright wrote Romeo and Juliet?", a: "William Shakespeare", points: 200, type: "text" },
    { q: "Who painted the Mona Lisa?", a: "Leonardo da Vinci", points: 200, type: "text" },
    { q: "Which civil rights leader gave the 'I Have a Dream' speech?", a: "Martin Luther King Jr.", points: 200, type: "text" },
    { q: "Who developed the theory of relativity?", a: "Albert Einstein", points: 200, type: "text" },
    { q: "Which British scientist proposed evolution by natural selection?", a: "Charles Darwin", points: 200, type: "text" },
    { q: "Who was the first man to walk on the Moon?", a: "Neil Armstrong", points: 200, type: "text" },
    { q: "Which Indian leader championed nonviolent resistance against British rule?", a: "Mahatma Gandhi", points: 200, type: "text" },
    { q: "Which queen ruled the United Kingdom from 1837 to 1901?", a: "Queen Victoria", points: 400, type: "text" },
    { q: "Who was the first woman to win a Nobel Prize?", a: "Marie Curie", points: 400, type: "text" },
    { q: "Which artist cut off part of his own ear?", a: "Vincent van Gogh", points: 400, type: "text" },
    { q: "Who was the first President of South Africa elected after apartheid?", a: "Nelson Mandela", points: 400, type: "text" },
    { q: "Which composer wrote his Ninth Symphony while almost completely deaf?", a: "Ludwig van Beethoven", points: 400, type: "text" },
    { q: "Who was the British Prime Minister during most of World War II?", a: "Winston Churchill", points: 400, type: "text" },
    { q: "Which explorer is credited with reaching the Americas in 1492?", a: "Christopher Columbus", points: 400, type: "text" },
    { q: "Who wrote the tragedies Hamlet and King Lear?", a: "William Shakespeare", points: 400, type: "text" },
    { q: "Which Roman general was assassinated on the Ides of March in 44 BC?", a: "Julius Caesar", points: 600, type: "text" },
    { q: "Who was the first female Prime Minister of the United Kingdom?", a: "Margaret Thatcher", points: 600, type: "text" },
    { q: "Which astronomer was forced by the Church to recant his support for heliocentrism?", a: "Galileo Galilei", points: 600, type: "text" },
    { q: "Who wrote the novels Pride and Prejudice and Emma?", a: "Jane Austen", points: 600, type: "text" },
    { q: "Which nurse became famous for her work during the Crimean War?", a: "Florence Nightingale", points: 600, type: "text" },
    { q: "Who was crowned the first Emperor of France in 1804?", a: "Napoleon Bonaparte", points: 600, type: "text" },
    { q: "Which American author wrote The Adventures of Huckleberry Finn?", a: "Mark Twain", points: 600, type: "text" },
    { q: "Who painted the ceiling of the Sistine Chapel?", a: "Michelangelo", points: 600, type: "text" },
    { q: "Which English mathematician helped found computer science and broke the Enigma code?", a: "Alan Turing", points: 800, type: "text" },
    { q: "Which Macedonian king, tutored by Aristotle, conquered the Persian Empire?", a: "Alexander the Great", points: 800, type: "text" },
    { q: "Which female pharaoh was one of ancient Egypt's most successful rulers in the 18th Dynasty?", a: "Hatshepsut", points: 800, type: "text" },
    { q: "Which Russian novelist wrote War and Peace?", a: "Leo Tolstoy", points: 800, type: "text" },
    { q: "Which German theologian's 95 Theses helped launch the Protestant Reformation?", a: "Martin Luther", points: 800, type: "text" },
    { q: "Who was the first woman to fly solo across the Atlantic Ocean?", a: "Amelia Earhart", points: 800, type: "text" },
    { q: "Which Mongol ruler founded the largest contiguous land empire in history?", a: "Genghis Khan", points: 800, type: "text" },
    { q: "Which Austrian composer wrote the opera The Marriage of Figaro?", a: "Wolfgang Amadeus Mozart", points: 800, type: "text" },
    { q: "Which Byzantine empress, wife of Justinian I, held great political power in the 6th century?", a: "Theodora", points: 1000, type: "text" },
    { q: "Which Danish physicist won the 1922 Nobel Prize for his model of atomic structure?", a: "Niels Bohr", points: 1000, type: "text" },
    { q: "Which Persian mathematician's name gives us the word 'algorithm'?", a: "Al-Khwarizmi", points: 1000, type: "text" },
    { q: "Who was the first woman elected to the United States Congress, in 1916?", a: "Jeannette Rankin", points: 1000, type: "text" },
    { q: "Which Italian explorer's first name inspired the naming of the Americas?", a: "Amerigo Vespucci", points: 1000, type: "text" },
    { q: "Which English chemist isolated oxygen gas in 1774?", a: "Joseph Priestley", points: 1000, type: "text" },
    { q: "Which ancient Greek physician is considered the father of medicine?", a: "Hippocrates", points: 1000, type: "text" },
    { q: "Which Carthaginian general famously crossed the Alps with war elephants?", a: "Hannibal", points: 1000, type: "text" }
  ],
  "Technology & Inventions": [
    { q: "What device, invented by Alexander Graham Bell, lets people talk over long distances?", a: "The telephone", points: 200, type: "text" },
    { q: "Who is credited with inventing the practical incandescent light bulb?", a: "Thomas Edison", points: 200, type: "text" },
    { q: "What company makes the iPhone?", a: "Apple", points: 200, type: "text" },
    { q: "What worldwide network of computers lets you browse websites?", a: "The Internet", points: 200, type: "text" },
    { q: "What machine did Gutenberg famously invent to print books?", a: "The printing press", points: 200, type: "text" },
    { q: "What handheld device changes channels on a TV from across the room?", a: "The remote control", points: 200, type: "text" },
    { q: "What social media platform was known for short messages once limited to 280 characters?", a: "Twitter (X)", points: 200, type: "text" },
    { q: "What vehicle did the Wright brothers famously build and fly in 1903?", a: "The airplane", points: 200, type: "text" },
    { q: "Who co-founded Microsoft with Paul Allen?", a: "Bill Gates", points: 400, type: "text" },
    { q: "What does 'WWW' stand for?", a: "World Wide Web", points: 400, type: "text" },
    { q: "Which Italian inventor is credited with developing long-distance radio transmission?", a: "Guglielmo Marconi", points: 400, type: "text" },
    { q: "What search engine company was founded by Larry Page and Sergey Brin?", a: "Google", points: 400, type: "text" },
    { q: "What was the name of the first general-purpose electronic computer, completed in 1945?", a: "ENIAC", points: 400, type: "text" },
    { q: "Who developed the first successful polio vaccine?", a: "Jonas Salk", points: 400, type: "text" },
    { q: "Which Swedish chemist invented dynamite and founded a famous set of prizes?", a: "Alfred Nobel", points: 400, type: "text" },
    { q: "In which year was the first iPhone released?", a: "2007", points: 400, type: "text" },
    { q: "Who is credited with inventing the World Wide Web in 1989?", a: "Tim Berners-Lee", points: 600, type: "text" },
    { q: "What was the name of the first artificial Earth satellite, launched in 1957?", a: "Sputnik 1", points: 600, type: "text" },
    { q: "Which company developed the first commercially successful microprocessor, the 4004?", a: "Intel", points: 600, type: "text" },
    { q: "Which programming language created by Guido van Rossum is named after a comedy troupe?", a: "Python", points: 600, type: "text" },
    { q: "Who invented the cotton gin in 1793?", a: "Eli Whitney", points: 600, type: "text" },
    { q: "What does the acronym 'GPS' stand for?", a: "Global Positioning System", points: 600, type: "text" },
    { q: "Which inventor developed alternating current systems and once worked for Edison?", a: "Nikola Tesla", points: 600, type: "text" },
    { q: "What was the first widely successful home video game console, released by Atari in 1977?", a: "Atari 2600", points: 600, type: "text" },
    { q: "Who is often credited as the first computer programmer for her work on Babbage's Analytical Engine?", a: "Ada Lovelace", points: 800, type: "text" },
    { q: "What device, invented at Bell Labs in 1947, replaced the vacuum tube?", a: "The transistor", points: 800, type: "text" },
    { q: "Which programming language did Dennis Ritchie develop in the early 1970s?", a: "C", points: 800, type: "text" },
    { q: "What packet-switching network, funded by the US military, preceded the modern Internet?", a: "ARPANET", points: 800, type: "text" },
    { q: "What encryption standard, abbreviated AES, became the US government standard in 2001?", a: "Advanced Encryption Standard", points: 800, type: "text" },
    { q: "What was the first handheld mobile phone, demonstrated by Motorola in 1973?", a: "Motorola DynaTAC", points: 800, type: "text" },
    { q: "What photographic process, announced in 1839, produced images on silver-plated copper?", a: "The daguerreotype", points: 800, type: "text" },
    { q: "Who invented the first commercially successful sewing machine, patented in 1846?", a: "Elias Howe", points: 800, type: "text" },
    { q: "Which Hungarian-American mathematician's architecture stores programs and data in the same memory?", a: "John von Neumann", points: 1000, type: "text" },
    { q: "What was the first commercially produced electronic spreadsheet program, released in 1979?", a: "VisiCalc", points: 1000, type: "text" },
    { q: "Who invented the integrated circuit at Texas Instruments in 1958?", a: "Jack Kilby", points: 1000, type: "text" },
    { q: "What protocol suite, developed by Vint Cerf and Bob Kahn, is the foundation of Internet communication?", a: "TCP/IP", points: 1000, type: "text" },
    { q: "Which English engineer designed the Difference Engine and Analytical Engine?", a: "Charles Babbage", points: 1000, type: "text" },
    { q: "What was the name of the first stored-program computer to run a program, built in Manchester in 1948?", a: "The Manchester Baby", points: 1000, type: "text" },
    { q: "Which Serbian-American engineer's namesake unit measures magnetic flux density?", a: "Nikola Tesla", points: 1000, type: "text" },
    { q: "What 1969 transmission was the first message sent over ARPANET?", a: "LOGIN (only 'LO' got through)", points: 1000, type: "text" }
  ],
  "Space & Astronomy": [
    { q: "What is the name of the star at the center of our solar system?", a: "The Sun", points: 200, type: "text" },
    { q: "What planet do humans live on?", a: "Earth", points: 200, type: "text" },
    { q: "What is Earth's only natural satellite called?", a: "The Moon", points: 200, type: "text" },
    { q: "Which planet is known as the Red Planet?", a: "Mars", points: 200, type: "text" },
    { q: "What galaxy do we live in?", a: "The Milky Way", points: 200, type: "text" },
    { q: "Which planet is the largest in our solar system?", a: "Jupiter", points: 200, type: "text" },
    { q: "What US space agency sent astronauts to the Moon?", a: "NASA", points: 200, type: "text" },
    { q: "What do we call a small space rock that burns up in the atmosphere as a streak of light?", a: "A meteor", points: 200, type: "text" },
    { q: "Which planet is famous for its prominent rings?", a: "Saturn", points: 400, type: "text" },
    { q: "What is the closest planet to the Sun?", a: "Mercury", points: 400, type: "text" },
    { q: "What force keeps the planets in orbit around the Sun?", a: "Gravity", points: 400, type: "text" },
    { q: "What was the name of the first artificial satellite launched into space?", a: "Sputnik 1", points: 400, type: "text" },
    { q: "Who was the first human to travel into space?", a: "Yuri Gagarin", points: 400, type: "text" },
    { q: "What space telescope launched in 1990 is known for its deep-space images?", a: "Hubble Space Telescope", points: 400, type: "text" },
    { q: "What do we call a collapsed object whose gravity is so strong even light cannot escape?", a: "A black hole", points: 400, type: "text" },
    { q: "Which planet is often called Earth's twin because of its similar size?", a: "Venus", points: 400, type: "text" },
    { q: "What was the name of the Apollo mission that first landed humans on the Moon?", a: "Apollo 11", points: 600, type: "text" },
    { q: "What is the term for the path one object takes around another in space?", a: "An orbit", points: 600, type: "text" },
    { q: "Which planet has the largest volcano in the solar system, Olympus Mons?", a: "Mars", points: 600, type: "text" },
    { q: "Which dwarf planet was reclassified from a planet in 2006?", a: "Pluto", points: 600, type: "text" },
    { q: "What is the boundary around a black hole beyond which nothing can escape?", a: "The event horizon", points: 600, type: "text" },
    { q: "Which astronomer formulated three laws of planetary motion in the early 1600s?", a: "Johannes Kepler", points: 600, type: "text" },
    { q: "What is the largest moon in the solar system, orbiting Jupiter?", a: "Ganymede", points: 600, type: "text" },
    { q: "Who was the first woman in space?", a: "Valentina Tereshkova", points: 600, type: "text" },
    { q: "What is the region of icy bodies beyond Neptune where Pluto resides?", a: "The Kuiper Belt", points: 800, type: "text" },
    { q: "Which star is the closest to our solar system, other than the Sun?", a: "Proxima Centauri", points: 800, type: "text" },
    { q: "What term describes the explosive death of a massive star?", a: "A supernova", points: 800, type: "text" },
    { q: "Who proposed that the universe is expanding, based on the redshift of distant galaxies?", a: "Edwin Hubble", points: 800, type: "text" },
    { q: "What is the name of Saturn's largest moon, which has a thick atmosphere?", a: "Titan", points: 800, type: "text" },
    { q: "What unit of distance equals the average distance from the Earth to the Sun?", a: "An astronomical unit (AU)", points: 800, type: "text" },
    { q: "What was the name of the first space station, launched by the Soviet Union in 1971?", a: "Salyut 1", points: 800, type: "text" },
    { q: "What type of star is the Sun classified as on the main sequence?", a: "A yellow dwarf", points: 800, type: "text" },
    { q: "What spacecraft launched in 1977 became the first human-made object to enter interstellar space?", a: "Voyager 1", points: 1000, type: "text" },
    { q: "Whose namesake limit describes the maximum mass of a stable white dwarf?", a: "Subrahmanyan Chandrasekhar", points: 1000, type: "text" },
    { q: "What is the term for the apparent shift of a nearby star used to measure its distance?", a: "Parallax", points: 1000, type: "text" },
    { q: "Which moon of Jupiter is a strong candidate for a subsurface ocean and possible life?", a: "Europa", points: 1000, type: "text" },
    { q: "What leftover radiation from the Big Bang was discovered in 1965?", a: "The cosmic microwave background", points: 1000, type: "text" },
    { q: "Which large spiral galaxy is on a collision course with the Milky Way?", a: "The Andromeda Galaxy", points: 1000, type: "text" },
    { q: "Which Danish astronomer's precise naked-eye observations enabled Kepler's laws?", a: "Tycho Brahe", points: 1000, type: "text" },
    { q: "What is the theoretical boundary where the Sun's solar wind meets interstellar space?", a: "The heliopause", points: 1000, type: "text" }
  ],
  "Art & Literature": [
    { q: "Who painted the Mona Lisa?", a: "Leonardo da Vinci", points: 200, type: "text" },
    { q: "Who wrote the play Romeo and Juliet?", a: "William Shakespeare", points: 200, type: "text" },
    { q: "What boy wizard is the hero of a series by J.K. Rowling?", a: "Harry Potter", points: 200, type: "text" },
    { q: "Who painted the ceiling of the Sistine Chapel?", a: "Michelangelo", points: 200, type: "text" },
    { q: "What Dutch painter created The Starry Night?", a: "Vincent van Gogh", points: 200, type: "text" },
    { q: "Who wrote Oliver Twist and A Christmas Carol?", a: "Charles Dickens", points: 200, type: "text" },
    { q: "What is the title of the first book in the Bible?", a: "Genesis", points: 200, type: "text" },
    { q: "Who wrote the epic poem the Odyssey?", a: "Homer", points: 200, type: "text" },
    { q: "Who wrote the novel Pride and Prejudice?", a: "Jane Austen", points: 400, type: "text" },
    { q: "What Spanish artist co-founded the Cubism movement?", a: "Pablo Picasso", points: 400, type: "text" },
    { q: "Who wrote the dystopian novel Nineteen Eighty-Four?", a: "George Orwell", points: 400, type: "text" },
    { q: "What Russian author wrote War and Peace?", a: "Leo Tolstoy", points: 400, type: "text" },
    { q: "Who sculpted the marble statue The Thinker?", a: "Auguste Rodin", points: 400, type: "text" },
    { q: "Who wrote the novel The Old Man and the Sea?", a: "Ernest Hemingway", points: 400, type: "text" },
    { q: "Which artist is famous for soup-can paintings and pop art?", a: "Andy Warhol", points: 400, type: "text" },
    { q: "Who wrote the tragedy Macbeth?", a: "William Shakespeare", points: 400, type: "text" },
    { q: "Who wrote the novel Crime and Punishment?", a: "Fyodor Dostoevsky", points: 600, type: "text" },
    { q: "What art movement did Salvador Dali belong to?", a: "Surrealism", points: 600, type: "text" },
    { q: "Who wrote the novel One Hundred Years of Solitude?", a: "Gabriel Garcia Marquez", points: 600, type: "text" },
    { q: "What Dutch painter created Girl with a Pearl Earring?", a: "Johannes Vermeer", points: 600, type: "text" },
    { q: "Who wrote the play Waiting for Godot?", a: "Samuel Beckett", points: 600, type: "text" },
    { q: "What Mexican artist is known for self-portraits and her distinctive eyebrows?", a: "Frida Kahlo", points: 600, type: "text" },
    { q: "Who wrote the novel Brave New World?", a: "Aldous Huxley", points: 600, type: "text" },
    { q: "What Norwegian artist painted The Scream?", a: "Edvard Munch", points: 600, type: "text" },
    { q: "Who wrote the modernist novel Ulysses?", a: "James Joyce", points: 800, type: "text" },
    { q: "What Italian Renaissance painter created The Birth of Venus?", a: "Sandro Botticelli", points: 800, type: "text" },
    { q: "Who wrote the poem The Waste Land?", a: "T.S. Eliot", points: 800, type: "text" },
    { q: "What Dutch painter created The Garden of Earthly Delights?", a: "Hieronymus Bosch", points: 800, type: "text" },
    { q: "Who wrote the novel Things Fall Apart?", a: "Chinua Achebe", points: 800, type: "text" },
    { q: "What American artist pioneered drip-style abstract expressionism?", a: "Jackson Pollock", points: 800, type: "text" },
    { q: "Who wrote the novel Madame Bovary?", a: "Gustave Flaubert", points: 800, type: "text" },
    { q: "What Spanish painter created Las Meninas in 1656?", a: "Diego Velazquez", points: 800, type: "text" },
    { q: "Who wrote the novel Invisible Man, published in 1952?", a: "Ralph Ellison", points: 1000, type: "text" },
    { q: "What Flemish painter created the Arnolfini Portrait?", a: "Jan van Eyck", points: 1000, type: "text" },
    { q: "Who wrote the epic poem Paradise Lost?", a: "John Milton", points: 1000, type: "text" },
    { q: "What Italian painter is known for dramatic chiaroscuro in The Calling of St Matthew?", a: "Caravaggio", points: 1000, type: "text" },
    { q: "Who wrote the novel The Master and Margarita?", a: "Mikhail Bulgakov", points: 1000, type: "text" },
    { q: "What Austrian painter created The Kiss in gold leaf?", a: "Gustav Klimt", points: 1000, type: "text" },
    { q: "Who wrote the novel In Search of Lost Time?", a: "Marcel Proust", points: 1000, type: "text" },
    { q: "What German artist created the engraving Melencolia I in 1514?", a: "Albrecht Durer", points: 1000, type: "text" }
  ],
  "Pop Culture": [
    { q: "What superhero is known as the Caped Crusader and protects Gotham City?", a: "Batman", points: 200, type: "text" },
    { q: "What is the name of the wizarding school in Harry Potter?", a: "Hogwarts", points: 200, type: "text" },
    { q: "Which band performed the song Hey Jude?", a: "The Beatles", points: 200, type: "text" },
    { q: "What is the name of the plumber who is Nintendo's mascot?", a: "Mario", points: 200, type: "text" },
    { q: "What singer is known as the King of Pop?", a: "Michael Jackson", points: 200, type: "text" },
    { q: "In Star Wars, who is Luke Skywalker's father?", a: "Darth Vader", points: 200, type: "text" },
    { q: "What yellow sponge lives in a pineapple under the sea?", a: "SpongeBob SquarePants", points: 200, type: "text" },
    { q: "What movie features a great white shark terrorizing a beach town?", a: "Jaws", points: 200, type: "text" },
    { q: "What 1997 film about a sinking ship starred Leonardo DiCaprio and Kate Winslet?", a: "Titanic", points: 400, type: "text" },
    { q: "Which artist released the album Thriller in 1982?", a: "Michael Jackson", points: 400, type: "text" },
    { q: "What is the name of the coffee shop hangout in the sitcom Friends?", a: "Central Perk", points: 400, type: "text" },
    { q: "What video game series features a character named Lara Croft?", a: "Tomb Raider", points: 400, type: "text" },
    { q: "Who directed the films Jurassic Park and E.T.?", a: "Steven Spielberg", points: 400, type: "text" },
    { q: "What Swedish band recorded the hit song Dancing Queen?", a: "ABBA", points: 400, type: "text" },
    { q: "What Japanese film studio created My Neighbor Totoro?", a: "Studio Ghibli", points: 400, type: "text" },
    { q: "In The Lord of the Rings, what creature is obsessed with the One Ring and calls it 'precious'?", a: "Gollum", points: 400, type: "text" },
    { q: "Who played the lead role in the 1994 film Forrest Gump?", a: "Tom Hanks", points: 600, type: "text" },
    { q: "What is the name of the fictional African nation in Black Panther?", a: "Wakanda", points: 600, type: "text" },
    { q: "Which British band released the album The Dark Side of the Moon?", a: "Pink Floyd", points: 600, type: "text" },
    { q: "What video game franchise features collectible creatures like Pikachu?", a: "Pokemon", points: 600, type: "text" },
    { q: "Who directed the 1994 film Pulp Fiction?", a: "Quentin Tarantino", points: 600, type: "text" },
    { q: "Which singer released the album 1989 and the song Shake It Off?", a: "Taylor Swift", points: 600, type: "text" },
    { q: "In The Matrix, what color pill does Neo take to learn the truth?", a: "Red", points: 600, type: "text" },
    { q: "What HBO series is based on George R.R. Martin's A Song of Ice and Fire?", a: "Game of Thrones", points: 600, type: "text" },
    { q: "Who composed the iconic two-note theme for the movie Jaws?", a: "John Williams", points: 800, type: "text" },
    { q: "What was the first feature-length animated film released by Walt Disney in 1937?", a: "Snow White and the Seven Dwarfs", points: 800, type: "text" },
    { q: "Who was the lead singer and songwriter of Nirvana?", a: "Kurt Cobain", points: 800, type: "text" },
    { q: "What 1998 video game popularized stealth gameplay with Solid Snake?", a: "Metal Gear Solid", points: 800, type: "text" },
    { q: "Who directed the 2001 film Mulholland Drive?", a: "David Lynch", points: 800, type: "text" },
    { q: "What jazz trumpeter recorded the 1959 album Kind of Blue?", a: "Miles Davis", points: 800, type: "text" },
    { q: "What Japanese director made the 1954 film Seven Samurai?", a: "Akira Kurosawa", points: 800, type: "text" },
    { q: "In Breaking Bad, what is chemistry teacher Walter White's street alias?", a: "Heisenberg", points: 800, type: "text" },
    { q: "Who directed the 1966 spaghetti western The Good, the Bad and the Ugly?", a: "Sergio Leone", points: 1000, type: "text" },
    { q: "What German electronic band released the influential 1974 album Autobahn?", a: "Kraftwerk", points: 1000, type: "text" },
    { q: "Who created the manga and anime film Akira?", a: "Katsuhiro Otomo", points: 1000, type: "text" },
    { q: "Which silent-film comedian is famous for The Gold Rush and The Tramp character?", a: "Charlie Chaplin", points: 1000, type: "text" },
    { q: "Which Motown group recorded the 1966 hit Reach Out I'll Be There?", a: "The Four Tops", points: 1000, type: "text" },
    { q: "What 1985 Nintendo game is credited with reviving the console industry after the 1983 crash?", a: "Super Mario Bros.", points: 1000, type: "text" },
    { q: "Who directed the 1948 Italian neorealist film Bicycle Thieves?", a: "Vittorio De Sica", points: 1000, type: "text" },
    { q: "What 1927 film is often cited as the first feature with synchronized dialogue?", a: "The Jazz Singer", points: 1000, type: "text" }
  ],
  "Famous Landmarks": [
    { q: "In which city is the Eiffel Tower located?", a: "Paris", points: 200, type: "text" },
    { q: "What ancient amphitheater is a famous landmark in Rome?", a: "The Colosseum", points: 200, type: "text" },
    { q: "What large green statue stands in New York Harbor?", a: "Statue of Liberty", points: 200, type: "text" },
    { q: "In which country would you find the Great Wall?", a: "China", points: 200, type: "text" },
    { q: "What famous clock tower stands beside the Houses of Parliament in London?", a: "Big Ben", points: 200, type: "text" },
    { q: "What pyramids stand near Cairo, Egypt?", a: "The Pyramids of Giza", points: 200, type: "text" },
    { q: "What white marble mausoleum is located in Agra, India?", a: "Taj Mahal", points: 200, type: "text" },
    { q: "What leaning tower is a famous landmark in Italy?", a: "Leaning Tower of Pisa", points: 200, type: "text" },
    { q: "On which continent is the ancient Inca city of Machu Picchu located?", a: "South America", points: 400, type: "text" },
    { q: "In which Australian city is the famous Opera House located?", a: "Sydney", points: 400, type: "text" },
    { q: "What prehistoric ring of standing stones is located in England?", a: "Stonehenge", points: 400, type: "text" },
    { q: "In which US state is the Grand Canyon located?", a: "Arizona", points: 400, type: "text" },
    { q: "What large statue of Jesus overlooks Rio de Janeiro?", a: "Christ the Redeemer", points: 400, type: "text" },
    { q: "What ancient temple sits atop the Acropolis in Athens?", a: "The Parthenon", points: 400, type: "text" },
    { q: "In which country is the rock-cut city of Petra located?", a: "Jordan", points: 400, type: "text" },
    { q: "What tall orange-and-white tower in Tokyo resembles the Eiffel Tower?", a: "Tokyo Tower", points: 400, type: "text" },
    { q: "In which country is the temple complex of Angkor Wat located?", a: "Cambodia", points: 600, type: "text" },
    { q: "What palace in Granada, Spain, is a famous example of Moorish architecture?", a: "The Alhambra", points: 600, type: "text" },
    { q: "What building in Dubai is currently the tallest in the world?", a: "Burj Khalifa", points: 600, type: "text" },
    { q: "In which city is the Brandenburg Gate located?", a: "Berlin", points: 600, type: "text" },
    { q: "What domed building in Istanbul was originally a Byzantine church?", a: "Hagia Sophia", points: 600, type: "text" },
    { q: "The Moai head statues are found on which island, a territory of Chile?", a: "Easter Island", points: 600, type: "text" },
    { q: "What Russian cathedral with colorful onion domes sits on Red Square?", a: "Saint Basil's Cathedral", points: 600, type: "text" },
    { q: "What unfinished basilica in Barcelona was designed by Antoni Gaudi?", a: "Sagrada Familia", points: 600, type: "text" },
    { q: "In which Egyptian city did the ancient lighthouse, one of the Seven Wonders, stand?", a: "Alexandria", points: 800, type: "text" },
    { q: "On which Indonesian island is the temple of Borobudur located?", a: "Java", points: 800, type: "text" },
    { q: "In which Italian city is the Doge's Palace located?", a: "Venice", points: 800, type: "text" },
    { q: "What is the name of the famous treasury facade carved into the rock at Petra?", a: "Al-Khazneh", points: 800, type: "text" },
    { q: "In which African country are the rock-hewn churches of Lalibela located?", a: "Ethiopia", points: 800, type: "text" },
    { q: "What palace near Paris was the principal royal residence of Louis XIV?", a: "Palace of Versailles", points: 800, type: "text" },
    { q: "What stepped pyramid named El Castillo is the centerpiece of Chichen Itza?", a: "El Castillo", points: 800, type: "text" },
    { q: "What 12th-century French Gothic cathedral was damaged by fire in 2019?", a: "Notre-Dame de Paris", points: 800, type: "text" },
    { q: "What ancient ziggurat is located near Nasiriyah in modern Iraq?", a: "Ziggurat of Ur", points: 1000, type: "text" },
    { q: "In which Thai city is the temple of the Reclining Buddha, Wat Pho, located?", a: "Bangkok", points: 1000, type: "text" },
    { q: "What megalithic temple complex in Turkey dates to around 9500 BCE?", a: "Gobekli Tepe", points: 1000, type: "text" },
    { q: "What ancient city in present-day Syria was a wealthy caravan hub famed for its colonnade?", a: "Palmyra", points: 1000, type: "text" },
    { q: "What ruined Mesoamerican city north of Mexico City contains the Pyramid of the Sun?", a: "Teotihuacan", points: 1000, type: "text" },
    { q: "In which Chinese city was the Terracotta Army discovered?", a: "Xi'an", points: 1000, type: "text" },
    { q: "What former palace of the Dalai Lama towers over Lhasa, Tibet?", a: "The Potala Palace", points: 1000, type: "text" },
    { q: "What Greek monasteries are perched atop towering rock pillars?", a: "Meteora", points: 1000, type: "text" }
  ]
};
