// Curated, direct question-and-answer trivia (clean, well-known, English).
// 15 broad themes, 30 questions each (6 per point tier; difficulty rises with value).
const REAL_CATEGORIES = {
  "General Knowledge": [
    { q: "Which planet in our solar system is known as the Red Planet?", a: "Mars", points: 200, type: "text" },
    { q: "What is the largest ocean on Earth?", a: "Pacific Ocean", points: 200, type: "text" },
    { q: "How many days are there in a leap year?", a: "366", points: 200, type: "text" },
    { q: "What is the chemical symbol for water?", a: "H2O", points: 200, type: "text" },
    { q: "What color do you get when you mix blue and yellow?", a: "Green", points: 200, type: "text" },
    { q: "How many sides does a triangle have?", a: "Three", points: 200, type: "text" },
    { q: "Which gas do plants absorb from the air for photosynthesis?", a: "Carbon dioxide", points: 400, type: "text" },
    { q: "What is the tallest mountain in the world?", a: "Mount Everest", points: 400, type: "text" },
    { q: "Who wrote the play Romeo and Juliet?", a: "William Shakespeare", points: 400, type: "text" },
    { q: "What is the capital city of Japan?", a: "Tokyo", points: 400, type: "text" },
    { q: "How many continents are there on Earth?", a: "Seven", points: 400, type: "text" },
    { q: "What is the hardest natural substance on Earth?", a: "Diamond", points: 400, type: "text" },
    { q: "Which famous scientist developed the theory of general relativity?", a: "Albert Einstein", points: 600, type: "text" },
    { q: "What is the largest internal organ in the human body?", a: "The liver", points: 600, type: "text" },
    { q: "Which artist painted the ceiling of the Sistine Chapel?", a: "Michelangelo", points: 600, type: "text" },
    { q: "What is the longest river in the world?", a: "The Nile", points: 600, type: "text" },
    { q: "What is the chemical symbol for gold?", a: "Au", points: 600, type: "text" },
    { q: "Which country gifted the Statue of Liberty to the United States?", a: "France", points: 600, type: "text" },
    { q: "What is the smallest prime number?", a: "2", points: 800, type: "text" },
    { q: "Who composed the Ninth Symphony, which includes the Ode to Joy?", a: "Ludwig van Beethoven", points: 800, type: "text" },
    { q: "What is the largest planet in our solar system?", a: "Jupiter", points: 800, type: "text" },
    { q: "Which element has the atomic number 1?", a: "Hydrogen", points: 800, type: "text" },
    { q: "In which year did the Berlin Wall fall?", a: "1989", points: 800, type: "text" },
    { q: "What is the currency used in Switzerland?", a: "Swiss franc", points: 800, type: "text" },
    { q: "What is the most abundant gas in Earth's atmosphere?", a: "Nitrogen", points: 1000, type: "text" },
    { q: "Who wrote the novel One Hundred Years of Solitude?", a: "Gabriel Garcia Marquez", points: 1000, type: "text" },
    { q: "Approximately how fast does light travel in a vacuum, in kilometers per second?", a: "About 300,000 km/s", points: 1000, type: "text" },
    { q: "Which Italian explorer reached the Americas in 1492?", a: "Christopher Columbus", points: 1000, type: "text" },
    { q: "What is the name of the galaxy that contains our solar system?", a: "The Milky Way", points: 1000, type: "text" },
    { q: "Which mathematician is known as the father of geometry?", a: "Euclid", points: 1000, type: "text" }
  ],
  "Sports": [
    { q: "How many players are on a soccer team on the field at one time?", a: "Eleven", points: 200, type: "text" },
    { q: "In which sport would you use a racket to hit a shuttlecock?", a: "Badminton", points: 200, type: "text" },
    { q: "How many points is a touchdown worth in American football?", a: "Six", points: 200, type: "text" },
    { q: "What sport is played at Wimbledon?", a: "Tennis", points: 200, type: "text" },
    { q: "How many rings are on the Olympic flag?", a: "Five", points: 200, type: "text" },
    { q: "In basketball, how many points is a free throw worth?", a: "One", points: 200, type: "text" },
    { q: "Which country hosts the famous Tour de France cycling race?", a: "France", points: 400, type: "text" },
    { q: "How often are the Summer Olympic Games held?", a: "Every four years", points: 400, type: "text" },
    { q: "In which sport is the term love used to mean a score of zero?", a: "Tennis", points: 400, type: "text" },
    { q: "What is the maximum number of clubs a golfer can carry during a round?", a: "Fourteen", points: 400, type: "text" },
    { q: "In which sport do teams compete for the Stanley Cup?", a: "Ice hockey", points: 400, type: "text" },
    { q: "How many players are on a basketball team on the court at one time?", a: "Five", points: 400, type: "text" },
    { q: "Which sport is associated with the term home run?", a: "Baseball", points: 600, type: "text" },
    { q: "In what country did the martial art of judo originate?", a: "Japan", points: 600, type: "text" },
    { q: "How long is a marathon, in miles, rounded to the nearest mile?", a: "About 26 miles", points: 600, type: "text" },
    { q: "Which sport features positions called goalkeeper, defender, and striker?", a: "Soccer", points: 600, type: "text" },
    { q: "What is the national summer sport of Canada?", a: "Lacrosse", points: 600, type: "text" },
    { q: "In boxing, how many minutes is a standard professional round?", a: "Three minutes", points: 600, type: "text" },
    { q: "Which country has won the most FIFA World Cup titles in men's soccer?", a: "Brazil", points: 800, type: "text" },
    { q: "In which sport would you perform a slam dunk?", a: "Basketball", points: 800, type: "text" },
    { q: "What is the term for three strikes in a row in bowling?", a: "A turkey", points: 800, type: "text" },
    { q: "Which Grand Slam tennis tournament is played on clay courts?", a: "The French Open", points: 800, type: "text" },
    { q: "In Formula One racing, what flag signals the end of a race?", a: "The checkered flag", points: 800, type: "text" },
    { q: "How many players are on a volleyball team on the court at one time?", a: "Six", points: 800, type: "text" },
    { q: "In which city were the first modern Olympic Games held in 1896?", a: "Athens", points: 1000, type: "text" },
    { q: "What is the diameter of a basketball hoop, in inches?", a: "Eighteen inches", points: 1000, type: "text" },
    { q: "Which sport uses terms such as scrum, try, and lineout?", a: "Rugby", points: 1000, type: "text" },
    { q: "In golf, what term describes a score of two under par on a single hole?", a: "An eagle", points: 1000, type: "text" },
    { q: "How many players are on a cricket team?", a: "Eleven", points: 1000, type: "text" },
    { q: "Which country popularized table tennis as a parlor game in the late 1800s?", a: "England", points: 1000, type: "text" }
  ],
  "History": [
    { q: "Who was the first President of the United States?", a: "George Washington", points: 200, type: "text" },
    { q: "In which country were the ancient pyramids of Giza built?", a: "Egypt", points: 200, type: "text" },
    { q: "What ancient civilization built the Colosseum?", a: "The Romans", points: 200, type: "text" },
    { q: "Who was the famous queen of ancient Egypt linked with Julius Caesar?", a: "Cleopatra", points: 200, type: "text" },
    { q: "On which continent did the ancient Maya civilization develop?", a: "North America", points: 200, type: "text" },
    { q: "What wall was built to protect ancient China from invaders?", a: "The Great Wall of China", points: 200, type: "text" },
    { q: "In which year did World War II end?", a: "1945", points: 400, type: "text" },
    { q: "Who was the British Prime Minister during most of World War II?", a: "Winston Churchill", points: 400, type: "text" },
    { q: "Which ship famously sank in 1912 after hitting an iceberg?", a: "The Titanic", points: 400, type: "text" },
    { q: "Who led India to independence through nonviolent resistance?", a: "Mahatma Gandhi", points: 400, type: "text" },
    { q: "Which empire was ruled by Julius Caesar?", a: "The Roman Empire", points: 400, type: "text" },
    { q: "Who delivered the I Have a Dream speech in 1963?", a: "Martin Luther King Jr.", points: 400, type: "text" },
    { q: "In which year did the United States declare its independence?", a: "1776", points: 600, type: "text" },
    { q: "Which French military leader was defeated at the Battle of Waterloo?", a: "Napoleon Bonaparte", points: 600, type: "text" },
    { q: "What was the name of the cultural rebirth in Europe that began in Italy?", a: "The Renaissance", points: 600, type: "text" },
    { q: "Who was the first man to walk on the Moon?", a: "Neil Armstrong", points: 600, type: "text" },
    { q: "Which civilization is credited with developing democracy in Athens?", a: "Ancient Greece", points: 600, type: "text" },
    { q: "Which explorer's crew first sailed all the way around the world?", a: "Ferdinand Magellan", points: 600, type: "text" },
    { q: "In which year did World War I begin?", a: "1914", points: 800, type: "text" },
    { q: "Who was the longest-reigning British queen before Elizabeth II?", a: "Queen Victoria", points: 800, type: "text" },
    { q: "Which document, signed in 1215, limited the power of the English king?", a: "The Magna Carta", points: 800, type: "text" },
    { q: "Which ancient wonder stood in the city of Alexandria as a lighthouse?", a: "The Lighthouse of Alexandria", points: 800, type: "text" },
    { q: "Which war was fought between the North and South in the US from 1861 to 1865?", a: "The American Civil War", points: 800, type: "text" },
    { q: "Which Italian city was buried by the eruption of Mount Vesuvius in 79 AD?", a: "Pompeii", points: 800, type: "text" },
    { q: "Who was the Macedonian king that built one of the largest ancient empires by 323 BC?", a: "Alexander the Great", points: 1000, type: "text" },
    { q: "Which treaty, signed in 1919, formally ended World War I?", a: "The Treaty of Versailles", points: 1000, type: "text" },
    { q: "Which dynasty built much of the Forbidden City in China?", a: "The Ming dynasty", points: 1000, type: "text" },
    { q: "Who was the first emperor of Rome?", a: "Augustus", points: 1000, type: "text" },
    { q: "Which revolution began in 1789 and ended the monarchy in France?", a: "The French Revolution", points: 1000, type: "text" },
    { q: "Which civilization built the mountain city of Machu Picchu?", a: "The Inca", points: 1000, type: "text" }
  ],
  "Geography": [
    { q: "What is the capital of France?", a: "Paris", points: 200, type: "text" },
    { q: "What is the largest ocean on Earth?", a: "Pacific Ocean", points: 200, type: "text" },
    { q: "On which continent is Egypt located?", a: "Africa", points: 200, type: "text" },
    { q: "What is the capital of Japan?", a: "Tokyo", points: 200, type: "text" },
    { q: "What is the longest river in the world?", a: "The Nile", points: 200, type: "text" },
    { q: "Which country's flag is this?", a: "Italy", points: 200, type: "image", emoji: "🇮🇹" },
    { q: "What is the capital of Canada?", a: "Ottawa", points: 400, type: "text" },
    { q: "What is the tallest mountain in the world?", a: "Mount Everest", points: 400, type: "text" },
    { q: "Which country is the largest in the world by area?", a: "Russia", points: 400, type: "text" },
    { q: "What is the capital of Australia?", a: "Canberra", points: 400, type: "text" },
    { q: "Which desert is the largest hot desert in the world?", a: "The Sahara", points: 400, type: "text" },
    { q: "Which country's flag is this?", a: "Brazil", points: 400, type: "image", emoji: "🇧🇷" },
    { q: "What is the capital of Brazil?", a: "Brasilia", points: 600, type: "text" },
    { q: "Which mountain range separates Europe from Asia?", a: "The Ural Mountains", points: 600, type: "text" },
    { q: "What is the smallest country in the world by area?", a: "Vatican City", points: 600, type: "text" },
    { q: "Which African country was formerly known as Abyssinia?", a: "Ethiopia", points: 600, type: "text" },
    { q: "What is the capital of South Korea?", a: "Seoul", points: 600, type: "text" },
    { q: "Which country's flag is this?", a: "Sweden", points: 600, type: "image", emoji: "🇸🇪" },
    { q: "What is the capital of Argentina?", a: "Buenos Aires", points: 800, type: "text" },
    { q: "Which is the largest island in the world?", a: "Greenland", points: 800, type: "text" },
    { q: "What is the capital of Egypt?", a: "Cairo", points: 800, type: "text" },
    { q: "What is the deepest ocean trench in the world?", a: "The Mariana Trench", points: 800, type: "text" },
    { q: "Which strait separates Europe from Africa at its narrowest point?", a: "The Strait of Gibraltar", points: 800, type: "text" },
    { q: "Which country's flag is this?", a: "South Korea", points: 800, type: "image", emoji: "🇰🇷" },
    { q: "What is the capital of New Zealand?", a: "Wellington", points: 1000, type: "text" },
    { q: "Which country has the most natural lakes in the world?", a: "Canada", points: 1000, type: "text" },
    { q: "What is the capital of Kazakhstan?", a: "Astana", points: 1000, type: "text" },
    { q: "Lake Titicaca lies on the border of Peru and which other country?", a: "Bolivia", points: 1000, type: "text" },
    { q: "What is the highest waterfall in the world?", a: "Angel Falls", points: 1000, type: "text" },
    { q: "Which country's flag is this?", a: "Turkey", points: 1000, type: "image", emoji: "🇹🇷" }
  ],
  "Movies & TV": [
    { q: "Who directed the movie Jurassic Park?", a: "Steven Spielberg", points: 200, type: "text" },
    { q: "In which movie does the character Simba appear?", a: "The Lion King", points: 200, type: "text" },
    { q: "What kind of animal is Nemo in Finding Nemo?", a: "A clownfish", points: 200, type: "text" },
    { q: "Who played Captain Jack Sparrow in Pirates of the Caribbean?", a: "Johnny Depp", points: 200, type: "text" },
    { q: "In the Harry Potter films, what is the name of Harry's pet owl?", a: "Hedwig", points: 200, type: "text" },
    { q: "What is the name of the toy cowboy in Toy Story?", a: "Woody", points: 200, type: "text" },
    { q: "Who directed the movie Titanic?", a: "James Cameron", points: 400, type: "text" },
    { q: "Which actor played Iron Man in the Marvel films?", a: "Robert Downey Jr.", points: 400, type: "text" },
    { q: "In which fictional African country is Black Panther set?", a: "Wakanda", points: 400, type: "text" },
    { q: "What is the name of the coffee shop in the TV show Friends?", a: "Central Perk", points: 400, type: "text" },
    { q: "Who voiced the genie in Disney's 1992 film Aladdin?", a: "Robin Williams", points: 400, type: "text" },
    { q: "Which movie features the song My Heart Will Go On?", a: "Titanic", points: 400, type: "text" },
    { q: "Who directed the movie Pulp Fiction?", a: "Quentin Tarantino", points: 600, type: "text" },
    { q: "In The Matrix, which colored pill does Neo take?", a: "The red pill", points: 600, type: "text" },
    { q: "What is the name of the kingdom in the movie Frozen?", a: "Arendelle", points: 600, type: "text" },
    { q: "Who played the Joker in the 2008 film The Dark Knight?", a: "Heath Ledger", points: 600, type: "text" },
    { q: "Which TV series features the Stark and Lannister families?", a: "Game of Thrones", points: 600, type: "text" },
    { q: "Who directed the original 1977 Star Wars film?", a: "George Lucas", points: 600, type: "text" },
    { q: "Which 1994 film stars Tom Hanks recounting his life from a park bench?", a: "Forrest Gump", points: 800, type: "text" },
    { q: "What is the name of the ship in the movie Alien?", a: "The Nostromo", points: 800, type: "text" },
    { q: "Who directed the films Inception and Interstellar?", a: "Christopher Nolan", points: 800, type: "text" },
    { q: "In Breaking Bad, what is chemistry teacher Walter White's alias?", a: "Heisenberg", points: 800, type: "text" },
    { q: "Which 1939 film features the line about there being no place like home?", a: "The Wizard of Oz", points: 800, type: "text" },
    { q: "Which studio created the films Toy Story and Finding Nemo?", a: "Pixar", points: 800, type: "text" },
    { q: "Which 1972 film by Francis Ford Coppola follows the Corleone family?", a: "The Godfather", points: 1000, type: "text" },
    { q: "Who directed the 2019 film Parasite?", a: "Bong Joon-ho", points: 1000, type: "text" },
    { q: "In the film Casablanca, what is the name of the cafe owned by Rick?", a: "Rick's Cafe Americain", points: 1000, type: "text" },
    { q: "Which actress played Clarice Starling in The Silence of the Lambs?", a: "Jodie Foster", points: 1000, type: "text" },
    { q: "Who directed the 1960 thriller Psycho?", a: "Alfred Hitchcock", points: 1000, type: "text" },
    { q: "Which Japanese animation studio produced the film Spirited Away?", a: "Studio Ghibli", points: 1000, type: "text" }
  ],
  "Music & Songs": [
    { q: "Which British band recorded the album Abbey Road?", a: "The Beatles", points: 200, type: "text" },
    { q: "Which singer is known as the King of Pop?", a: "Michael Jackson", points: 200, type: "text" },
    { q: "What instrument has 88 keys?", a: "The piano", points: 200, type: "text" },
    { q: "Which singer released the album 21 and the song Rolling in the Deep?", a: "Adele", points: 200, type: "text" },
    { q: "Which instrument did Louis Armstrong famously play?", a: "The trumpet", points: 200, type: "text" },
    { q: "Which band performed the song Bohemian Rhapsody?", a: "Queen", points: 200, type: "text" },
    { q: "Who is known as the Queen of Pop and sang Like a Virgin?", a: "Madonna", points: 400, type: "text" },
    { q: "How many strings does a standard guitar have?", a: "Six", points: 400, type: "text" },
    { q: "Who was the lead vocalist of the band Queen?", a: "Freddie Mercury", points: 400, type: "text" },
    { q: "Which American singer is known as the King of Rock and Roll?", a: "Elvis Presley", points: 400, type: "text" },
    { q: "Which Swedish group sang Dancing Queen and Mamma Mia?", a: "ABBA", points: 400, type: "text" },
    { q: "Which Jamaican musician is famous for the song No Woman, No Cry?", a: "Bob Marley", points: 400, type: "text" },
    { q: "Which composer wrote the Ninth Symphony, also known as the Ode to Joy?", a: "Ludwig van Beethoven", points: 600, type: "text" },
    { q: "Which band released the album The Dark Side of the Moon?", a: "Pink Floyd", points: 600, type: "text" },
    { q: "Which singer recorded the album Thriller?", a: "Michael Jackson", points: 600, type: "text" },
    { q: "Which American singer is nicknamed Ol' Blue Eyes and sang My Way?", a: "Frank Sinatra", points: 600, type: "text" },
    { q: "Which family group from Gary, Indiana, launched Michael Jackson's career?", a: "The Jackson 5", points: 600, type: "text" },
    { q: "Which Italian musical term means to play loudly?", a: "Forte", points: 600, type: "text" },
    { q: "Which composer wrote The Four Seasons?", a: "Antonio Vivaldi", points: 800, type: "text" },
    { q: "Which band performed the song Stairway to Heaven?", a: "Led Zeppelin", points: 800, type: "text" },
    { q: "Which American singer released the 1971 album Tapestry?", a: "Carole King", points: 800, type: "text" },
    { q: "How many lines are there on a standard musical staff?", a: "Five", points: 800, type: "text" },
    { q: "Which Austrian composer wrote the opera The Magic Flute?", a: "Wolfgang Amadeus Mozart", points: 800, type: "text" },
    { q: "Which singer was a pioneer of soul music and recorded What'd I Say?", a: "Ray Charles", points: 800, type: "text" },
    { q: "Which Russian composer wrote the ballets Swan Lake and The Nutcracker?", a: "Pyotr Ilyich Tchaikovsky", points: 1000, type: "text" },
    { q: "Which jazz trumpeter recorded the album Kind of Blue?", a: "Miles Davis", points: 1000, type: "text" },
    { q: "Which German composer wrote the Brandenburg Concertos?", a: "Johann Sebastian Bach", points: 1000, type: "text" },
    { q: "Which American jazz singer was known as Lady Day?", a: "Billie Holiday", points: 1000, type: "text" },
    { q: "How many musicians make up a string quartet?", a: "Four", points: 1000, type: "text" },
    { q: "Which Polish composer is famous for his piano nocturnes?", a: "Frederic Chopin", points: 1000, type: "text" }
  ],
  "Science": [
    { q: "What gas do plants absorb from the air for photosynthesis?", a: "Carbon dioxide", points: 200, type: "text" },
    { q: "What is the closest planet to the Sun?", a: "Mercury", points: 200, type: "text" },
    { q: "What is the chemical symbol for water?", a: "H2O", points: 200, type: "text" },
    { q: "What organ pumps blood through the human body?", a: "The heart", points: 200, type: "text" },
    { q: "What force pulls objects toward the center of the Earth?", a: "Gravity", points: 200, type: "text" },
    { q: "What is the center of an atom called?", a: "The nucleus", points: 200, type: "text" },
    { q: "What gas do humans need to breathe in to survive?", a: "Oxygen", points: 400, type: "text" },
    { q: "What is the hardest known natural substance on Earth?", a: "Diamond", points: 400, type: "text" },
    { q: "What planet is known as the Red Planet?", a: "Mars", points: 400, type: "text" },
    { q: "What is the freezing point of water in degrees Celsius?", a: "Zero degrees", points: 400, type: "text" },
    { q: "What part of the human body contains the cochlea?", a: "The ear", points: 400, type: "text" },
    { q: "What is the most abundant gas in Earth's atmosphere?", a: "Nitrogen", points: 400, type: "text" },
    { q: "What is the chemical symbol for gold?", a: "Au", points: 600, type: "text" },
    { q: "What type of energy is stored in food?", a: "Chemical energy", points: 600, type: "text" },
    { q: "What is the powerhouse of the cell?", a: "The mitochondria", points: 600, type: "text" },
    { q: "Which scientist proposed the theory of general relativity?", a: "Albert Einstein", points: 600, type: "text" },
    { q: "What is the largest planet in our solar system?", a: "Jupiter", points: 600, type: "text" },
    { q: "What is the process by which a liquid turns into a gas called?", a: "Evaporation", points: 600, type: "text" },
    { q: "What blood type is known as the universal donor?", a: "O negative", points: 800, type: "text" },
    { q: "What is the atomic number of carbon?", a: "Six", points: 800, type: "text" },
    { q: "Which scientist developed the laws of motion and universal gravitation?", a: "Isaac Newton", points: 800, type: "text" },
    { q: "What is the term for an animal that eats only plants?", a: "Herbivore", points: 800, type: "text" },
    { q: "What gas do plants release as a byproduct of photosynthesis?", a: "Oxygen", points: 800, type: "text" },
    { q: "What is the SI unit of electric current?", a: "The ampere", points: 800, type: "text" },
    { q: "What is the lightest element on the periodic table?", a: "Hydrogen", points: 1000, type: "text" },
    { q: "Which scientist is credited with discovering penicillin?", a: "Alexander Fleming", points: 1000, type: "text" },
    { q: "What is the term for the bending of light as it passes through a medium?", a: "Refraction", points: 1000, type: "text" },
    { q: "What is the pH value of a neutral solution at room temperature?", a: "Seven", points: 1000, type: "text" },
    { q: "What molecule carries genetic information in living things?", a: "DNA", points: 1000, type: "text" },
    { q: "What is the study of living organisms called?", a: "Biology", points: 1000, type: "text" }
  ],
  "Animals & Nature": [
    { q: "What is the largest land animal on Earth?", a: "The African elephant", points: 200, type: "text" },
    { q: "What is the tallest animal in the world?", a: "The giraffe", points: 200, type: "text" },
    { q: "What animal is known as the king of the jungle?", a: "The lion", points: 200, type: "text" },
    { q: "How many legs does a spider have?", a: "Eight", points: 200, type: "text" },
    { q: "What do bees collect from flowers to make honey?", a: "Nectar", points: 200, type: "text" },
    { q: "What is a baby dog called?", a: "A puppy", points: 200, type: "text" },
    { q: "What is the largest animal ever known to have lived?", a: "The blue whale", points: 400, type: "text" },
    { q: "What is the fastest land animal in the world?", a: "The cheetah", points: 400, type: "text" },
    { q: "What is the only mammal capable of true flight?", a: "The bat", points: 400, type: "text" },
    { q: "What do you call an animal that is active at night?", a: "Nocturnal", points: 400, type: "text" },
    { q: "What is the largest species of bear?", a: "The polar bear", points: 400, type: "text" },
    { q: "What part of a plant absorbs water and nutrients from the soil?", a: "The roots", points: 400, type: "text" },
    { q: "What is a group of lions called?", a: "A pride", points: 600, type: "text" },
    { q: "What is the largest type of penguin?", a: "The emperor penguin", points: 600, type: "text" },
    { q: "What is the process by which caterpillars transform into butterflies called?", a: "Metamorphosis", points: 600, type: "text" },
    { q: "On which continent can you find wild kangaroos?", a: "Australia", points: 600, type: "text" },
    { q: "What is the largest living species of reptile?", a: "The saltwater crocodile", points: 600, type: "text" },
    { q: "What gas do trees mainly take in from the air?", a: "Carbon dioxide", points: 600, type: "text" },
    { q: "What is the term for animals that eat both plants and meat?", a: "Omnivore", points: 800, type: "text" },
    { q: "What is the largest bird in the world by height and weight?", a: "The ostrich", points: 800, type: "text" },
    { q: "What is the name for the seasonal movement of animals between regions?", a: "Migration", points: 800, type: "text" },
    { q: "What is a group of wolves called?", a: "A pack", points: 800, type: "text" },
    { q: "Along with the echidna, which mammal lays eggs?", a: "The platypus", points: 800, type: "text" },
    { q: "Which ocean is home to the Great Barrier Reef?", a: "The Pacific Ocean", points: 800, type: "text" },
    { q: "What is the largest rainforest in the world?", a: "The Amazon rainforest", points: 1000, type: "text" },
    { q: "What is the study of birds called?", a: "Ornithology", points: 1000, type: "text" },
    { q: "Which big cat cannot fully retract its claws?", a: "The cheetah", points: 1000, type: "text" },
    { q: "What is the term for a species that lives in only one specific region?", a: "Endemic", points: 1000, type: "text" },
    { q: "What is the largest species of fish?", a: "The whale shark", points: 1000, type: "text" },
    { q: "What is the name of the layer of gases surrounding the Earth?", a: "The atmosphere", points: 1000, type: "text" }
  ],
  "Food & Drink": [
    { q: "What fruit is traditionally used to make wine?", a: "Grapes", points: 200, type: "text" },
    { q: "What is the main ingredient in guacamole?", a: "Avocado", points: 200, type: "text" },
    { q: "What hot drink is made from roasted beans?", a: "Coffee", points: 200, type: "text" },
    { q: "What vegetable is the main ingredient in french fries?", a: "Potato", points: 200, type: "text" },
    { q: "What dairy product is churned to make butter?", a: "Cream", points: 200, type: "text" },
    { q: "What yellow fruit do monkeys famously eat?", a: "Banana", points: 200, type: "text" },
    { q: "Which country is famous for inventing pizza?", a: "Italy", points: 400, type: "text" },
    { q: "What spice is the most expensive in the world by weight?", a: "Saffron", points: 400, type: "text" },
    { q: "What grain is the main ingredient in sushi?", a: "Rice", points: 400, type: "text" },
    { q: "What is the main ingredient in traditional hummus?", a: "Chickpeas", points: 400, type: "text" },
    { q: "What bean is chocolate made from?", a: "The cacao bean", points: 400, type: "text" },
    { q: "What leafy herb is the main ingredient in pesto sauce?", a: "Basil", points: 400, type: "text" },
    { q: "What fermented soybean paste is a staple of Japanese cuisine?", a: "Miso", points: 600, type: "text" },
    { q: "Which country is the origin of the dish paella?", a: "Spain", points: 600, type: "text" },
    { q: "What citrus fruit is used to make traditional marmalade?", a: "Orange", points: 600, type: "text" },
    { q: "What is the process of preserving food in vinegar or brine called?", a: "Pickling", points: 600, type: "text" },
    { q: "What is the main ingredient in traditional risotto?", a: "Rice", points: 600, type: "text" },
    { q: "Which country is famous for the soft cheese called Brie?", a: "France", points: 600, type: "text" },
    { q: "What leavening agent makes bread dough rise?", a: "Yeast", points: 800, type: "text" },
    { q: "Which country is the origin of the dish sushi?", a: "Japan", points: 800, type: "text" },
    { q: "What is the French term for preparing ingredients before cooking?", a: "Mise en place", points: 800, type: "text" },
    { q: "What is the main alcoholic ingredient in a traditional mojito?", a: "Rum", points: 800, type: "text" },
    { q: "What nut is used to make traditional marzipan?", a: "Almond", points: 800, type: "text" },
    { q: "What spice, harvested from a crocus flower, is famous for its red threads?", a: "Saffron", points: 800, type: "text" },
    { q: "What acid gives lemons and limes their sour taste?", a: "Citric acid", points: 1000, type: "text" },
    { q: "Which country is the origin of the cheese known as feta?", a: "Greece", points: 1000, type: "text" },
    { q: "What is the savory fifth basic taste, alongside sweet, sour, salty, and bitter?", a: "Umami", points: 1000, type: "text" },
    { q: "Which plant is the source of natural vanilla flavoring?", a: "The vanilla orchid", points: 1000, type: "text" },
    { q: "What is the main ingredient in the Japanese rice wine called sake?", a: "Rice", points: 1000, type: "text" },
    { q: "Which Italian dessert's name translates to 'pick me up'?", a: "Tiramisu", points: 1000, type: "text" }
  ],
  "Famous People": [
    { q: "Who was the first person to walk on the Moon?", a: "Neil Armstrong", points: 200, type: "text" },
    { q: "Which artist painted the Mona Lisa?", a: "Leonardo da Vinci", points: 200, type: "text" },
    { q: "Who wrote the play Romeo and Juliet?", a: "William Shakespeare", points: 200, type: "text" },
    { q: "Which scientist developed the theory of relativity?", a: "Albert Einstein", points: 200, type: "text" },
    { q: "Who was the first President of the United States?", a: "George Washington", points: 200, type: "text" },
    { q: "Which leader ended apartheid and became President of South Africa?", a: "Nelson Mandela", points: 200, type: "text" },
    { q: "Which nurse is considered the founder of modern nursing?", a: "Florence Nightingale", points: 400, type: "text" },
    { q: "Who painted the ceiling of the Sistine Chapel?", a: "Michelangelo", points: 400, type: "text" },
    { q: "Which scientist proposed the theory of evolution by natural selection?", a: "Charles Darwin", points: 400, type: "text" },
    { q: "Who was the British Prime Minister during most of World War II?", a: "Winston Churchill", points: 400, type: "text" },
    { q: "Which composer wrote his Ninth Symphony while deaf?", a: "Ludwig van Beethoven", points: 400, type: "text" },
    { q: "Who was the queen of Egypt linked with Caesar and Mark Antony?", a: "Cleopatra", points: 400, type: "text" },
    { q: "Which woman won Nobel Prizes in both Physics and Chemistry?", a: "Marie Curie", points: 600, type: "text" },
    { q: "Who led India to independence through nonviolent civil disobedience?", a: "Mahatma Gandhi", points: 600, type: "text" },
    { q: "Which explorer is credited with reaching the Americas in 1492?", a: "Christopher Columbus", points: 600, type: "text" },
    { q: "Who wrote the novel Pride and Prejudice?", a: "Jane Austen", points: 600, type: "text" },
    { q: "Which artist is famous for painting The Starry Night?", a: "Vincent van Gogh", points: 600, type: "text" },
    { q: "Who was the first female Prime Minister of the United Kingdom?", a: "Margaret Thatcher", points: 600, type: "text" },
    { q: "Which ancient Greek philosopher tutored Alexander the Great?", a: "Aristotle", points: 800, type: "text" },
    { q: "Which Italian astronomer was tried by the Church for supporting heliocentrism?", a: "Galileo Galilei", points: 800, type: "text" },
    { q: "Who was the Roman general assassinated on the Ides of March?", a: "Julius Caesar", points: 800, type: "text" },
    { q: "Which Polish astronomer proposed that the Sun is the center of the solar system?", a: "Nicolaus Copernicus", points: 800, type: "text" },
    { q: "Who was the leader of the Soviet Union during World War II?", a: "Joseph Stalin", points: 800, type: "text" },
    { q: "Which American inventor and Founding Father experimented with electricity?", a: "Benjamin Franklin", points: 800, type: "text" },
    { q: "Which French military leader crowned himself Emperor in 1804?", a: "Napoleon Bonaparte", points: 1000, type: "text" },
    { q: "Which Austrian composer wrote the opera The Magic Flute?", a: "Wolfgang Amadeus Mozart", points: 1000, type: "text" },
    { q: "Who was the English naturalist that wrote On the Origin of Species?", a: "Charles Darwin", points: 1000, type: "text" },
    { q: "Which Mongol leader founded the largest contiguous land empire in history?", a: "Genghis Khan", points: 1000, type: "text" },
    { q: "Who was the first woman to fly solo across the Atlantic Ocean?", a: "Amelia Earhart", points: 1000, type: "text" },
    { q: "Which nun won the Nobel Peace Prize for her charitable work in Kolkata?", a: "Mother Teresa", points: 1000, type: "text" }
  ],
  "Technology & Inventions": [
    { q: "Which company makes the iPhone?", a: "Apple", points: 200, type: "text" },
    { q: "What does the abbreviation WWW stand for?", a: "World Wide Web", points: 200, type: "text" },
    { q: "Which device is used to type letters and numbers into a computer?", a: "Keyboard", points: 200, type: "text" },
    { q: "What is the popular video-sharing website owned by Google?", a: "YouTube", points: 200, type: "text" },
    { q: "Which company created the Windows operating system?", a: "Microsoft", points: 200, type: "text" },
    { q: "What do we call a portable computer that folds shut?", a: "Laptop", points: 200, type: "text" },
    { q: "Who is credited with inventing the telephone?", a: "Alexander Graham Bell", points: 400, type: "text" },
    { q: "Which inventor developed the first practical electric light bulb?", a: "Thomas Edison", points: 400, type: "text" },
    { q: "What does the acronym GPS stand for?", a: "Global Positioning System", points: 400, type: "text" },
    { q: "What is the name of the search engine founded by Larry Page and Sergey Brin?", a: "Google", points: 400, type: "text" },
    { q: "What does CPU stand for in computing?", a: "Central Processing Unit", points: 400, type: "text" },
    { q: "Which company developed the Android mobile operating system?", a: "Google", points: 400, type: "text" },
    { q: "Who is widely credited with inventing the World Wide Web?", a: "Tim Berners-Lee", points: 600, type: "text" },
    { q: "Which Italian inventor pioneered long-distance radio transmission?", a: "Guglielmo Marconi", points: 600, type: "text" },
    { q: "What does the abbreviation USB stand for?", a: "Universal Serial Bus", points: 600, type: "text" },
    { q: "What was the name of Ford's first mass-produced car?", a: "Model T", points: 600, type: "text" },
    { q: "What does the acronym RAM stand for in computers?", a: "Random Access Memory", points: 600, type: "text" },
    { q: "Which company introduced the first Macintosh personal computer?", a: "Apple", points: 600, type: "text" },
    { q: "Which two brothers built and flew the first powered airplane?", a: "The Wright Brothers", points: 800, type: "text" },
    { q: "Who invented the printing press with movable type in Europe?", a: "Johannes Gutenberg", points: 800, type: "text" },
    { q: "What does the acronym HTML stand for?", a: "HyperText Markup Language", points: 800, type: "text" },
    { q: "Which Serbian-American inventor pioneered alternating current?", a: "Nikola Tesla", points: 800, type: "text" },
    { q: "What was the name of the first general-purpose electronic computer, from 1945?", a: "ENIAC", points: 800, type: "text" },
    { q: "What does the acronym LASER stand for?", a: "Light Amplification by Stimulated Emission of Radiation", points: 800, type: "text" },
    { q: "Who is credited with inventing dynamite and founding a famous set of prizes?", a: "Alfred Nobel", points: 1000, type: "text" },
    { q: "Which Scottish engineer greatly improved the steam engine in the 1700s?", a: "James Watt", points: 1000, type: "text" },
    { q: "Who developed the polio vaccine in the 1950s?", a: "Jonas Salk", points: 1000, type: "text" },
    { q: "Which programming language, released in 1995, was named after coffee?", a: "Java", points: 1000, type: "text" },
    { q: "What set of protocols underlies the modern internet?", a: "TCP/IP", points: 1000, type: "text" },
    { q: "Who is often called the first computer programmer for her work in the 1800s?", a: "Ada Lovelace", points: 1000, type: "text" }
  ],
  "Space & Astronomy": [
    { q: "Which planet do we live on?", a: "Earth", points: 200, type: "text" },
    { q: "What is the closest star to Earth?", a: "The Sun", points: 200, type: "text" },
    { q: "Which planet is known as the Red Planet?", a: "Mars", points: 200, type: "text" },
    { q: "What natural satellite orbits the Earth?", a: "The Moon", points: 200, type: "text" },
    { q: "Which is the largest planet in our solar system?", a: "Jupiter", points: 200, type: "text" },
    { q: "What galaxy do we live in?", a: "The Milky Way", points: 200, type: "text" },
    { q: "Which planet is famous for its prominent rings?", a: "Saturn", points: 400, type: "text" },
    { q: "Which planet is closest to the Sun?", a: "Mercury", points: 400, type: "text" },
    { q: "What do we call a rocky object that burns up entering Earth's atmosphere?", a: "A meteor", points: 400, type: "text" },
    { q: "Which space telescope was launched in 1990 and named after an astronomer?", a: "Hubble Space Telescope", points: 400, type: "text" },
    { q: "What is the name of the space agency of the United States?", a: "NASA", points: 400, type: "text" },
    { q: "How many planets are in our solar system?", a: "Eight", points: 400, type: "text" },
    { q: "Which planet is known for a giant storm called the Great Red Spot?", a: "Jupiter", points: 600, type: "text" },
    { q: "What was the first artificial satellite, launched by the USSR in 1957?", a: "Sputnik", points: 600, type: "text" },
    { q: "Who was the first human to travel into space?", a: "Yuri Gagarin", points: 600, type: "text" },
    { q: "What do we call the path one object takes around another in space?", a: "An orbit", points: 600, type: "text" },
    { q: "Which planet is the hottest in our solar system?", a: "Venus", points: 600, type: "text" },
    { q: "What was the name of the NASA program that first landed humans on the Moon?", a: "Apollo", points: 600, type: "text" },
    { q: "What is the boundary around a black hole beyond which nothing escapes?", a: "The event horizon", points: 800, type: "text" },
    { q: "Which body was reclassified as a dwarf planet in 2006?", a: "Pluto", points: 800, type: "text" },
    { q: "What is the name of the largest moon of Saturn?", a: "Titan", points: 800, type: "text" },
    { q: "Which gas makes up the majority of the Sun's mass?", a: "Hydrogen", points: 800, type: "text" },
    { q: "What do we call a star that suddenly explodes and brightens dramatically?", a: "A supernova", points: 800, type: "text" },
    { q: "Which planet has the largest volcano in the solar system, Olympus Mons?", a: "Mars", points: 800, type: "text" },
    { q: "What is the closest star to our Sun, other than the Sun itself?", a: "Proxima Centauri", points: 1000, type: "text" },
    { q: "Which scientist formulated the three laws of planetary motion?", a: "Johannes Kepler", points: 1000, type: "text" },
    { q: "Which galaxy is on a collision course with the Milky Way?", a: "Andromeda", points: 1000, type: "text" },
    { q: "What unit of distance equals the distance light travels in one year?", a: "A light-year", points: 1000, type: "text" },
    { q: "Which planet has the fastest winds and a deep blue color?", a: "Neptune", points: 1000, type: "text" },
    { q: "What is the name of the theory describing the origin of the universe?", a: "The Big Bang", points: 1000, type: "text" }
  ],
  "Art & Literature": [
    { q: "Who wrote the play Romeo and Juliet?", a: "William Shakespeare", points: 200, type: "text" },
    { q: "Who painted the Mona Lisa?", a: "Leonardo da Vinci", points: 200, type: "text" },
    { q: "Who is the boy wizard at the center of J.K. Rowling's book series?", a: "Harry Potter", points: 200, type: "text" },
    { q: "Who wrote the play Hamlet?", a: "William Shakespeare", points: 200, type: "text" },
    { q: "Which artist famously cut off part of his own ear?", a: "Vincent van Gogh", points: 200, type: "text" },
    { q: "What is the first book of the Bible?", a: "Genesis", points: 200, type: "text" },
    { q: "Who wrote the novel Pride and Prejudice?", a: "Jane Austen", points: 400, type: "text" },
    { q: "Who painted the ceiling of the Sistine Chapel?", a: "Michelangelo", points: 400, type: "text" },
    { q: "Who wrote the novel Oliver Twist?", a: "Charles Dickens", points: 400, type: "text" },
    { q: "Which Russian author wrote the novel War and Peace?", a: "Leo Tolstoy", points: 400, type: "text" },
    { q: "Who created the detective character Sherlock Holmes?", a: "Arthur Conan Doyle", points: 400, type: "text" },
    { q: "Who wrote the play A Midsummer Night's Dream?", a: "William Shakespeare", points: 400, type: "text" },
    { q: "Who wrote the novel The Old Man and the Sea?", a: "Ernest Hemingway", points: 600, type: "text" },
    { q: "Which Dutch artist painted The Starry Night?", a: "Vincent van Gogh", points: 600, type: "text" },
    { q: "Who wrote the novel Crime and Punishment?", a: "Fyodor Dostoevsky", points: 600, type: "text" },
    { q: "Which Spanish artist co-founded the Cubism movement?", a: "Pablo Picasso", points: 600, type: "text" },
    { q: "Who wrote the novel Great Expectations?", a: "Charles Dickens", points: 600, type: "text" },
    { q: "Which English author created the world of Middle-earth?", a: "J.R.R. Tolkien", points: 600, type: "text" },
    { q: "Who wrote the epic poem The Divine Comedy?", a: "Dante Alighieri", points: 800, type: "text" },
    { q: "Which artist painted the melting clocks in The Persistence of Memory?", a: "Salvador Dali", points: 800, type: "text" },
    { q: "Who wrote the novel Anna Karenina?", a: "Leo Tolstoy", points: 800, type: "text" },
    { q: "Which English poet wrote Paradise Lost?", a: "John Milton", points: 800, type: "text" },
    { q: "Which French author wrote The Hunchback of Notre-Dame?", a: "Victor Hugo", points: 800, type: "text" },
    { q: "Which artist created the Campbell's Soup Cans artworks?", a: "Andy Warhol", points: 800, type: "text" },
    { q: "Who wrote the play Waiting for Godot?", a: "Samuel Beckett", points: 1000, type: "text" },
    { q: "Which artist painted Guernica?", a: "Pablo Picasso", points: 1000, type: "text" },
    { q: "Who wrote the novel Ulysses?", a: "James Joyce", points: 1000, type: "text" },
    { q: "Which Norwegian artist painted The Scream?", a: "Edvard Munch", points: 1000, type: "text" },
    { q: "Who wrote the novel Don Quixote?", a: "Miguel de Cervantes", points: 1000, type: "text" },
    { q: "Which Dutch artist painted Girl with a Pearl Earring?", a: "Johannes Vermeer", points: 1000, type: "text" }
  ],
  "Pop Culture": [
    { q: "Which superhero is known as the Caped Crusader and protects Gotham City?", a: "Batman", points: 200, type: "text" },
    { q: "What is the name of the wizarding school in the Harry Potter films?", a: "Hogwarts", points: 200, type: "text" },
    { q: "Which animated mouse is the mascot of the Walt Disney Company?", a: "Mickey Mouse", points: 200, type: "text" },
    { q: "Which band recorded the album Abbey Road?", a: "The Beatles", points: 200, type: "text" },
    { q: "What is the name of the toy cowboy in the film Toy Story?", a: "Woody", points: 200, type: "text" },
    { q: "Which green ogre stars in a DreamWorks film of the same name?", a: "Shrek", points: 200, type: "text" },
    { q: "Which singer is known as the King of Pop?", a: "Michael Jackson", points: 400, type: "text" },
    { q: "In Star Wars, what is the name of Luke Skywalker's father?", a: "Darth Vader", points: 400, type: "text" },
    { q: "Which film about a sinking ship stars Leonardo DiCaprio?", a: "Titanic", points: 400, type: "text" },
    { q: "What is the name of the fictional nation ruled by Black Panther?", a: "Wakanda", points: 400, type: "text" },
    { q: "Who was the lead singer of the band Queen?", a: "Freddie Mercury", points: 400, type: "text" },
    { q: "In The Lion King, what is the name of the young lion prince?", a: "Simba", points: 400, type: "text" },
    { q: "Which actor played Jack Sparrow in Pirates of the Caribbean?", a: "Johnny Depp", points: 600, type: "text" },
    { q: "Which artist released the best-selling album Thriller?", a: "Michael Jackson", points: 600, type: "text" },
    { q: "In The Wizard of Oz, what color are Dorothy's slippers in the film?", a: "Ruby red", points: 600, type: "text" },
    { q: "Which director made the films Jaws and E.T. the Extra-Terrestrial?", a: "Steven Spielberg", points: 600, type: "text" },
    { q: "Which superhero team includes Iron Man, Thor, and Captain America?", a: "The Avengers", points: 600, type: "text" },
    { q: "Which actress played Hermione Granger in the Harry Potter films?", a: "Emma Watson", points: 600, type: "text" },
    { q: "Which band performed the song Bohemian Rhapsody?", a: "Queen", points: 800, type: "text" },
    { q: "Which 1984 sci-fi film features the catchphrase 'I'll be back'?", a: "The Terminator", points: 800, type: "text" },
    { q: "Who directed the film Pulp Fiction?", a: "Quentin Tarantino", points: 800, type: "text" },
    { q: "In Star Wars, what is the name of Han Solo's spaceship?", a: "The Millennium Falcon", points: 800, type: "text" },
    { q: "Which singer is known as the Material Girl?", a: "Madonna", points: 800, type: "text" },
    { q: "Which superhero is also known as the Man of Steel?", a: "Superman", points: 800, type: "text" },
    { q: "Who composed the music for the films Star Wars and Jurassic Park?", a: "John Williams", points: 1000, type: "text" },
    { q: "Which actor played the Joker in the 2008 film The Dark Knight?", a: "Heath Ledger", points: 1000, type: "text" },
    { q: "Which band released the album The Dark Side of the Moon?", a: "Pink Floyd", points: 1000, type: "text" },
    { q: "Who directed the films Vertigo and Psycho?", a: "Alfred Hitchcock", points: 1000, type: "text" },
    { q: "Which Swedish pop group won Eurovision in 1974 with the song Waterloo?", a: "ABBA", points: 1000, type: "text" },
    { q: "Which actor played Forrest Gump in the 1994 film?", a: "Tom Hanks", points: 1000, type: "text" }
  ],
  "Famous Landmarks": [
    { q: "In which city is the Eiffel Tower located?", a: "Paris", points: 200, type: "text" },
    { q: "In which city is the Statue of Liberty located?", a: "New York City", points: 200, type: "text" },
    { q: "In which country is the Great Wall located?", a: "China", points: 200, type: "text" },
    { q: "In which Italian city is the Colosseum located?", a: "Rome", points: 200, type: "text" },
    { q: "In which country are the Great Pyramids of Giza located?", a: "Egypt", points: 200, type: "text" },
    { q: "In which city is Big Ben located?", a: "London", points: 200, type: "text" },
    { q: "In which Indian city is the Taj Mahal located?", a: "Agra", points: 400, type: "text" },
    { q: "In which country is the Leaning Tower of Pisa located?", a: "Italy", points: 400, type: "text" },
    { q: "In which city is the Sydney Opera House located?", a: "Sydney", points: 400, type: "text" },
    { q: "In which country is the ancient city of Machu Picchu located?", a: "Peru", points: 400, type: "text" },
    { q: "In which city is the Brandenburg Gate located?", a: "Berlin", points: 400, type: "text" },
    { q: "On which Greek hill is the Parthenon located?", a: "The Acropolis", points: 400, type: "text" },
    { q: "In which country is the rock city of Petra located?", a: "Jordan", points: 600, type: "text" },
    { q: "In which Russian city is Red Square located?", a: "Moscow", points: 600, type: "text" },
    { q: "In which country is the temple complex of Angkor Wat located?", a: "Cambodia", points: 600, type: "text" },
    { q: "In which Brazilian city is the Christ the Redeemer statue located?", a: "Rio de Janeiro", points: 600, type: "text" },
    { q: "In which US state is the Grand Canyon located?", a: "Arizona", points: 600, type: "text" },
    { q: "In which Spanish city is the Sagrada Familia church located?", a: "Barcelona", points: 600, type: "text" },
    { q: "In which country is the temple of Borobudur located?", a: "Indonesia", points: 800, type: "text" },
    { q: "In which city is the Trevi Fountain located?", a: "Rome", points: 800, type: "text" },
    { q: "In which country is the prehistoric monument Stonehenge located?", a: "England", points: 800, type: "text" },
    { q: "In which Turkish city is the Hagia Sophia located?", a: "Istanbul", points: 800, type: "text" },
    { q: "In which country is the salt flat Salar de Uyuni located?", a: "Bolivia", points: 800, type: "text" },
    { q: "In which US city is the Golden Gate Bridge located?", a: "San Francisco", points: 800, type: "text" },
    { q: "In which country is Neuschwanstein Castle located?", a: "Germany", points: 1000, type: "text" },
    { q: "In which city is the Charles Bridge located?", a: "Prague", points: 1000, type: "text" },
    { q: "In which country is the ancient temple of Karnak located?", a: "Egypt", points: 1000, type: "text" },
    { q: "In which Saudi Arabian city is the Kaaba located?", a: "Mecca", points: 1000, type: "text" },
    { q: "In which country is the Chichen Itza pyramid located?", a: "Mexico", points: 1000, type: "text" },
    { q: "In which African country is the rock-hewn church of Lalibela located?", a: "Ethiopia", points: 1000, type: "text" }
  ]
};
